/**
 * Vietnamese food database
 * 
 * Nutritional information for Vietnamese foods
 */

export interface FoodItem {
  id: string;
  code: string; // Mã số (ví dụ: "10001") - required for food-database tool
  name: string;
  nameEn?: string;
  category: FoodCategory;
  servingSize: number; // in grams (luôn 100g để chuẩn hóa)
  servingUnit: string; // "g"
  calories: number; // per 100g
  protein: number; // grams per 100g
  carbs: number; // grams per 100g
  fat: number; // grams per 100g
  water?: number; // grams per 100g
  fiber?: number; // grams per 100g
  sodium?: number; // mg per 100g
  potassium?: number; // mg per 100g (K)
  calcium?: number; // mg per 100g (Ca)
  iron?: number; // mg per 100g (Fe)
  phosphorus?: number; // mg per 100g (P)
  magnesium?: number; // mg per 100g (Mg)
  zinc?: number; // mg per 100g (Zn)
  vitaminC?: number; // mg per 100g
  vitaminA?: number; // IU or mcg per 100g
  cholesterol?: number; // mg per 100g
  notes?: string;
  commonServing?: string;
}

export type FoodCategory =
  | "rice-noodles"
  | "meat"
  | "seafood"
  | "vegetables"
  | "fruits"
  | "legumes"
  | "dairy"
  | "condiments"
  | "beverages"
  | "snacks"
  | "soups"
  | "desserts";

export const foodDatabase: FoodItem[] = [
  // Rice & Noodles
  {
    id: "com-trang",
    code: "10001",
    name: "Cơm trắng",
    nameEn: "White rice",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    water: 68.4,
    fiber: 0.4,
    sodium: 1,
    potassium: 35,
    calcium: 8,
    iron: 0.8,
    phosphorus: 33,
    magnesium: 12,
    zinc: 0.4,
    commonServing: "1 bát nhỏ (100g)",
  },
  {
    id: "pho-bo",
    code: "10002",
    name: "Phở bò",
    nameEn: "Beef pho",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 117, // 350/3 normalized to 100g
    protein: 6.7, // 20/3
    carbs: 15, // 45/3
    fat: 2.7, // 8/3
    water: 75,
    fiber: 0.7, // 2/3
    sodium: 400, // 1200/3
    potassium: 80,
    calcium: 15,
    iron: 1.2,
    phosphorus: 50,
    magnesium: 18,
    zinc: 0.8,
    commonServing: "1 tô vừa (300g)",
    notes: "Bao gồm bánh phở, thịt bò, nước dùng",
  },
  {
    id: "bun-cha",
    code: "10003",
    name: "Bún chả",
    nameEn: "Grilled pork with noodles",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 168, // 420/2.5 normalized to 100g
    protein: 10, // 25/2.5
    carbs: 20, // 50/2.5
    fat: 4.8, // 12/2.5
    water: 65,
    fiber: 0.6, // 1.5/2.5
    sodium: 320, // 800/2.5
    potassium: 120,
    calcium: 20,
    iron: 1.5,
    phosphorus: 60,
    magnesium: 22,
    zinc: 1.2,
    commonServing: "1 phần (250g)",
  },

  // Meat
  {
    id: "thit-heo-nac",
    code: "20001",
    name: "Thịt heo nạc",
    nameEn: "Lean pork",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 143,
    protein: 27,
    carbs: 0,
    fat: 3.5,
    water: 69,
    sodium: 62,
    potassium: 360,
    calcium: 8,
    iron: 0.9,
    phosphorus: 220,
    magnesium: 25,
    zinc: 2.1,
    cholesterol: 62,
    commonServing: "100g (khoảng 1 lòng bàn tay)",
  },
  {
    id: "thit-ga",
    code: "20002",
    name: "Thịt gà",
    nameEn: "Chicken",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    water: 65,
    sodium: 74,
    potassium: 256,
    calcium: 15,
    iron: 0.9,
    phosphorus: 220,
    magnesium: 28,
    zinc: 1.3,
    cholesterol: 85,
    commonServing: "100g (khoảng 1 lòng bàn tay)",
  },
  {
    id: "thit-bo",
    code: "20003",
    name: "Thịt bò",
    nameEn: "Beef",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    water: 58,
    sodium: 72,
    potassium: 315,
    calcium: 18,
    iron: 2.6,
    phosphorus: 198,
    magnesium: 21,
    zinc: 4.8,
    cholesterol: 90,
    commonServing: "100g (khoảng 1 lòng bàn tay)",
  },

  // Seafood
  {
    id: "ca-basa",
    code: "30001",
    name: "Cá basa",
    nameEn: "Basa fish",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 162,
    protein: 18,
    carbs: 0,
    fat: 9,
    water: 72,
    sodium: 45,
    potassium: 280,
    calcium: 15,
    iron: 0.5,
    phosphorus: 200,
    magnesium: 25,
    zinc: 0.8,
    cholesterol: 55,
    commonServing: "100g (1 miếng vừa)",
  },
  {
    id: "tom",
    code: "30002",
    name: "Tôm",
    nameEn: "Shrimp",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
    water: 75,
    sodium: 111,
    potassium: 259,
    calcium: 52,
    iron: 0.3,
    phosphorus: 237,
    magnesium: 37,
    zinc: 1.1,
    cholesterol: 152,
    commonServing: "100g (khoảng 8-10 con vừa)",
  },

  // Vegetables
  {
    id: "rau-muong",
    code: "40001",
    name: "Rau muống",
    nameEn: "Water spinach",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 19,
    protein: 2.6,
    carbs: 3.1,
    fat: 0.2,
    water: 92,
    fiber: 2.1,
    sodium: 79,
    potassium: 312,
    calcium: 77,
    iron: 1.7,
    phosphorus: 39,
    magnesium: 71,
    zinc: 0.4,
    vitaminC: 55,
    vitaminA: 3158,
    commonServing: "100g (1 bó nhỏ)",
  },
  {
    id: "cai-xanh",
    code: "40002",
    name: "Cải xanh",
    nameEn: "Chinese cabbage",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 16,
    protein: 1.5,
    carbs: 3.2,
    fat: 0.2,
    water: 95,
    fiber: 1.2,
    sodium: 65,
    potassium: 252,
    calcium: 105,
    iron: 0.8,
    phosphorus: 37,
    magnesium: 19,
    zinc: 0.2,
    vitaminC: 36,
    vitaminA: 4468,
    commonServing: "100g",
  },
  {
    id: "ca-chua",
    code: "40003",
    name: "Cà chua",
    nameEn: "Tomato",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    water: 94,
    fiber: 1.2,
    sodium: 5,
    potassium: 237,
    calcium: 10,
    iron: 0.3,
    phosphorus: 24,
    magnesium: 11,
    zinc: 0.2,
    vitaminC: 14,
    vitaminA: 833,
    commonServing: "100g (1-2 quả vừa)",
  },

  // Fruits
  {
    id: "chuoi",
    code: "50001",
    name: "Chuối",
    nameEn: "Banana",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    water: 75,
    fiber: 2.6,
    sodium: 1,
    potassium: 358,
    calcium: 5,
    iron: 0.3,
    phosphorus: 22,
    magnesium: 27,
    zinc: 0.2,
    vitaminC: 8.7,
    commonServing: "100g (1 quả vừa)",
  },
  {
    id: "cam",
    code: "50002",
    name: "Cam",
    nameEn: "Orange",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    water: 87,
    fiber: 2.4,
    sodium: 0,
    potassium: 181,
    calcium: 40,
    iron: 0.1,
    phosphorus: 14,
    magnesium: 10,
    zinc: 0.1,
    vitaminC: 53.2,
    vitaminA: 225,
    commonServing: "100g (1 quả vừa)",
  },

  // Legumes
  {
    id: "dau-phu",
    code: "60001",
    name: "Đậu phụ",
    nameEn: "Tofu",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 76,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
    water: 85,
    fiber: 0.3,
    sodium: 7,
    potassium: 121,
    calcium: 350,
    iron: 5.4,
    phosphorus: 97,
    magnesium: 30,
    zinc: 0.8,
    commonServing: "100g (1 miếng vừa)",
  },
  {
    id: "dau-xanh",
    code: "60002",
    name: "Đậu xanh",
    nameEn: "Mung beans",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 347,
    protein: 24,
    carbs: 63,
    fat: 1.2,
    water: 10,
    fiber: 16.3,
    sodium: 15,
    potassium: 1246,
    calcium: 132,
    iron: 6.7,
    phosphorus: 367,
    magnesium: 189,
    zinc: 2.8,
    commonServing: "100g (nấu chín)",
  },

  // Condiments
  {
    id: "nuoc-mam",
    code: "70001",
    name: "Nước mắm",
    nameEn: "Fish sauce",
    category: "condiments",
    servingSize: 100,
    servingUnit: "g",
    calories: 53, // 8/15*100 normalized to 100g
    protein: 8.7, // 1.3/15*100
    carbs: 5.3, // 0.8/15*100
    fat: 0,
    water: 85,
    sodium: 10000, // 1500/15*100
    potassium: 200,
    calcium: 20,
    iron: 0.5,
    phosphorus: 50,
    magnesium: 15,
    zinc: 0.3,
    commonServing: "1 muỗng canh (15ml)",
    notes: "Rất nhiều natri - dùng ít cho người tăng huyết áp",
  },
  {
    id: "tuong-ot",
    code: "70002",
    name: "Tương ớt",
    nameEn: "Chili sauce",
    category: "condiments",
    servingSize: 100,
    servingUnit: "g",
    calories: 100, // 15/15*100 normalized to 100g
    protein: 2, // 0.3/15*100
    carbs: 23.3, // 3.5/15*100
    fat: 0.7, // 0.1/15*100
    water: 73,
    sodium: 1333, // 200/15*100
    potassium: 150,
    calcium: 10,
    iron: 0.3,
    phosphorus: 30,
    magnesium: 12,
    zinc: 0.2,
    vitaminC: 33, // 5/15*100
    commonServing: "1 muỗng canh (15g)",
  },

  // Dairy
  {
    id: "sua-bo-tuoi",
    code: "80001",
    name: "Sữa bò tươi",
    nameEn: "Fresh cow milk",
    category: "dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 61,
    protein: 3.2,
    carbs: 4.7,
    fat: 3.3,
    water: 88,
    sodium: 44,
    potassium: 150,
    calcium: 120,
    iron: 0.1,
    phosphorus: 95,
    magnesium: 12,
    zinc: 0.4,
    vitaminA: 46,
    vitaminC: 1,
    cholesterol: 10,
    commonServing: "100ml (1 ly nhỏ)",
  },
  {
    id: "sua-chua",
    code: "80002",
    name: "Sữa chua",
    nameEn: "Yogurt",
    category: "dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 61,
    protein: 3.3,
    carbs: 4.7,
    fat: 3.3,
    water: 88,
    sodium: 36,
    potassium: 155,
    calcium: 110,
    iron: 0.1,
    phosphorus: 85,
    magnesium: 12,
    zinc: 0.6,
    vitaminA: 27,
    vitaminC: 0.5,
    cholesterol: 13,
    commonServing: "100g (1 hũ nhỏ)",
  },
  {
    id: "sua-dau-nanh",
    code: "80003",
    name: "Sữa đậu nành",
    nameEn: "Soy milk",
    category: "dairy",
    servingSize: 100,
    servingUnit: "ml",
    calories: 33,
    protein: 2.9,
    carbs: 1.8,
    fat: 1.6,
    water: 93,
    sodium: 4,
    potassium: 118,
    calcium: 25,
    iron: 0.6,
    phosphorus: 52,
    magnesium: 25,
    zinc: 0.2,
    vitaminA: 0,
    commonServing: "100ml (1 ly nhỏ)",
  },
  {
    id: "pho-mai",
    code: "80004",
    name: "Phô mai",
    nameEn: "Cheese",
    category: "dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 300,
    protein: 25,
    carbs: 1.3,
    fat: 22,
    water: 50,
    sodium: 621,
    potassium: 95,
    calcium: 721,
    iron: 0.7,
    phosphorus: 512,
    magnesium: 28,
    zinc: 2.5,
    vitaminA: 1002,
    cholesterol: 100,
    commonServing: "100g (1 miếng vừa)",
  },
  {
    id: "trung-ga",
    code: "80005",
    name: "Trứng gà",
    nameEn: "Chicken egg",
    category: "dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    water: 75,
    sodium: 124,
    potassium: 138,
    calcium: 56,
    iron: 1.8,
    phosphorus: 198,
    magnesium: 12,
    zinc: 1.3,
    vitaminA: 160,
    vitaminC: 0,
    cholesterol: 372,
    commonServing: "100g (khoảng 2 quả)",
  },

  // More Rice & Noodles
  {
    id: "bun-ga",
    code: "10004",
    name: "Bún gà",
    nameEn: "Chicken noodle soup",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 95,
    protein: 5.5,
    carbs: 12,
    fat: 2.5,
    water: 79,
    fiber: 0.5,
    sodium: 350,
    potassium: 85,
    calcium: 12,
    iron: 0.8,
    phosphorus: 45,
    magnesium: 15,
    zinc: 0.6,
    cholesterol: 25,
    commonServing: "1 tô vừa (300g)",
  },
  {
    id: "banh-mi",
    code: "10005",
    name: "Bánh mì",
    nameEn: "Vietnamese bread",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 265,
    protein: 8.2,
    carbs: 51,
    fat: 3.2,
    water: 36,
    fiber: 2.7,
    sodium: 491,
    potassium: 115,
    calcium: 20,
    iron: 3.6,
    phosphorus: 98,
    magnesium: 25,
    zinc: 0.7,
    commonServing: "100g (1 ổ vừa)",
  },
  {
    id: "mien",
    code: "10006",
    name: "Miến",
    nameEn: "Glass noodles",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 351,
    protein: 0.2,
    carbs: 86,
    fat: 0.1,
    water: 13,
    fiber: 0.2,
    sodium: 4,
    potassium: 5,
    calcium: 4,
    iron: 0.1,
    phosphorus: 2,
    magnesium: 1,
    zinc: 0.1,
    commonServing: "100g (khô)",
  },

  // More Meat
  {
    id: "thit-vit",
    code: "20004",
    name: "Thịt vịt",
    nameEn: "Duck meat",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 337,
    protein: 19,
    carbs: 0,
    fat: 28,
    water: 52,
    sodium: 83,
    potassium: 271,
    calcium: 12,
    iron: 2.7,
    phosphorus: 188,
    magnesium: 19,
    zinc: 2.6,
    cholesterol: 76,
    commonServing: "100g (khoảng 1 lòng bàn tay)",
  },
  {
    id: "thit-heo-ba-chi",
    code: "20005",
    name: "Thịt heo ba chỉ",
    nameEn: "Pork belly",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 518,
    protein: 9.3,
    carbs: 0,
    fat: 53,
    water: 37,
    sodium: 54,
    potassium: 185,
    calcium: 5,
    iron: 0.8,
    phosphorus: 83,
    magnesium: 8,
    zinc: 1.1,
    cholesterol: 72,
    commonServing: "100g",
  },
  {
    id: "gan-heo",
    code: "20006",
    name: "Gan heo",
    nameEn: "Pork liver",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 134,
    protein: 21,
    carbs: 3.8,
    fat: 3.4,
    water: 71,
    sodium: 87,
    potassium: 300,
    calcium: 8,
    iron: 23,
    phosphorus: 363,
    magnesium: 21,
    zinc: 6.7,
    vitaminA: 6502,
    vitaminC: 23,
    cholesterol: 301,
    commonServing: "100g",
  },

  // More Seafood
  {
    id: "ca-rot",
    code: "30003",
    name: "Cá rô",
    nameEn: "Climbing perch",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 103,
    protein: 20,
    carbs: 0,
    fat: 2.1,
    water: 77,
    sodium: 65,
    potassium: 317,
    calcium: 26,
    iron: 0.5,
    phosphorus: 200,
    magnesium: 25,
    zinc: 0.8,
    cholesterol: 66,
    commonServing: "100g (1 con vừa)",
  },
  {
    id: "ca-chep",
    code: "30004",
    name: "Cá chép",
    nameEn: "Carp",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 127,
    protein: 18,
    carbs: 0,
    fat: 5.6,
    water: 76,
    sodium: 49,
    potassium: 333,
    calcium: 50,
    iron: 0.8,
    phosphorus: 200,
    magnesium: 29,
    zinc: 1.5,
    cholesterol: 84,
    commonServing: "100g",
  },
  {
    id: "cua",
    code: "30005",
    name: "Cua",
    nameEn: "Crab",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 97,
    protein: 19,
    carbs: 0.1,
    fat: 1.5,
    water: 79,
    sodium: 395,
    potassium: 259,
    calcium: 91,
    iron: 0.8,
    phosphorus: 234,
    magnesium: 34,
    zinc: 3.8,
    vitaminA: 1,
    cholesterol: 78,
    commonServing: "100g (thịt cua)",
  },

  // More Vegetables
  {
    id: "ca-rot-rau",
    code: "40004",
    name: "Cà rốt",
    nameEn: "Carrot",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    water: 88,
    fiber: 2.8,
    sodium: 69,
    potassium: 320,
    calcium: 33,
    iron: 0.3,
    phosphorus: 35,
    magnesium: 12,
    zinc: 0.2,
    vitaminC: 5.9,
    vitaminA: 835,
    commonServing: "100g (1 củ vừa)",
  },
  {
    id: "bap-cai",
    code: "40005",
    name: "Bắp cải",
    nameEn: "Cabbage",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 25,
    protein: 1.3,
    carbs: 6,
    fat: 0.1,
    water: 92,
    fiber: 2.5,
    sodium: 18,
    potassium: 170,
    calcium: 40,
    iron: 0.5,
    phosphorus: 26,
    magnesium: 12,
    zinc: 0.2,
    vitaminC: 36.6,
    vitaminA: 98,
    commonServing: "100g",
  },
  {
    id: "khoai-tay",
    code: "40006",
    name: "Khoai tây",
    nameEn: "Potato",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    water: 80,
    fiber: 2.2,
    sodium: 6,
    potassium: 421,
    calcium: 12,
    iron: 0.8,
    phosphorus: 57,
    magnesium: 23,
    zinc: 0.3,
    vitaminC: 19.7,
    commonServing: "100g (1 củ vừa)",
  },
  {
    id: "bi-do",
    code: "40007",
    name: "Bí đỏ",
    nameEn: "Pumpkin",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 26,
    protein: 1,
    carbs: 7,
    fat: 0.1,
    water: 91,
    fiber: 0.5,
    sodium: 1,
    potassium: 340,
    calcium: 21,
    iron: 0.8,
    phosphorus: 44,
    magnesium: 12,
    zinc: 0.3,
    vitaminC: 9,
    vitaminA: 851,
    commonServing: "100g",
  },
  {
    id: "rau-cai",
    code: "40008",
    name: "Rau cải",
    nameEn: "Mustard greens",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 27,
    protein: 2.7,
    carbs: 4.7,
    fat: 0.4,
    water: 91,
    fiber: 1.8,
    sodium: 20,
    potassium: 354,
    calcium: 103,
    iron: 1.5,
    phosphorus: 29,
    magnesium: 32,
    zinc: 0.2,
    vitaminC: 70,
    vitaminA: 3024,
    commonServing: "100g (1 bó nhỏ)",
  },
  {
    id: "dau-bap",
    code: "40009",
    name: "Đậu bắp",
    nameEn: "Okra",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 33,
    protein: 2,
    carbs: 7.5,
    fat: 0.2,
    water: 90,
    fiber: 3.2,
    sodium: 7,
    potassium: 299,
    calcium: 82,
    iron: 0.6,
    phosphorus: 61,
    magnesium: 57,
    zinc: 0.6,
    vitaminC: 23,
    vitaminA: 36,
    commonServing: "100g (10-12 quả)",
  },

  // More Fruits
  {
    id: "tao",
    code: "50003",
    name: "Táo",
    nameEn: "Apple",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    water: 86,
    fiber: 2.4,
    sodium: 1,
    potassium: 107,
    calcium: 6,
    iron: 0.1,
    phosphorus: 11,
    magnesium: 5,
    zinc: 0.04,
    vitaminC: 4.6,
    vitaminA: 3,
    commonServing: "100g (1 quả vừa)",
  },
  {
    id: "dua-hau",
    code: "50004",
    name: "Dưa hấu",
    nameEn: "Watermelon",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 30,
    protein: 0.6,
    carbs: 8,
    fat: 0.2,
    water: 91,
    fiber: 0.4,
    sodium: 1,
    potassium: 112,
    calcium: 7,
    iron: 0.2,
    phosphorus: 11,
    magnesium: 10,
    zinc: 0.1,
    vitaminC: 8.1,
    vitaminA: 28,
    commonServing: "100g (1 miếng nhỏ)",
  },
  {
    id: "xoai",
    code: "50005",
    name: "Xoài",
    nameEn: "Mango",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    water: 83,
    fiber: 1.6,
    sodium: 1,
    potassium: 168,
    calcium: 11,
    iron: 0.2,
    phosphorus: 14,
    magnesium: 10,
    zinc: 0.1,
    vitaminC: 36.4,
    vitaminA: 54,
    commonServing: "100g (1/2 quả vừa)",
  },
  {
    id: "du-du",
    code: "50006",
    name: "Đu đủ",
    nameEn: "Papaya",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 43,
    protein: 0.5,
    carbs: 11,
    fat: 0.3,
    water: 88,
    fiber: 1.7,
    sodium: 8,
    potassium: 182,
    calcium: 20,
    iron: 0.3,
    phosphorus: 10,
    magnesium: 21,
    zinc: 0.1,
    vitaminC: 60.9,
    vitaminA: 55,
    commonServing: "100g (1 miếng vừa)",
  },
  {
    id: "oi",
    code: "50007",
    name: "Ổi",
    nameEn: "Guava",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 68,
    protein: 2.6,
    carbs: 14,
    fat: 1,
    water: 81,
    fiber: 5.4,
    sodium: 2,
    potassium: 417,
    calcium: 18,
    iron: 0.3,
    phosphorus: 40,
    magnesium: 22,
    zinc: 0.2,
    vitaminC: 228.3,
    vitaminA: 31,
    commonServing: "100g (1 quả vừa)",
  },
  {
    id: "nho",
    code: "50008",
    name: "Nho",
    nameEn: "Grapes",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 69,
    protein: 0.7,
    carbs: 18,
    fat: 0.2,
    water: 81,
    fiber: 0.9,
    sodium: 3,
    potassium: 191,
    calcium: 10,
    iron: 0.4,
    phosphorus: 20,
    magnesium: 7,
    zinc: 0.1,
    vitaminC: 10.8,
    vitaminA: 3,
    commonServing: "100g (khoảng 10-15 quả)",
  },

  // More Legumes
  {
    id: "dau-nanh",
    code: "60003",
    name: "Đậu nành",
    nameEn: "Soybeans",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 446,
    protein: 36,
    carbs: 30,
    fat: 20,
    water: 8,
    fiber: 9.3,
    sodium: 2,
    potassium: 1797,
    calcium: 277,
    iron: 15.7,
    phosphorus: 704,
    magnesium: 280,
    zinc: 4.9,
    vitaminC: 6,
    commonServing: "100g (khô)",
  },
  {
    id: "dau-do",
    code: "60004",
    name: "Đậu đỏ",
    nameEn: "Red beans",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 337,
    protein: 22,
    carbs: 63,
    fat: 0.5,
    water: 12,
    fiber: 12.7,
    sodium: 2,
    potassium: 1259,
    calcium: 83,
    iron: 6.7,
    phosphorus: 381,
    magnesium: 138,
    zinc: 2.8,
    vitaminC: 1,
    commonServing: "100g (nấu chín)",
  },
  {
    id: "lac",
    code: "60005",
    name: "Lạc (Đậu phộng)",
    nameEn: "Peanuts",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 567,
    protein: 26,
    carbs: 16,
    fat: 49,
    water: 7,
    fiber: 8.5,
    sodium: 18,
    potassium: 705,
    calcium: 92,
    iron: 4.6,
    phosphorus: 376,
    magnesium: 168,
    zinc: 3.3,
    vitaminC: 0,
    commonServing: "100g (khoảng 1 bát nhỏ)",
  },

  // Beverages
  {
    id: "nuoc-dua",
    code: "90001",
    name: "Nước dừa",
    nameEn: "Coconut water",
    category: "beverages",
    servingSize: 100,
    servingUnit: "ml",
    calories: 19,
    protein: 0.7,
    carbs: 3.7,
    fat: 0.2,
    water: 95,
    sodium: 105,
    potassium: 250,
    calcium: 24,
    iron: 0.3,
    phosphorus: 20,
    magnesium: 25,
    zinc: 0.1,
    vitaminC: 2.4,
    commonServing: "100ml (1 ly nhỏ)",
  },
  {
    id: "nuoc-cam",
    code: "90002",
    name: "Nước cam",
    nameEn: "Orange juice",
    category: "beverages",
    servingSize: 100,
    servingUnit: "ml",
    calories: 45,
    protein: 0.7,
    carbs: 10,
    fat: 0.2,
    water: 89,
    sodium: 1,
    potassium: 200,
    calcium: 11,
    iron: 0.2,
    phosphorus: 17,
    magnesium: 11,
    zinc: 0.1,
    vitaminC: 50,
    vitaminA: 10,
    commonServing: "100ml (1 ly nhỏ)",
  },
  {
    id: "tra-xanh",
    code: "90003",
    name: "Trà xanh",
    nameEn: "Green tea",
    category: "beverages",
    servingSize: 100,
    servingUnit: "ml",
    calories: 2,
    protein: 0.2,
    carbs: 0,
    fat: 0,
    water: 99,
    sodium: 3,
    potassium: 8,
    calcium: 3,
    iron: 0.02,
    phosphorus: 1,
    magnesium: 1,
    zinc: 0.01,
    vitaminC: 0,
    commonServing: "100ml (1 ly)",
  },

  // Snacks
  {
    id: "khoai-lang",
    code: "10007",
    name: "Khoai lang",
    nameEn: "Sweet potato",
    category: "snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    water: 77,
    fiber: 3,
    sodium: 54,
    potassium: 337,
    calcium: 30,
    iron: 0.6,
    phosphorus: 47,
    magnesium: 25,
    zinc: 0.3,
    vitaminC: 2.4,
    vitaminA: 709,
    commonServing: "100g (1 củ vừa)",
  },
  {
    id: "ngu-coc",
    code: "10008",
    name: "Ngô (Bắp)",
    nameEn: "Corn",
    category: "snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 96,
    protein: 3.4,
    carbs: 21,
    fat: 1.2,
    water: 74,
    fiber: 2.4,
    sodium: 1,
    potassium: 270,
    calcium: 2,
    iron: 0.5,
    phosphorus: 89,
    magnesium: 37,
    zinc: 0.5,
    vitaminC: 6.8,
    vitaminA: 9,
    commonServing: "100g (1 bắp nhỏ)",
  },
];

/**
 * Search foods by name
 */
export function searchFoods(query: string): FoodItem[] {
  if (!query.trim()) return [];

  const lowerQuery = query.toLowerCase();
  return foodDatabase.filter(
    (food) =>
      food.name.toLowerCase().includes(lowerQuery) ||
      food.nameEn?.toLowerCase().includes(lowerQuery)
  );
}

/**
 * Get foods by category
 */
export function getFoodsByCategory(category: FoodCategory): FoodItem[] {
  return foodDatabase.filter((food) => food.category === category);
}

/**
 * Get food by ID
 */
export function getFoodById(id: string): FoodItem | undefined {
  return foodDatabase.find((food) => food.id === id);
}

/**
 * Calculate nutrition for multiple servings
 */
export function calculateNutrition(
  food: FoodItem,
  servings: number
): Omit<FoodItem, "id" | "code" | "name" | "nameEn" | "category" | "notes" | "commonServing"> {
  const multiplier = servings;
  return {
    servingSize: food.servingSize * multiplier,
    servingUnit: food.servingUnit,
    calories: food.calories * multiplier,
    protein: food.protein * multiplier,
    carbs: food.carbs * multiplier,
    fat: food.fat * multiplier,
    water: food.water ? food.water * multiplier : undefined,
    fiber: food.fiber ? food.fiber * multiplier : undefined,
    sodium: food.sodium ? food.sodium * multiplier : undefined,
    potassium: food.potassium ? food.potassium * multiplier : undefined,
    calcium: food.calcium ? food.calcium * multiplier : undefined,
    iron: food.iron ? food.iron * multiplier : undefined,
    phosphorus: food.phosphorus ? food.phosphorus * multiplier : undefined,
    magnesium: food.magnesium ? food.magnesium * multiplier : undefined,
    zinc: food.zinc ? food.zinc * multiplier : undefined,
    vitaminC: food.vitaminC ? food.vitaminC * multiplier : undefined,
    vitaminA: food.vitaminA ? food.vitaminA * multiplier : undefined,
    cholesterol: food.cholesterol ? food.cholesterol * multiplier : undefined,
  };
}

/**
 * Get nutrition values per 100g (already normalized in our database)
 */
export function getNutritionPer100g(food: FoodItem): Omit<FoodItem, "id" | "code" | "name" | "nameEn" | "category" | "notes" | "commonServing"> {
  return {
    servingSize: 100,
    servingUnit: "g",
    calories: food.calories,
    protein: food.protein,
    carbs: food.carbs,
    fat: food.fat,
    water: food.water,
    fiber: food.fiber,
    sodium: food.sodium,
    potassium: food.potassium,
    calcium: food.calcium,
    iron: food.iron,
    phosphorus: food.phosphorus,
    magnesium: food.magnesium,
    zinc: food.zinc,
    vitaminC: food.vitaminC,
    vitaminA: food.vitaminA,
    cholesterol: food.cholesterol,
  };
}

/**
 * Filter foods by kcal range
 */
export type KcalRange = "all" | "<50" | "50-100" | "100-200" | "200-300" | ">300";

export function filterFoodsByKcalRange(foods: FoodItem[], range: KcalRange): FoodItem[] {
  if (range === "all") return foods;

  return foods.filter((food) => {
    const kcal = food.calories;
    switch (range) {
      case "<50":
        return kcal < 50;
      case "50-100":
        return kcal >= 50 && kcal < 100;
      case "100-200":
        return kcal >= 100 && kcal < 200;
      case "200-300":
        return kcal >= 200 && kcal < 300;
      case ">300":
        return kcal >= 300;
      default:
        return true;
    }
  });
}
