/**
 * Vietnamese food database
 * 
 * Nutritional information for Vietnamese foods
 */

export interface FoodItem {
  id: string;
  code: string; // Mã số (ví dụ: "10001") - required for food-database tool
  name: string;
  nameEn?: string;
  category: FoodCategory;
  servingSize: number; // in grams (luôn 100g để chuẩn hóa)
  servingUnit: string; // "g"
  calories: number; // per 100g
  protein: number; // grams per 100g
  carbs: number; // grams per 100g
  fat: number; // grams per 100g
  sugars?: number; // grams per 100g - tổng đường, nếu có
  water?: number; // grams per 100g
  fiber?: number; // grams per 100g
  sodium?: number; // mg per 100g
  potassium?: number; // mg per 100g (K)
  calcium?: number; // mg per 100g (Ca)
  iron?: number; // mg per 100g (Fe)
  phosphorus?: number; // mg per 100g (P)
  magnesium?: number; // mg per 100g (Mg)
  zinc?: number; // mg per 100g (Zn)
  vitaminC?: number; // mg per 100g
  vitaminA?: number; // IU or mcg per 100g
  cholesterol?: number; // mg per 100g
  notes?: string;
  commonServing?: string;
}

export type FoodCategory =
  | "rice-noodles"
  | "meat"
  | "seafood"
  | "vegetables"
  | "fruits"
  | "legumes"
  | "dairy"
  | "condiments"
  | "beverages"
  | "snacks"
  | "soups"
  | "desserts";

export const foodDatabase: FoodItem[] = [
  // Rice & Noodles
  {
    id: "com-trang",
    code: "10001",
    name: "Cơm trắng",
    nameEn: "White rice",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    water: 68.4,
    fiber: 0.4,
    sodium: 1,
    potassium: 35,
    calcium: 8,
    iron: 0.8,
    phosphorus: 33,
    magnesium: 12,
    zinc: 0.4,
    commonServing: "1 bát nhỏ (100g)",
  },
  {
    id: "pho-bo",
    code: "10002",
    name: "Phở bò",
    nameEn: "Beef pho",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 117, // 350/3 normalized to 100g
    protein: 6.7, // 20/3
    carbs: 15, // 45/3
    fat: 2.7, // 8/3
    water: 75,
    fiber: 0.7, // 2/3
    sodium: 400, // 1200/3
    potassium: 80,
    calcium: 15,
    iron: 1.2,
    phosphorus: 50,
    magnesium: 18,
    zinc: 0.8,
    commonServing: "1 tô vừa (300g)",
    notes: "Bao gồm bánh phở, thịt bò, nước dùng",
  },
  {
    id: "bun-cha",
    code: "10003",
    name: "Bún chả",
    nameEn: "Grilled pork with noodles",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 168, // 420/2.5 normalized to 100g
    protein: 10, // 25/2.5
    carbs: 20, // 50/2.5
    fat: 4.8, // 12/2.5
    water: 65,
    fiber: 0.6, // 1.5/2.5
    sodium: 320, // 800/2.5
    potassium: 120,
    calcium: 20,
    iron: 1.5,
    phosphorus: 60,
    magnesium: 22,
    zinc: 1.2,
    commonServing: "1 phần (250g)",
  },

  // Meat
  {
    id: "thit-heo-nac",
    code: "20001",
    name: "Thịt heo nạc",
    nameEn: "Lean pork",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 143,
    protein: 27,
    carbs: 0,
    fat: 3.5,
    water: 69,
    sodium: 62,
    potassium: 360,
    calcium: 8,
    iron: 0.9,
    phosphorus: 220,
    magnesium: 25,
    zinc: 2.1,
    cholesterol: 62,
    commonServing: "100g (khoảng 1 lòng bàn tay)",
  },
  {
    id: "thit-ga",
    code: "20002",
    name: "Thịt gà",
    nameEn: "Chicken",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    water: 65,
    sodium: 74,
    potassium: 256,
    calcium: 15,
    iron: 0.9,
    phosphorus: 220,
    magnesium: 28,
    zinc: 1.3,
    cholesterol: 85,
    commonServing: "100g (khoảng 1 lòng bàn tay)",
  },
  {
    id: "thit-bo",
    code: "20003",
    name: "Thịt bò",
    nameEn: "Beef",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    water: 58,
    sodium: 72,
    potassium: 315,
    calcium: 18,
    iron: 2.6,
    phosphorus: 198,
    magnesium: 21,
    zinc: 4.8,
    cholesterol: 90,
    commonServing: "100g (khoảng 1 lòng bàn tay)",
  },

  // Seafood
  {
    id: "ca-basa",
    code: "30001",
    name: "Cá basa",
    nameEn: "Basa fish",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 162,
    protein: 18,
    carbs: 0,
    fat: 9,
    water: 72,
    sodium: 45,
    potassium: 280,
    calcium: 15,
    iron: 0.5,
    phosphorus: 200,
    magnesium: 25,
    zinc: 0.8,
    cholesterol: 55,
    commonServing: "100g (1 miếng vừa)",
  },
  {
    id: "tom",
    code: "30002",
    name: "Tôm",
    nameEn: "Shrimp",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
    water: 75,
    sodium: 111,
    potassium: 259,
    calcium: 52,
    iron: 0.3,
    phosphorus: 237,
    magnesium: 37,
    zinc: 1.1,
    cholesterol: 152,
    commonServing: "100g (khoảng 8-10 con vừa)",
  },

  // Vegetables
  {
    id: "rau-muong",
    code: "40001",
    name: "Rau muống",
    nameEn: "Water spinach",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 19,
    protein: 2.6,
    carbs: 3.1,
    fat: 0.2,
    water: 92,
    fiber: 2.1,
    sodium: 79,
    potassium: 312,
    calcium: 77,
    iron: 1.7,
    phosphorus: 39,
    magnesium: 71,
    zinc: 0.4,
    vitaminC: 55,
    vitaminA: 3158,
    commonServing: "100g (1 bó nhỏ)",
  },
  {
    id: "cai-xanh",
    code: "40002",
    name: "Cải xanh",
    nameEn: "Chinese cabbage",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 16,
    protein: 1.5,
    carbs: 3.2,
    fat: 0.2,
    water: 95,
    fiber: 1.2,
    sodium: 65,
    potassium: 252,
    calcium: 105,
    iron: 0.8,
    phosphorus: 37,
    magnesium: 19,
    zinc: 0.2,
    vitaminC: 36,
    vitaminA: 4468,
    commonServing: "100g",
  },
  {
    id: "ca-chua",
    code: "40003",
    name: "Cà chua",
    nameEn: "Tomato",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    water: 94,
    fiber: 1.2,
    sodium: 5,
    potassium: 237,
    calcium: 10,
    iron: 0.3,
    phosphorus: 24,
    magnesium: 11,
    zinc: 0.2,
    vitaminC: 14,
    vitaminA: 833,
    commonServing: "100g (1-2 quả vừa)",
  },

  // Fruits
  {
    id: "chuoi",
    code: "50001",
    name: "Chuối",
    nameEn: "Banana",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    water: 75,
    fiber: 2.6,
    sodium: 1,
    potassium: 358,
    calcium: 5,
    iron: 0.3,
    phosphorus: 22,
    magnesium: 27,
    zinc: 0.2,
    vitaminC: 8.7,
    commonServing: "100g (1 quả vừa)",
  },
  {
    id: "cam",
    code: "50002",
    name: "Cam",
    nameEn: "Orange",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    water: 87,
    fiber: 2.4,
    sodium: 0,
    potassium: 181,
    calcium: 40,
    iron: 0.1,
    phosphorus: 14,
    magnesium: 10,
    zinc: 0.1,
    vitaminC: 53.2,
    vitaminA: 225,
    commonServing: "100g (1 quả vừa)",
  },

  // Legumes
  {
    id: "dau-phu",
    code: "60001",
    name: "Đậu phụ",
    nameEn: "Tofu",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 76,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
    water: 85,
    fiber: 0.3,
    sodium: 7,
    potassium: 121,
    calcium: 350,
    iron: 5.4,
    phosphorus: 97,
    magnesium: 30,
    zinc: 0.8,
    commonServing: "100g (1 miếng vừa)",
  },
  {
    id: "dau-xanh",
    code: "60002",
    name: "Đậu xanh",
    nameEn: "Mung beans",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 347,
    protein: 24,
    carbs: 63,
    fat: 1.2,
    water: 10,
    fiber: 16.3,
    sodium: 15,
    potassium: 1246,
    calcium: 132,
    iron: 6.7,
    phosphorus: 367,
    magnesium: 189,
    zinc: 2.8,
    commonServing: "100g (nấu chín)",
  },

  // Condiments
  {
    id: "nuoc-mam",
    code: "70001",
    name: "Nước mắm",
    nameEn: "Fish sauce",
    category: "condiments",
    servingSize: 100,
    servingUnit: "g",
    calories: 53, // 8/15*100 normalized to 100g
    protein: 8.7, // 1.3/15*100
    carbs: 5.3, // 0.8/15*100
    fat: 0,
    water: 85,
    sodium: 10000, // 1500/15*100
    potassium: 200,
    calcium: 20,
    iron: 0.5,
    phosphorus: 50,
    magnesium: 15,
    zinc: 0.3,
    commonServing: "1 muỗng canh (15ml)",
    notes: "Rất nhiều natri - dùng ít cho người tăng huyết áp",
  },
  {
    id: "tuong-ot",
    code: "70002",
    name: "Tương ớt",
    nameEn: "Chili sauce",
    category: "condiments",
    servingSize: 100,
    servingUnit: "g",
    calories: 100, // 15/15*100 normalized to 100g
    protein: 2, // 0.3/15*100
    carbs: 23.3, // 3.5/15*100
    fat: 0.7, // 0.1/15*100
    water: 73,
    sodium: 1333, // 200/15*100
    potassium: 150,
    calcium: 10,
    iron: 0.3,
    phosphorus: 30,
    magnesium: 12,
    zinc: 0.2,
    vitaminC: 33, // 5/15*100
    commonServing: "1 muỗng canh (15g)",
  },

  // Dairy
  {
    id: "sua-bo-tuoi",
    code: "80001",
    name: "Sữa bò tươi",
    nameEn: "Fresh cow milk",
    category: "dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 61,
    protein: 3.2,
    carbs: 4.7,
    fat: 3.3,
    water: 88,
    sodium: 44,
    potassium: 150,
    calcium: 120,
    iron: 0.1,
    phosphorus: 95,
    magnesium: 12,
    zinc: 0.4,
    vitaminA: 46,
    vitaminC: 1,
    cholesterol: 10,
    commonServing: "100ml (1 ly nhỏ)",
  },
  {
    id: "sua-chua",
    code: "80002",
    name: "Sữa chua",
    nameEn: "Yogurt",
    category: "dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 61,
    protein: 3.3,
    carbs: 4.7,
    fat: 3.3,
    water: 88,
    sodium: 36,
    potassium: 155,
    calcium: 110,
    iron: 0.1,
    phosphorus: 85,
    magnesium: 12,
    zinc: 0.6,
    vitaminA: 27,
    vitaminC: 0.5,
    cholesterol: 13,
    commonServing: "100g (1 hũ nhỏ)",
  },
  {
    id: "sua-dau-nanh",
    code: "80003",
    name: "Sữa đậu nành",
    nameEn: "Soy milk",
    category: "dairy",
    servingSize: 100,
    servingUnit: "ml",
    calories: 33,
    protein: 2.9,
    carbs: 1.8,
    fat: 1.6,
    water: 93,
    sodium: 4,
    potassium: 118,
    calcium: 25,
    iron: 0.6,
    phosphorus: 52,
    magnesium: 25,
    zinc: 0.2,
    vitaminA: 0,
    commonServing: "100ml (1 ly nhỏ)",
  },
  {
    id: "pho-mai",
    code: "80004",
    name: "Phô mai",
    nameEn: "Cheese",
    category: "dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 300,
    protein: 25,
    carbs: 1.3,
    fat: 22,
    water: 50,
    sodium: 621,
    potassium: 95,
    calcium: 721,
    iron: 0.7,
    phosphorus: 512,
    magnesium: 28,
    zinc: 2.5,
    vitaminA: 1002,
    cholesterol: 100,
    commonServing: "100g (1 miếng vừa)",
  },
  {
    id: "trung-ga",
    code: "80005",
    name: "Trứng gà",
    nameEn: "Chicken egg",
    category: "dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    water: 75,
    sodium: 124,
    potassium: 138,
    calcium: 56,
    iron: 1.8,
    phosphorus: 198,
    magnesium: 12,
    zinc: 1.3,
    vitaminA: 160,
    vitaminC: 0,
    cholesterol: 372,
    commonServing: "100g (khoảng 2 quả)",
  },

  // More Rice & Noodles
  {
    id: "bun-ga",
    code: "10004",
    name: "Bún gà",
    nameEn: "Chicken noodle soup",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 95,
    protein: 5.5,
    carbs: 12,
    fat: 2.5,
    water: 79,
    fiber: 0.5,
    sodium: 350,
    potassium: 85,
    calcium: 12,
    iron: 0.8,
    phosphorus: 45,
    magnesium: 15,
    zinc: 0.6,
    cholesterol: 25,
    commonServing: "1 tô vừa (300g)",
  },
  {
    id: "banh-mi",
    code: "10005",
    name: "Bánh mì",
    nameEn: "Vietnamese bread",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 265,
    protein: 8.2,
    carbs: 51,
    fat: 3.2,
    water: 36,
    fiber: 2.7,
    sodium: 491,
    potassium: 115,
    calcium: 20,
    iron: 3.6,
    phosphorus: 98,
    magnesium: 25,
    zinc: 0.7,
    commonServing: "100g (1 ổ vừa)",
  },
  {
    id: "mien",
    code: "10006",
    name: "Miến",
    nameEn: "Glass noodles",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 351,
    protein: 0.2,
    carbs: 86,
    fat: 0.1,
    water: 13,
    fiber: 0.2,
    sodium: 4,
    potassium: 5,
    calcium: 4,
    iron: 0.1,
    phosphorus: 2,
    magnesium: 1,
    zinc: 0.1,
    commonServing: "100g (khô)",
  },

  // More Meat
  {
    id: "thit-vit",
    code: "20004",
    name: "Thịt vịt",
    nameEn: "Duck meat",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 337,
    protein: 19,
    carbs: 0,
    fat: 28,
    water: 52,
    sodium: 83,
    potassium: 271,
    calcium: 12,
    iron: 2.7,
    phosphorus: 188,
    magnesium: 19,
    zinc: 2.6,
    cholesterol: 76,
    commonServing: "100g (khoảng 1 lòng bàn tay)",
  },
  {
    id: "thit-heo-ba-chi",
    code: "20005",
    name: "Thịt heo ba chỉ",
    nameEn: "Pork belly",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 518,
    protein: 9.3,
    carbs: 0,
    fat: 53,
    water: 37,
    sodium: 54,
    potassium: 185,
    calcium: 5,
    iron: 0.8,
    phosphorus: 83,
    magnesium: 8,
    zinc: 1.1,
    cholesterol: 72,
    commonServing: "100g",
  },
  {
    id: "gan-heo",
    code: "20006",
    name: "Gan heo",
    nameEn: "Pork liver",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 134,
    protein: 21,
    carbs: 3.8,
    fat: 3.4,
    water: 71,
    sodium: 87,
    potassium: 300,
    calcium: 8,
    iron: 23,
    phosphorus: 363,
    magnesium: 21,
    zinc: 6.7,
    vitaminA: 6502,
    vitaminC: 23,
    cholesterol: 301,
    commonServing: "100g",
  },

  // More Seafood
  {
    id: "ca-rot",
    code: "30003",
    name: "Cá rô",
    nameEn: "Climbing perch",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 103,
    protein: 20,
    carbs: 0,
    fat: 2.1,
    water: 77,
    sodium: 65,
    potassium: 317,
    calcium: 26,
    iron: 0.5,
    phosphorus: 200,
    magnesium: 25,
    zinc: 0.8,
    cholesterol: 66,
    commonServing: "100g (1 con vừa)",
  },
  {
    id: "ca-chep",
    code: "30004",
    name: "Cá chép",
    nameEn: "Carp",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 127,
    protein: 18,
    carbs: 0,
    fat: 5.6,
    water: 76,
    sodium: 49,
    potassium: 333,
    calcium: 50,
    iron: 0.8,
    phosphorus: 200,
    magnesium: 29,
    zinc: 1.5,
    cholesterol: 84,
    commonServing: "100g",
  },
  {
    id: "cua",
    code: "30005",
    name: "Cua",
    nameEn: "Crab",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 97,
    protein: 19,
    carbs: 0.1,
    fat: 1.5,
    water: 79,
    sodium: 395,
    potassium: 259,
    calcium: 91,
    iron: 0.8,
    phosphorus: 234,
    magnesium: 34,
    zinc: 3.8,
    vitaminA: 1,
    cholesterol: 78,
    commonServing: "100g (thịt cua)",
  },

  // More Vegetables
  {
    id: "ca-rot-rau",
    code: "40004",
    name: "Cà rốt",
    nameEn: "Carrot",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    water: 88,
    fiber: 2.8,
    sodium: 69,
    potassium: 320,
    calcium: 33,
    iron: 0.3,
    phosphorus: 35,
    magnesium: 12,
    zinc: 0.2,
    vitaminC: 5.9,
    vitaminA: 835,
    commonServing: "100g (1 củ vừa)",
  },
  {
    id: "bap-cai",
    code: "40005",
    name: "Bắp cải",
    nameEn: "Cabbage",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 25,
    protein: 1.3,
    carbs: 6,
    fat: 0.1,
    water: 92,
    fiber: 2.5,
    sodium: 18,
    potassium: 170,
    calcium: 40,
    iron: 0.5,
    phosphorus: 26,
    magnesium: 12,
    zinc: 0.2,
    vitaminC: 36.6,
    vitaminA: 98,
    commonServing: "100g",
  },
  {
    id: "khoai-tay",
    code: "40006",
    name: "Khoai tây",
    nameEn: "Potato",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    water: 80,
    fiber: 2.2,
    sodium: 6,
    potassium: 421,
    calcium: 12,
    iron: 0.8,
    phosphorus: 57,
    magnesium: 23,
    zinc: 0.3,
    vitaminC: 19.7,
    commonServing: "100g (1 củ vừa)",
  },
  {
    id: "bi-do",
    code: "40007",
    name: "Bí đỏ",
    nameEn: "Pumpkin",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 26,
    protein: 1,
    carbs: 7,
    fat: 0.1,
    water: 91,
    fiber: 0.5,
    sodium: 1,
    potassium: 340,
    calcium: 21,
    iron: 0.8,
    phosphorus: 44,
    magnesium: 12,
    zinc: 0.3,
    vitaminC: 9,
    vitaminA: 851,
    commonServing: "100g",
  },
  {
    id: "rau-cai",
    code: "40008",
    name: "Rau cải",
    nameEn: "Mustard greens",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 27,
    protein: 2.7,
    carbs: 4.7,
    fat: 0.4,
    water: 91,
    fiber: 1.8,
    sodium: 20,
    potassium: 354,
    calcium: 103,
    iron: 1.5,
    phosphorus: 29,
    magnesium: 32,
    zinc: 0.2,
    vitaminC: 70,
    vitaminA: 3024,
    commonServing: "100g (1 bó nhỏ)",
  },
  {
    id: "dau-bap",
    code: "40009",
    name: "Đậu bắp",
    nameEn: "Okra",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 33,
    protein: 2,
    carbs: 7.5,
    fat: 0.2,
    water: 90,
    fiber: 3.2,
    sodium: 7,
    potassium: 299,
    calcium: 82,
    iron: 0.6,
    phosphorus: 61,
    magnesium: 57,
    zinc: 0.6,
    vitaminC: 23,
    vitaminA: 36,
    commonServing: "100g (10-12 quả)",
  },

  // More Fruits
  {
    id: "tao",
    code: "50003",
    name: "Táo",
    nameEn: "Apple",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    water: 86,
    fiber: 2.4,
    sodium: 1,
    potassium: 107,
    calcium: 6,
    iron: 0.1,
    phosphorus: 11,
    magnesium: 5,
    zinc: 0.04,
    vitaminC: 4.6,
    vitaminA: 3,
    commonServing: "100g (1 quả vừa)",
  },
  {
    id: "dua-hau",
    code: "50004",
    name: "Dưa hấu",
    nameEn: "Watermelon",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 30,
    protein: 0.6,
    carbs: 8,
    fat: 0.2,
    water: 91,
    fiber: 0.4,
    sodium: 1,
    potassium: 112,
    calcium: 7,
    iron: 0.2,
    phosphorus: 11,
    magnesium: 10,
    zinc: 0.1,
    vitaminC: 8.1,
    vitaminA: 28,
    commonServing: "100g (1 miếng nhỏ)",
  },
  {
    id: "xoai",
    code: "50005",
    name: "Xoài",
    nameEn: "Mango",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    water: 83,
    fiber: 1.6,
    sodium: 1,
    potassium: 168,
    calcium: 11,
    iron: 0.2,
    phosphorus: 14,
    magnesium: 10,
    zinc: 0.1,
    vitaminC: 36.4,
    vitaminA: 54,
    commonServing: "100g (1/2 quả vừa)",
  },
  {
    id: "du-du",
    code: "50006",
    name: "Đu đủ",
    nameEn: "Papaya",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 43,
    protein: 0.5,
    carbs: 11,
    fat: 0.3,
    water: 88,
    fiber: 1.7,
    sodium: 8,
    potassium: 182,
    calcium: 20,
    iron: 0.3,
    phosphorus: 10,
    magnesium: 21,
    zinc: 0.1,
    vitaminC: 60.9,
    vitaminA: 55,
    commonServing: "100g (1 miếng vừa)",
  },
  {
    id: "oi",
    code: "50007",
    name: "Ổi",
    nameEn: "Guava",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 68,
    protein: 2.6,
    carbs: 14,
    fat: 1,
    water: 81,
    fiber: 5.4,
    sodium: 2,
    potassium: 417,
    calcium: 18,
    iron: 0.3,
    phosphorus: 40,
    magnesium: 22,
    zinc: 0.2,
    vitaminC: 228.3,
    vitaminA: 31,
    commonServing: "100g (1 quả vừa)",
  },
  {
    id: "nho",
    code: "50008",
    name: "Nho",
    nameEn: "Grapes",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 69,
    protein: 0.7,
    carbs: 18,
    fat: 0.2,
    water: 81,
    fiber: 0.9,
    sodium: 3,
    potassium: 191,
    calcium: 10,
    iron: 0.4,
    phosphorus: 20,
    magnesium: 7,
    zinc: 0.1,
    vitaminC: 10.8,
    vitaminA: 3,
    commonServing: "100g (khoảng 10-15 quả)",
  },

  // More Legumes
  {
    id: "dau-nanh",
    code: "60003",
    name: "Đậu nành",
    nameEn: "Soybeans",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 446,
    protein: 36,
    carbs: 30,
    fat: 20,
    water: 8,
    fiber: 9.3,
    sodium: 2,
    potassium: 1797,
    calcium: 277,
    iron: 15.7,
    phosphorus: 704,
    magnesium: 280,
    zinc: 4.9,
    vitaminC: 6,
    commonServing: "100g (khô)",
  },
  {
    id: "dau-do",
    code: "60004",
    name: "Đậu đỏ",
    nameEn: "Red beans",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 337,
    protein: 22,
    carbs: 63,
    fat: 0.5,
    water: 12,
    fiber: 12.7,
    sodium: 2,
    potassium: 1259,
    calcium: 83,
    iron: 6.7,
    phosphorus: 381,
    magnesium: 138,
    zinc: 2.8,
    vitaminC: 1,
    commonServing: "100g (nấu chín)",
  },
  {
    id: "lac",
    code: "60005",
    name: "Lạc (Đậu phộng)",
    nameEn: "Peanuts",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 567,
    protein: 26,
    carbs: 16,
    fat: 49,
    water: 7,
    fiber: 8.5,
    sodium: 18,
    potassium: 705,
    calcium: 92,
    iron: 4.6,
    phosphorus: 376,
    magnesium: 168,
    zinc: 3.3,
    vitaminC: 0,
    commonServing: "100g (khoảng 1 bát nhỏ)",
  },

  // Beverages
  {
    id: "nuoc-dua",
    code: "90001",
    name: "Nước dừa",
    nameEn: "Coconut water",
    category: "beverages",
    servingSize: 100,
    servingUnit: "ml",
    calories: 19,
    protein: 0.7,
    carbs: 3.7,
    fat: 0.2,
    water: 95,
    sodium: 105,
    potassium: 250,
    calcium: 24,
    iron: 0.3,
    phosphorus: 20,
    magnesium: 25,
    zinc: 0.1,
    vitaminC: 2.4,
    commonServing: "100ml (1 ly nhỏ)",
  },
  {
    id: "nuoc-cam",
    code: "90002",
    name: "Nước cam",
    nameEn: "Orange juice",
    category: "beverages",
    servingSize: 100,
    servingUnit: "ml",
    calories: 45,
    protein: 0.7,
    carbs: 10,
    fat: 0.2,
    water: 89,
    sodium: 1,
    potassium: 200,
    calcium: 11,
    iron: 0.2,
    phosphorus: 17,
    magnesium: 11,
    zinc: 0.1,
    vitaminC: 50,
    vitaminA: 10,
    commonServing: "100ml (1 ly nhỏ)",
  },
  {
    id: "tra-xanh",
    code: "90003",
    name: "Trà xanh",
    nameEn: "Green tea",
    category: "beverages",
    servingSize: 100,
    servingUnit: "ml",
    calories: 2,
    protein: 0.2,
    carbs: 0,
    fat: 0,
    water: 99,
    sodium: 3,
    potassium: 8,
    calcium: 3,
    iron: 0.02,
    phosphorus: 1,
    magnesium: 1,
    zinc: 0.01,
    vitaminC: 0,
    commonServing: "100ml (1 ly)",
  },

  // Snacks
  {
    id: "khoai-lang",
    code: "10007",
    name: "Khoai lang",
    nameEn: "Sweet potato",
    category: "snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    water: 77,
    fiber: 3,
    sodium: 54,
    potassium: 337,
    calcium: 30,
    iron: 0.6,
    phosphorus: 47,
    magnesium: 25,
    zinc: 0.3,
    vitaminC: 2.4,
    vitaminA: 709,
    commonServing: "100g (1 củ vừa)",
  },
  {
    id: "ngu-coc",
    code: "10008",
    name: "Ngô (Bắp)",
    nameEn: "Corn",
    category: "snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 96,
    protein: 3.4,
    carbs: 21,
    fat: 1.2,
    water: 74,
    fiber: 2.4,
    sodium: 1,
    potassium: 270,
    calcium: 2,
    iron: 0.5,
    phosphorus: 89,
    magnesium: 37,
    zinc: 0.5,
    vitaminC: 6.8,
    vitaminA: 9,
    commonServing: "100g (1 bắp nhỏ)",
  },

  // More Rice & Noodles
  {
    id: "com-ga",
    code: "10009",
    name: "Cơm gà",
    nameEn: "Chicken rice",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 145,
    protein: 4.5,
    carbs: 28,
    fat: 2.2,
    water: 64,
    fiber: 0.4,
    sodium: 280,
    potassium: 90,
    calcium: 10,
    iron: 0.6,
    phosphorus: 40,
    magnesium: 15,
    zinc: 0.5,
    cholesterol: 15,
    commonServing: "1 phần (200g)",
  },
  {
    id: "banh-cuon",
    code: "10010",
    name: "Bánh cuốn",
    nameEn: "Steamed rice rolls",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 120,
    protein: 3.5,
    carbs: 24,
    fat: 1.2,
    water: 70,
    fiber: 0.5,
    sodium: 200,
    potassium: 60,
    calcium: 8,
    iron: 0.4,
    phosphorus: 30,
    magnesium: 10,
    zinc: 0.3,
    commonServing: "1 phần (150g)",
  },

  // More Meat
  {
    id: "thit-bo-kho",
    code: "20007",
    name: "Thịt bò kho",
    nameEn: "Braised beef",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 195,
    protein: 20,
    carbs: 3,
    fat: 10,
    water: 66,
    sodium: 450,
    potassium: 280,
    calcium: 15,
    iron: 2.2,
    phosphorus: 180,
    magnesium: 18,
    zinc: 4.2,
    cholesterol: 75,
    commonServing: "100g",
  },
  {
    id: "thit-ga-nuong",
    code: "20008",
    name: "Thịt gà nướng",
    nameEn: "Grilled chicken",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    water: 65,
    sodium: 74,
    potassium: 256,
    calcium: 15,
    iron: 0.9,
    phosphorus: 220,
    magnesium: 28,
    zinc: 1.3,
    cholesterol: 85,
    commonServing: "100g",
  },

  // More Seafood
  {
    id: "ca-ngu",
    code: "30006",
    name: "Cá ngừ",
    nameEn: "Tuna",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 144,
    protein: 30,
    carbs: 0,
    fat: 1,
    water: 68,
    sodium: 37,
    potassium: 252,
    calcium: 8,
    iron: 1,
    phosphorus: 220,
    magnesium: 30,
    zinc: 0.9,
    cholesterol: 38,
    commonServing: "100g",
  },
  {
    id: "muc",
    code: "30007",
    name: "Mực",
    nameEn: "Squid",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 92,
    protein: 16,
    carbs: 3.1,
    fat: 1.4,
    water: 78,
    sodium: 44,
    potassium: 246,
    calcium: 32,
    iron: 0.7,
    phosphorus: 221,
    magnesium: 33,
    zinc: 1.5,
    cholesterol: 233,
    commonServing: "100g",
  },
  {
    id: "ca-hui",
    code: "30008",
    name: "Cá hồi",
    nameEn: "Salmon",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    water: 66,
    sodium: 44,
    potassium: 363,
    calcium: 12,
    iron: 0.8,
    phosphorus: 200,
    magnesium: 27,
    zinc: 0.6,
    cholesterol: 55,
    commonServing: "100g",
  },

  // More Vegetables
  {
    id: "rau-lang",
    code: "40010",
    name: "Rau lang",
    nameEn: "Sweet potato leaves",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 30,
    protein: 2.6,
    carbs: 4.2,
    fat: 0.3,
    water: 92,
    fiber: 1.3,
    sodium: 6,
    potassium: 312,
    calcium: 78,
    iron: 0.8,
    phosphorus: 28,
    magnesium: 61,
    zinc: 0.2,
    vitaminC: 11,
    vitaminA: 1897,
    commonServing: "100g (1 bó nhỏ)",
  },
  {
    id: "rau-diep",
    code: "40011",
    name: "Rau diếp",
    nameEn: "Lettuce",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    water: 95,
    fiber: 1.3,
    sodium: 5,
    potassium: 194,
    calcium: 36,
    iron: 0.9,
    phosphorus: 29,
    magnesium: 13,
    zinc: 0.2,
    vitaminC: 9.2,
    vitaminA: 7405,
    commonServing: "100g",
  },
  {
    id: "dau-bao",
    code: "40012",
    name: "Đậu bắp",
    nameEn: "Green beans",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.2,
    water: 90,
    fiber: 2.7,
    sodium: 6,
    potassium: 211,
    calcium: 37,
    iron: 1,
    phosphorus: 38,
    magnesium: 25,
    zinc: 0.2,
    vitaminC: 12.2,
    vitaminA: 35,
    commonServing: "100g",
  },
  {
    id: "su-su",
    code: "40013",
    name: "Su su",
    nameEn: "Chayote",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 19,
    protein: 0.8,
    carbs: 4.5,
    fat: 0.1,
    water: 94,
    fiber: 1.7,
    sodium: 2,
    potassium: 125,
    calcium: 17,
    iron: 0.3,
    phosphorus: 18,
    magnesium: 12,
    zinc: 0.1,
    vitaminC: 7.7,
    vitaminA: 3,
    commonServing: "100g (1 quả nhỏ)",
  },

  // More Fruits
  {
    id: "thanh-long",
    code: "50009",
    name: "Thanh long",
    nameEn: "Dragon fruit",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 60,
    protein: 1.2,
    carbs: 13,
    fat: 0.4,
    water: 85,
    fiber: 1.8,
    sodium: 0,
    potassium: 264,
    calcium: 8,
    iron: 0.3,
    phosphorus: 22,
    magnesium: 18,
    zinc: 0.1,
    vitaminC: 3,
    vitaminA: 0,
    commonServing: "100g (1/2 quả vừa)",
  },
  {
    id: "buoi",
    code: "50010",
    name: "Bưởi",
    nameEn: "Pomelo",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 38,
    protein: 0.8,
    carbs: 10,
    fat: 0,
    water: 89,
    fiber: 1,
    sodium: 1,
    potassium: 216,
    calcium: 4,
    iron: 0.1,
    phosphorus: 17,
    magnesium: 6,
    zinc: 0.1,
    vitaminC: 61,
    vitaminA: 8,
    commonServing: "100g (2-3 múi)",
  },
  {
    id: "mit",
    code: "50011",
    name: "Mít",
    nameEn: "Jackfruit",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 95,
    protein: 1.7,
    carbs: 24,
    fat: 0.3,
    water: 73,
    fiber: 1.5,
    sodium: 2,
    potassium: 448,
    calcium: 24,
    iron: 0.2,
    phosphorus: 21,
    magnesium: 29,
    zinc: 0.1,
    vitaminC: 13.7,
    vitaminA: 5,
    commonServing: "100g (3-4 múi)",
  },
  {
    id: "sau-rieng",
    code: "50012",
    name: "Sầu riêng",
    nameEn: "Durian",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 147,
    protein: 1.5,
    carbs: 27,
    fat: 5.3,
    water: 65,
    fiber: 3.8,
    sodium: 2,
    potassium: 436,
    calcium: 6,
    iron: 0.4,
    phosphorus: 39,
    magnesium: 30,
    zinc: 0.3,
    vitaminC: 19.7,
    vitaminA: 2,
    commonServing: "100g (1 múi)",
  },

  // More Legumes
  {
    id: "dau-den",
    code: "60006",
    name: "Đậu đen",
    nameEn: "Black beans",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 341,
    protein: 21,
    carbs: 62,
    fat: 1.4,
    water: 11,
    fiber: 15.5,
    sodium: 5,
    potassium: 1483,
    calcium: 123,
    iron: 5,
    phosphorus: 352,
    magnesium: 171,
    zinc: 3.6,
    vitaminC: 0,
    commonServing: "100g (nấu chín)",
  },
  {
    id: "dau-trang",
    code: "60007",
    name: "Đậu trắng",
    nameEn: "White beans",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 333,
    protein: 23,
    carbs: 60,
    fat: 0.9,
    water: 12,
    fiber: 15.2,
    sodium: 16,
    potassium: 1795,
    calcium: 240,
    iron: 10.4,
    phosphorus: 301,
    magnesium: 190,
    zinc: 3.7,
    vitaminC: 0,
    commonServing: "100g (nấu chín)",
  },

  // More Dairy
  {
    id: "sua-tuoi-tiet-trung",
    code: "80006",
    name: "Sữa tươi tiệt trùng",
    nameEn: "Pasteurized milk",
    category: "dairy",
    servingSize: 100,
    servingUnit: "ml",
    calories: 61,
    protein: 3.2,
    carbs: 4.7,
    fat: 3.3,
    water: 88,
    sodium: 44,
    potassium: 150,
    calcium: 120,
    iron: 0.1,
    phosphorus: 95,
    magnesium: 12,
    zinc: 0.4,
    vitaminA: 46,
    vitaminC: 1,
    cholesterol: 10,
    commonServing: "100ml (1 ly nhỏ)",
  },
  {
    id: "sua-dac",
    code: "80007",
    name: "Sữa đặc",
    nameEn: "Condensed milk",
    category: "dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 321,
    protein: 7.9,
    carbs: 54,
    fat: 9,
    water: 27,
    sodium: 127,
    potassium: 371,
    calcium: 284,
    iron: 0.2,
    phosphorus: 253,
    magnesium: 26,
    zinc: 1,
    vitaminA: 74,
    vitaminC: 2.6,
    cholesterol: 34,
    commonServing: "100g (khoảng 3 muỗng canh)",
  },

  // More Beverages
  {
    id: "nuoc-chanh",
    code: "90004",
    name: "Nước chanh",
    nameEn: "Lemon juice",
    category: "beverages",
    servingSize: 100,
    servingUnit: "ml",
    calories: 22,
    protein: 0.4,
    carbs: 7,
    fat: 0.2,
    water: 92,
    sodium: 1,
    potassium: 103,
    calcium: 6,
    iron: 0.1,
    phosphorus: 8,
    magnesium: 6,
    zinc: 0.05,
    vitaminC: 29.1,
    commonServing: "100ml (1 ly nhỏ)",
  },
  {
    id: "ca-phe-den",
    code: "90005",
    name: "Cà phê đen",
    nameEn: "Black coffee",
    category: "beverages",
    servingSize: 100,
    servingUnit: "ml",
    calories: 2,
    protein: 0.1,
    carbs: 0,
    fat: 0,
    water: 99,
    sodium: 5,
    potassium: 49,
    calcium: 2,
    iron: 0.1,
    phosphorus: 3,
    magnesium: 3,
    zinc: 0.02,
    vitaminC: 0,
    commonServing: "100ml (1 ly)",
  },
  {
    id: "tra-dao",
    code: "90006",
    name: "Trà đào",
    nameEn: "Peach tea",
    category: "beverages",
    servingSize: 100,
    servingUnit: "ml",
    calories: 30,
    protein: 0.1,
    carbs: 7.5,
    fat: 0,
    water: 92,
    sodium: 3,
    potassium: 20,
    calcium: 1,
    iron: 0.1,
    phosphorus: 1,
    magnesium: 1,
    zinc: 0.01,
    vitaminC: 2,
    commonServing: "100ml (1 ly)",
  },

  // More Snacks
  {
    id: "khoai-tay-chien",
    code: "10011",
    name: "Khoai tây chiên",
    nameEn: "French fries",
    category: "snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 312,
    protein: 3.4,
    carbs: 41,
    fat: 15,
    water: 38,
    fiber: 3.8,
    sodium: 210,
    potassium: 579,
    calcium: 18,
    iron: 0.8,
    phosphorus: 62,
    magnesium: 30,
    zinc: 0.3,
    vitaminC: 13,
    commonServing: "100g (1 phần nhỏ)",
  },
  {
    id: "banh-quy",
    code: "10012",
    name: "Bánh quy",
    nameEn: "Biscuits",
    category: "snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 433,
    protein: 7,
    carbs: 72,
    fat: 12,
    water: 4,
    fiber: 2.3,
    sodium: 580,
    potassium: 100,
    calcium: 20,
    iron: 3.5,
    phosphorus: 100,
    magnesium: 20,
    zinc: 0.8,
    commonServing: "100g (khoảng 10-12 cái)",
  },

  // Soups
  {
    id: "canh-chua",
    code: "11001",
    name: "Canh chua",
    nameEn: "Sour soup",
    category: "soups",
    servingSize: 100,
    servingUnit: "g",
    calories: 35,
    protein: 2.5,
    carbs: 4,
    fat: 0.8,
    water: 92,
    fiber: 0.5,
    sodium: 280,
    potassium: 120,
    calcium: 15,
    iron: 0.5,
    phosphorus: 25,
    magnesium: 12,
    zinc: 0.3,
    vitaminC: 8,
    commonServing: "100g (1 bát nhỏ)",
  },
  {
    id: "pho-ga",
    code: "11002",
    name: "Phở gà",
    nameEn: "Chicken pho",
    category: "soups",
    servingSize: 100,
    servingUnit: "g",
    calories: 95,
    protein: 5.5,
    carbs: 12,
    fat: 2.5,
    water: 79,
    fiber: 0.5,
    sodium: 350,
    potassium: 85,
    calcium: 12,
    iron: 0.8,
    phosphorus: 45,
    magnesium: 15,
    zinc: 0.6,
    cholesterol: 25,
    commonServing: "1 tô vừa (300g)",
  },

  // More Soups
  {
    id: "bun-rieu",
    code: "11003",
    name: "Bún riêu",
    nameEn: "Crab noodle soup",
    category: "soups",
    servingSize: 100,
    servingUnit: "g",
    calories: 85,
    protein: 4.5,
    carbs: 12,
    fat: 2,
    water: 80,
    fiber: 0.5,
    sodium: 320,
    potassium: 95,
    calcium: 45,
    iron: 0.6,
    phosphorus: 50,
    magnesium: 18,
    zinc: 0.5,
    cholesterol: 20,
    commonServing: "1 tô vừa (300g)",
  },
  {
    id: "canh-kho-qua",
    code: "11004",
    name: "Canh khổ qua",
    nameEn: "Bitter melon soup",
    category: "soups",
    servingSize: 100,
    servingUnit: "g",
    calories: 28,
    protein: 1.5,
    carbs: 4.5,
    fat: 0.8,
    water: 92,
    fiber: 1.2,
    sodium: 250,
    potassium: 180,
    calcium: 12,
    iron: 0.4,
    phosphorus: 22,
    magnesium: 15,
    zinc: 0.2,
    vitaminC: 84,
    commonServing: "100g (1 bát nhỏ)",
  },

  // More Rice & Noodles
  {
    id: "com-tam",
    code: "10013",
    name: "Cơm tấm",
    nameEn: "Broken rice",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    water: 68,
    fiber: 0.4,
    sodium: 1,
    potassium: 35,
    calcium: 8,
    iron: 0.8,
    phosphorus: 33,
    magnesium: 12,
    zinc: 0.4,
    commonServing: "100g (1 đĩa nhỏ)",
  },
  {
    id: "hu-tieu",
    code: "10014",
    name: "Hủ tiếu",
    nameEn: "Hu tieu noodles",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 110,
    protein: 4,
    carbs: 20,
    fat: 1.5,
    water: 73,
    fiber: 0.6,
    sodium: 380,
    potassium: 70,
    calcium: 10,
    iron: 0.7,
    phosphorus: 35,
    magnesium: 12,
    zinc: 0.4,
    commonServing: "1 tô vừa (300g)",
  },
  {
    id: "mi-quang",
    code: "10015",
    name: "Mì Quảng",
    nameEn: "Quang noodles",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 125,
    protein: 5.5,
    carbs: 18,
    fat: 3.2,
    water: 72,
    fiber: 0.8,
    sodium: 420,
    potassium: 95,
    calcium: 15,
    iron: 1,
    phosphorus: 50,
    magnesium: 18,
    zinc: 0.6,
    cholesterol: 18,
    commonServing: "1 tô vừa (300g)",
  },

  // More Meat
  {
    id: "thit-heo-kho",
    code: "20009",
    name: "Thịt heo kho",
    nameEn: "Braised pork",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 185,
    protein: 22,
    carbs: 2.5,
    fat: 9,
    water: 66,
    sodium: 480,
    potassium: 320,
    calcium: 10,
    iron: 1.2,
    phosphorus: 200,
    magnesium: 22,
    zinc: 2.3,
    cholesterol: 68,
    commonServing: "100g",
  },
  {
    id: "thit-bo-luc-lac",
    code: "20010",
    name: "Thịt bò lúc lắc",
    nameEn: "Shaking beef",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 220,
    protein: 24,
    carbs: 3,
    fat: 11,
    water: 61,
    sodium: 420,
    potassium: 300,
    calcium: 16,
    iron: 2.4,
    phosphorus: 195,
    magnesium: 20,
    zinc: 4.5,
    cholesterol: 85,
    commonServing: "100g",
  },
  {
    id: "nem-nuong",
    code: "20011",
    name: "Nem nướng",
    nameEn: "Grilled pork sausage",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 195,
    protein: 18,
    carbs: 2,
    fat: 12,
    water: 67,
    sodium: 550,
    potassium: 250,
    calcium: 12,
    iron: 1.5,
    phosphorus: 180,
    magnesium: 18,
    zinc: 2.2,
    cholesterol: 72,
    commonServing: "100g (khoảng 3-4 cái)",
  },

  // More Seafood
  {
    id: "ca-loc",
    code: "30009",
    name: "Cá lóc",
    nameEn: "Snakehead fish",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 92,
    protein: 19,
    carbs: 0,
    fat: 1.2,
    water: 79,
    sodium: 55,
    potassium: 256,
    calcium: 20,
    iron: 0.5,
    phosphorus: 200,
    magnesium: 24,
    zinc: 0.7,
    cholesterol: 66,
    commonServing: "100g",
  },
  {
    id: "ca-tre",
    code: "30010",
    name: "Cá trê",
    nameEn: "Catfish",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 105,
    protein: 18,
    carbs: 0,
    fat: 3.2,
    water: 78,
    sodium: 50,
    potassium: 302,
    calcium: 14,
    iron: 0.6,
    phosphorus: 198,
    magnesium: 26,
    zinc: 0.9,
    cholesterol: 58,
    commonServing: "100g",
  },
  {
    id: "ca-chem",
    code: "30011",
    name: "Cá chẽm",
    nameEn: "Sea bass",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 124,
    protein: 20,
    carbs: 0,
    fat: 4.2,
    water: 75,
    sodium: 68,
    potassium: 328,
    calcium: 12,
    iron: 0.6,
    phosphorus: 210,
    magnesium: 28,
    zinc: 0.8,
    cholesterol: 62,
    commonServing: "100g",
  },
  {
    id: "cua-bien",
    code: "30012",
    name: "Cua biển",
    nameEn: "Sea crab",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 101,
    protein: 19,
    carbs: 0.1,
    fat: 1.6,
    water: 79,
    sodium: 395,
    potassium: 259,
    calcium: 91,
    iron: 0.8,
    phosphorus: 234,
    magnesium: 34,
    zinc: 3.8,
    vitaminA: 1,
    cholesterol: 78,
    commonServing: "100g (thịt cua)",
  },

  // More Vegetables
  {
    id: "rau-ngo",
    code: "40014",
    name: "Rau ngót",
    nameEn: "Sauropus leaves",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 35,
    protein: 5.3,
    carbs: 3.4,
    fat: 0.4,
    water: 90,
    fiber: 2.5,
    sodium: 25,
    potassium: 457,
    calcium: 169,
    iron: 2.7,
    phosphorus: 65,
    magnesium: 123,
    zinc: 0.5,
    vitaminC: 185,
    vitaminA: 11458,
    commonServing: "100g (1 bó nhỏ)",
  },
  {
    id: "rau-den",
    code: "40015",
    name: "Rau dền",
    nameEn: "Amaranth leaves",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 23,
    protein: 2.5,
    carbs: 4,
    fat: 0.3,
    water: 92,
    fiber: 2.2,
    sodium: 20,
    potassium: 611,
    calcium: 267,
    iron: 2.3,
    phosphorus: 67,
    magnesium: 55,
    zinc: 0.9,
    vitaminC: 43,
    vitaminA: 2917,
    commonServing: "100g (1 bó nhỏ)",
  },
  {
    id: "rau-ma",
    code: "40016",
    name: "Rau má",
    nameEn: "Centella leaves",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 44,
    protein: 2.6,
    carbs: 8.5,
    fat: 0.2,
    water: 88,
    fiber: 1.8,
    sodium: 4,
    potassium: 391,
    calcium: 171,
    iron: 1.2,
    phosphorus: 32,
    magnesium: 23,
    zinc: 0.2,
    vitaminC: 48,
    vitaminA: 361,
    commonServing: "100g",
  },
  {
    id: "rau-cai-thia",
    code: "40017",
    name: "Rau cải thìa",
    nameEn: "Bok choy",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 13,
    protein: 1.5,
    carbs: 2.2,
    fat: 0.2,
    water: 95,
    fiber: 1,
    sodium: 65,
    potassium: 252,
    calcium: 105,
    iron: 0.8,
    phosphorus: 37,
    magnesium: 19,
    zinc: 0.2,
    vitaminC: 45,
    vitaminA: 4468,
    commonServing: "100g",
  },
  {
    id: "rau-cai-cuc",
    code: "40018",
    name: "Rau cải cúc",
    nameEn: "Chrysanthemum greens",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 24,
    protein: 1.8,
    carbs: 4.5,
    fat: 0.3,
    water: 93,
    fiber: 1.2,
    sodium: 8,
    potassium: 220,
    calcium: 73,
    iron: 1.4,
    phosphorus: 30,
    magnesium: 20,
    zinc: 0.3,
    vitaminC: 1.4,
    vitaminA: 2320,
    commonServing: "100g",
  },
  {
    id: "khoai-mon",
    code: "40019",
    name: "Khoai môn",
    nameEn: "Taro",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 112,
    protein: 1.5,
    carbs: 26,
    fat: 0.2,
    water: 71,
    fiber: 4.1,
    sodium: 11,
    potassium: 591,
    calcium: 43,
    iron: 0.6,
    phosphorus: 84,
    magnesium: 33,
    zinc: 0.2,
    vitaminC: 4.5,
    vitaminA: 76,
    commonServing: "100g",
  },

  // More Fruits
  {
    id: "mang-cut",
    code: "50013",
    name: "Măng cụt",
    nameEn: "Mangosteen",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 73,
    protein: 0.4,
    carbs: 18,
    fat: 0.6,
    water: 81,
    fiber: 1.8,
    sodium: 7,
    potassium: 48,
    calcium: 12,
    iron: 0.3,
    phosphorus: 8,
    magnesium: 13,
    zinc: 0.2,
    vitaminC: 2.9,
    vitaminA: 0,
    commonServing: "100g (2-3 quả nhỏ)",
  },
  {
    id: "chom-chom",
    code: "50014",
    name: "Chôm chôm",
    nameEn: "Rambutan",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 82,
    protein: 0.7,
    carbs: 21,
    fat: 0.2,
    water: 78,
    fiber: 0.9,
    sodium: 11,
    potassium: 42,
    calcium: 22,
    iron: 0.4,
    phosphorus: 9,
    magnesium: 10,
    zinc: 0.1,
    vitaminC: 4.9,
    vitaminA: 0,
    commonServing: "100g (5-6 quả)",
  },
  {
    id: "mam-xoi",
    code: "50015",
    name: "Mâm xôi",
    nameEn: "Raspberry",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 52,
    protein: 1.2,
    carbs: 12,
    fat: 0.7,
    water: 86,
    fiber: 6.5,
    sodium: 1,
    potassium: 151,
    calcium: 25,
    iron: 0.7,
    phosphorus: 29,
    magnesium: 22,
    zinc: 0.4,
    vitaminC: 26.2,
    vitaminA: 2,
    commonServing: "100g (khoảng 1 bát nhỏ)",
  },
  {
    id: "dau-tay",
    code: "50016",
    name: "Dâu tây",
    nameEn: "Strawberry",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 32,
    protein: 0.7,
    carbs: 8,
    fat: 0.3,
    water: 91,
    fiber: 2,
    sodium: 1,
    potassium: 153,
    calcium: 16,
    iron: 0.4,
    phosphorus: 24,
    magnesium: 13,
    zinc: 0.1,
    vitaminC: 58.8,
    vitaminA: 1,
    commonServing: "100g (khoảng 8-10 quả)",
  },

  // More Legumes
  {
    id: "dau-co-ve",
    code: "60008",
    name: "Đậu cô ve",
    nameEn: "Green beans",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.2,
    water: 90,
    fiber: 2.7,
    sodium: 6,
    potassium: 211,
    calcium: 37,
    iron: 1,
    phosphorus: 38,
    magnesium: 25,
    zinc: 0.2,
    vitaminC: 12.2,
    vitaminA: 35,
    commonServing: "100g",
  },
  {
    id: "dau-ha-lan",
    code: "60009",
    name: "Đậu Hà Lan",
    nameEn: "Peas",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 81,
    protein: 5.4,
    carbs: 14,
    fat: 0.4,
    water: 79,
    fiber: 5.1,
    sodium: 5,
    potassium: 244,
    calcium: 25,
    iron: 1.5,
    phosphorus: 108,
    magnesium: 33,
    zinc: 1.2,
    vitaminC: 40,
    vitaminA: 38,
    commonServing: "100g",
  },

  // More Dairy
  {
    id: "sua-chua-uop-lanh",
    code: "80008",
    name: "Sữa chua ướp lạnh",
    nameEn: "Frozen yogurt",
    category: "dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 127,
    protein: 3,
    carbs: 22,
    fat: 3.6,
    water: 71,
    sodium: 80,
    potassium: 199,
    calcium: 100,
    iron: 0.1,
    phosphorus: 95,
    magnesium: 12,
    zinc: 0.4,
    vitaminA: 30,
    vitaminC: 0.5,
    cholesterol: 12,
    commonServing: "100g (1 hũ)",
  },
  {
    id: "trung-vit",
    code: "80009",
    name: "Trứng vịt",
    nameEn: "Duck egg",
    category: "dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 185,
    protein: 13,
    carbs: 1.5,
    fat: 14,
    water: 70,
    sodium: 146,
    potassium: 222,
    calcium: 64,
    iron: 3.9,
    phosphorus: 220,
    magnesium: 17,
    zinc: 1.4,
    vitaminA: 194,
    vitaminC: 0,
    cholesterol: 884,
    commonServing: "100g (khoảng 1.5 quả)",
  },

  // More Beverages
  {
    id: "nuoc-mia",
    code: "90007",
    name: "Nước mía",
    nameEn: "Sugarcane juice",
    category: "beverages",
    servingSize: 100,
    servingUnit: "ml",
    calories: 57,
    protein: 0.3,
    carbs: 14,
    fat: 0.1,
    water: 85,
    sodium: 1,
    potassium: 95,
    calcium: 18,
    iron: 0.4,
    phosphorus: 12,
    magnesium: 10,
    zinc: 0.1,
    vitaminC: 2.4,
    commonServing: "100ml (1 ly nhỏ)",
  },
  {
    id: "nuoc-dau-xanh",
    code: "90008",
    name: "Nước đậu xanh",
    nameEn: "Mung bean drink",
    category: "beverages",
    servingSize: 100,
    servingUnit: "ml",
    calories: 35,
    protein: 2.4,
    carbs: 6.3,
    fat: 0.1,
    water: 91,
    sodium: 1.5,
    potassium: 125,
    calcium: 13,
    iron: 0.7,
    phosphorus: 37,
    magnesium: 19,
    zinc: 0.3,
    vitaminC: 0,
    commonServing: "100ml (1 ly nhỏ)",
  },
  {
    id: "tra-atiso",
    code: "90009",
    name: "Trà atiso",
    nameEn: "Artichoke tea",
    category: "beverages",
    servingSize: 100,
    servingUnit: "ml",
    calories: 1,
    protein: 0.1,
    carbs: 0.2,
    fat: 0,
    water: 99,
    sodium: 2,
    potassium: 15,
    calcium: 1,
    iron: 0.02,
    phosphorus: 1,
    magnesium: 1,
    zinc: 0.01,
    vitaminC: 0,
    commonServing: "100ml (1 ly)",
  },

  // More Snacks
  {
    id: "banh-trang",
    code: "10016",
    name: "Bánh tráng",
    nameEn: "Rice paper",
    category: "snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 330,
    protein: 7.2,
    carbs: 72,
    fat: 0.5,
    water: 19,
    fiber: 0.3,
    sodium: 2,
    potassium: 15,
    calcium: 8,
    iron: 1.2,
    phosphorus: 20,
    magnesium: 5,
    zinc: 0.3,
    commonServing: "100g (khoảng 20-25 tờ)",
  },
  {
    id: "banh-phong-tom",
    code: "10017",
    name: "Bánh phồng tôm",
    nameEn: "Shrimp chips",
    category: "snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 387,
    protein: 2.8,
    carbs: 78,
    fat: 6.2,
    water: 11,
    fiber: 0.5,
    sodium: 680,
    potassium: 25,
    calcium: 5,
    iron: 0.3,
    phosphorus: 15,
    magnesium: 8,
    zinc: 0.2,
    cholesterol: 5,
    commonServing: "100g (khoảng 15-20 cái)",
  },

  // Desserts
  {
    id: "che-dau-xanh",
    code: "12001",
    name: "Chè đậu xanh",
    nameEn: "Mung bean dessert",
    category: "desserts",
    servingSize: 100,
    servingUnit: "g",
    calories: 95,
    protein: 2.4,
    carbs: 20,
    fat: 0.2,
    water: 76,
    fiber: 1.6,
    sodium: 2,
    potassium: 125,
    calcium: 13,
    iron: 0.7,
    phosphorus: 37,
    magnesium: 19,
    zinc: 0.3,
    commonServing: "100g (1 bát nhỏ)",
  },
  {
    id: "che-khoai-mon",
    code: "12002",
    name: "Chè khoai môn",
    nameEn: "Taro dessert",
    category: "desserts",
    servingSize: 100,
    servingUnit: "g",
    calories: 112,
    protein: 1.5,
    carbs: 26,
    fat: 0.2,
    water: 71,
    fiber: 4.1,
    sodium: 11,
    potassium: 591,
    calcium: 43,
    iron: 0.6,
    phosphorus: 84,
    magnesium: 33,
    zinc: 0.2,
    vitaminC: 4.5,
    vitaminA: 76,
    commonServing: "100g (1 bát nhỏ)",
  },
  {
    id: "kem",
    code: "12003",
    name: "Kem",
    nameEn: "Ice cream",
    category: "desserts",
    servingSize: 100,
    servingUnit: "g",
    calories: 207,
    protein: 3.5,
    carbs: 24,
    fat: 11,
    water: 61,
    sodium: 80,
    potassium: 199,
    calcium: 128,
    iron: 0.1,
    phosphorus: 105,
    magnesium: 14,
    zinc: 0.4,
    vitaminA: 118,
    vitaminC: 0.6,
    cholesterol: 44,
    commonServing: "100g (1 cây kem)",
  },
];

/**
 * Search foods by name
 */
export function searchFoods(query: string): FoodItem[] {
  if (!query.trim()) return [];

  const lowerQuery = query.toLowerCase();
  return foodDatabase.filter(
    (food) =>
      food.name.toLowerCase().includes(lowerQuery) ||
      food.nameEn?.toLowerCase().includes(lowerQuery)
  );
}

/**
 * Get foods by category
 */
export function getFoodsByCategory(category: FoodCategory): FoodItem[] {
  return foodDatabase.filter((food) => food.category === category);
}

/**
 * Get food by ID
 */
export function getFoodById(id: string): FoodItem | undefined {
  return foodDatabase.find((food) => food.id === id);
}

/**
 * Calculate nutrition for multiple servings
 */
export function calculateNutrition(
  food: FoodItem,
  servings: number
): Omit<FoodItem, "id" | "code" | "name" | "nameEn" | "category" | "notes" | "commonServing"> {
  const multiplier = servings;
  return {
    servingSize: food.servingSize * multiplier,
    servingUnit: food.servingUnit,
    calories: food.calories * multiplier,
    protein: food.protein * multiplier,
    carbs: food.carbs * multiplier,
    fat: food.fat * multiplier,
    water: food.water ? food.water * multiplier : undefined,
    fiber: food.fiber ? food.fiber * multiplier : undefined,
    sodium: food.sodium ? food.sodium * multiplier : undefined,
    potassium: food.potassium ? food.potassium * multiplier : undefined,
    calcium: food.calcium ? food.calcium * multiplier : undefined,
    iron: food.iron ? food.iron * multiplier : undefined,
    phosphorus: food.phosphorus ? food.phosphorus * multiplier : undefined,
    magnesium: food.magnesium ? food.magnesium * multiplier : undefined,
    zinc: food.zinc ? food.zinc * multiplier : undefined,
    vitaminC: food.vitaminC ? food.vitaminC * multiplier : undefined,
    vitaminA: food.vitaminA ? food.vitaminA * multiplier : undefined,
    cholesterol: food.cholesterol ? food.cholesterol * multiplier : undefined,
  };
}

/**
 * Get nutrition values per 100g (already normalized in our database)
 */
export function getNutritionPer100g(food: FoodItem): Omit<FoodItem, "id" | "code" | "name" | "nameEn" | "category" | "notes" | "commonServing"> {
  return {
    servingSize: 100,
    servingUnit: "g",
    calories: food.calories,
    protein: food.protein,
    carbs: food.carbs,
    fat: food.fat,
    water: food.water,
    fiber: food.fiber,
    sodium: food.sodium,
    potassium: food.potassium,
    calcium: food.calcium,
    iron: food.iron,
    phosphorus: food.phosphorus,
    magnesium: food.magnesium,
    zinc: food.zinc,
    vitaminC: food.vitaminC,
    vitaminA: food.vitaminA,
    cholesterol: food.cholesterol,
  };
}

/**
 * Filter foods by kcal range
 */
export type KcalRange = "all" | "<50" | "50-100" | "100-200" | "200-300" | ">300";

export function filterFoodsByKcalRange(foods: FoodItem[], range: KcalRange): FoodItem[] {
  if (range === "all") return foods;

  return foods.filter((food) => {
    const kcal = food.calories;
    switch (range) {
      case "<50":
        return kcal < 50;
      case "50-100":
        return kcal >= 50 && kcal < 100;
      case "100-200":
        return kcal >= 100 && kcal < 200;
      case "200-300":
        return kcal >= 200 && kcal < 300;
      case ">300":
        return kcal >= 300;
      default:
        return true;
    }
  });
}
