/**
 * Extended Vietnamese food database with disease-specific information
 * 
 * Mở rộng từ food-db.ts với thông tin về:
 * - Đái tháo đường: GI, GL
 * - Bệnh gút: Purin
 * - Bệnh thận: Kali, Phốt pho
 * - Tăng huyết áp: Natri
 * - Tim mạch: Cholesterol, Chất béo bão hòa
 */

import type { FoodItem } from "./food-db";

export interface DiseaseSpecificInfo {
  // Đái tháo đường
  diabetes?: {
    glycemicIndex?: number; // GI
    glycemicLoad?: number; // GL cho khẩu phần thông thường
    carbPerPortion: number; // g carb trong khẩu phần thông thường
  };
  
  // Bệnh gút
  gout?: {
    purine: number; // mg/100g
    purineLevel: 'very-high' | 'high' | 'medium' | 'low';
  };
  
  // Bệnh thận
  kidney?: {
    potassium: number; // mg/100g
    phosphorus: number; // mg/100g
  };
  
  // Tăng huyết áp (natri đã có trong FoodItem)
  
  // Tim mạch
  cardiovascular?: {
    cholesterol: number; // mg/100g
    saturatedFat: number; // g/100g
  };
}

export interface ExtendedFoodItem extends Omit<FoodItem, 'code'>, DiseaseSpecificInfo {
  // Vitamin nhóm B & vitamin D (đơn vị tham khảo, dùng cho mục đích giáo dục)
  vitaminB1?: number; // mg per 100g
  vitaminB2?: number; // mg per 100g
  vitaminB6?: number; // mg per 100g
  folate?: number; // µg per 100g
  vitaminB12?: number; // µg per 100g
  vitaminD?: number; // IU per 100g

  // Đơn vị Việt Nam
  vietnameseUnits?: {
    unit: 'bat' | 'thia-canh' | 'thia-ca-phe' | 'dia' | 'to' | 'cai' | 'qua' | 'mieng' | 'bo';
    weight: number; // grams
    description: string;
  }[];
}

/**
 * Database thực phẩm Việt Nam với thông tin đầy đủ
 */
export const extendedFoodDatabase: ExtendedFoodItem[] = [
  // Rice & Noodles
  {
    id: "com-trang",
    name: "Cơm trắng",
    nameEn: "White rice",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    sodium: 1,
    vitaminB1: 0.02,
    vitaminB2: 0.01,
    vitaminB6: 0.1,
    folate: 8,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 bát nhỏ (100g)",
    diabetes: {
      glycemicIndex: 73,
      glycemicLoad: 33, // cho 1 bát vừa (~150g)
      carbPerPortion: 45,
    },
    kidney: {
      potassium: 30,
      phosphorus: 30,
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0.1,
    },
    vietnameseUnits: [
      { unit: 'bat', weight: 150, description: '1 bát vừa' },
      { unit: 'bat', weight: 100, description: '1 bát nhỏ' },
    ],
  },
  {
    id: "com-gao-lut",
    name: "Cơm gạo lứt",
    nameEn: "Brown rice",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    fiber: 1.8,
    sodium: 5,
    vitaminB1: 0.18,
    vitaminB2: 0.05,
    vitaminB6: 0.3,
    folate: 9,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 bát vừa (150g)",
    diabetes: {
      glycemicIndex: 55,
      glycemicLoad: 25, // cho 1 bát vừa (~150g)
      carbPerPortion: 45,
    },
    kidney: {
      potassium: 43,
      phosphorus: 83, // cao hơn gạo trắng
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0.2,
    },
    vietnameseUnits: [
      { unit: 'bat', weight: 150, description: '1 bát vừa' },
    ],
  },
  {
    id: "pho-bo",
    name: "Phở bò",
    nameEn: "Beef pho",
    category: "rice-noodles",
    servingSize: 300,
    servingUnit: "g",
    calories: 350,
    protein: 20,
    carbs: 45,
    fat: 8,
    fiber: 2,
    sodium: 1200,
    commonServing: "1 tô vừa (300g)",
    notes: "Bao gồm bánh phở, thịt bò, nước dùng",
    diabetes: {
      glycemicIndex: 45,
      glycemicLoad: 10, // cho 1 tô vừa
      carbPerPortion: 22, // chỉ bánh phở
    },
    gout: {
      purine: 160, // từ thịt bò
      purineLevel: 'high',
    },
    kidney: {
      potassium: 200,
      phosphorus: 200,
    },
    cardiovascular: {
      cholesterol: 50,
      saturatedFat: 3,
    },
    vietnameseUnits: [
      { unit: 'to', weight: 300, description: '1 tô vừa' },
      { unit: 'to', weight: 250, description: '1 tô nhỏ' },
    ],
  },
  {
    id: "bun",
    name: "Bún",
    nameEn: "Rice vermicelli",
    category: "rice-noodles",
    servingSize: 100,
    servingUnit: "g",
    calories: 109,
    protein: 1.8,
    carbs: 25,
    fat: 0.2,
    fiber: 0.5,
    sodium: 1,
    commonServing: "100g (1 phần bún)",
    diabetes: {
      glycemicIndex: 53,
      glycemicLoad: 13, // cho 1 tô bún (~100g bún)
      carbPerPortion: 25,
    },
    kidney: {
      potassium: 10,
      phosphorus: 20,
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0,
    },
    vietnameseUnits: [
      { unit: 'to', weight: 100, description: '1 tô bún' },
    ],
  },

  // Meat
  {
    id: "thit-heo-nac",
    name: "Thịt heo nạc",
    nameEn: "Lean pork",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 143,
    protein: 27,
    carbs: 0,
    fat: 3.5,
    sodium: 62,
    iron: 0.9,
    vitaminB1: 0.8,
    vitaminB2: 0.2,
    vitaminB6: 0.5,
    folate: 5,
    vitaminB12: 0.7,
    vitaminD: 0,
    commonServing: "100g (khoảng 1 lòng bàn tay)",
    gout: {
      purine: 150,
      purineLevel: 'high',
    },
    kidney: {
      potassium: 200,
      phosphorus: 200,
    },
    cardiovascular: {
      cholesterol: 80,
      saturatedFat: 1.2,
    },
    vietnameseUnits: [
      { unit: 'mieng', weight: 100, description: '1 miếng vừa (100g)' },
    ],
  },
  {
    id: "thit-ga",
    name: "Thịt gà",
    nameEn: "Chicken",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    sodium: 74,
    iron: 0.9,
    vitaminB1: 0.07,
    vitaminB2: 0.15,
    vitaminB6: 0.5,
    folate: 4,
    vitaminB12: 0.3,
    vitaminD: 0,
    commonServing: "100g (khoảng 1 lòng bàn tay)",
    gout: {
      purine: 140,
      purineLevel: 'medium',
    },
    kidney: {
      potassium: 200,
      phosphorus: 200,
    },
    cardiovascular: {
      cholesterol: 85,
      saturatedFat: 1, // bỏ da
    },
    vietnameseUnits: [
      { unit: 'mieng', weight: 100, description: '1 miếng vừa (100g)' },
    ],
  },
  {
    id: "thit-bo",
    name: "Thịt bò",
    nameEn: "Beef",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    sodium: 72,
    iron: 2.6,
    vitaminB1: 0.05,
    vitaminB2: 0.2,
    vitaminB6: 0.4,
    folate: 9,
    vitaminB12: 2.5,
    vitaminD: 0,
    commonServing: "100g (khoảng 1 lòng bàn tay)",
    gout: {
      purine: 160,
      purineLevel: 'high',
    },
    kidney: {
      potassium: 200,
      phosphorus: 200,
    },
    cardiovascular: {
      cholesterol: 70,
      saturatedFat: 6,
    },
    vietnameseUnits: [
      { unit: 'mieng', weight: 100, description: '1 miếng vừa (100g)' },
    ],
  },
  {
    id: "gan-lon",
    name: "Gan lợn",
    nameEn: "Pork liver",
    category: "meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 21,
    carbs: 3,
    fat: 3.6,
    sodium: 87,
    iron: 15,
    commonServing: "100g",
    gout: {
      purine: 300,
      purineLevel: 'very-high',
    },
    kidney: {
      potassium: 300,
      phosphorus: 300,
    },
    cardiovascular: {
      cholesterol: 300,
      saturatedFat: 1.2,
    },
    notes: "Nội tạng có purin và cholesterol rất cao - tránh cho người gút và tim mạch",
  },

  // Seafood
  {
    id: "ca-basa",
    name: "Cá basa",
    nameEn: "Basa fish",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 162,
    protein: 18,
    carbs: 0,
    fat: 9,
    sodium: 45,
    commonServing: "100g (1 miếng vừa)",
    gout: {
      purine: 100,
      purineLevel: 'medium',
    },
    kidney: {
      potassium: 200,
      phosphorus: 200,
    },
    cardiovascular: {
      cholesterol: 50,
      saturatedFat: 2,
    },
    vietnameseUnits: [
      { unit: 'mieng', weight: 100, description: '1 miếng vừa (100g)' },
    ],
  },
  {
    id: "ca-loc",
    name: "Cá lóc",
    nameEn: "Snakehead fish",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 97,
    protein: 19,
    carbs: 0,
    fat: 1.5,
    sodium: 50,
    commonServing: "100g (1 miếng vừa)",
    gout: {
      purine: 110,
      purineLevel: 'medium',
    },
    kidney: {
      potassium: 200,
      phosphorus: 200,
    },
    cardiovascular: {
      cholesterol: 60,
      saturatedFat: 0.5,
    },
    vietnameseUnits: [
      { unit: 'mieng', weight: 100, description: '1 miếng vừa (100g)' },
    ],
  },
  {
    id: "tom",
    name: "Tôm",
    nameEn: "Shrimp",
    category: "seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
    sodium: 111,
    calcium: 52,
    iron: 0.3,
    commonServing: "100g (khoảng 8-10 con vừa)",
    gout: {
      purine: 150,
      purineLevel: 'high',
    },
    kidney: {
      potassium: 200,
      phosphorus: 200,
    },
    cardiovascular: {
      cholesterol: 150,
      saturatedFat: 0.2,
    },
    vietnameseUnits: [
      { unit: 'cai', weight: 10, description: '1 con tôm vừa (10g)' },
    ],
  },

  // Vegetables
  {
    id: "rau-muong",
    name: "Rau muống",
    nameEn: "Water spinach",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 19,
    protein: 2.6,
    carbs: 3.1,
    fat: 0.2,
    fiber: 2.1,
    sodium: 79,
    calcium: 77,
    iron: 1.7,
    vitaminC: 55,
    vitaminA: 3158,
    commonServing: "100g (1 bó nhỏ)",
    diabetes: {
      glycemicIndex: 20,
      glycemicLoad: 1,
      carbPerPortion: 3.1,
    },
    gout: {
      purine: 20,
      purineLevel: 'low',
    },
    kidney: {
      potassium: 100,
      phosphorus: 30,
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0,
    },
    vietnameseUnits: [
      { unit: 'bo', weight: 100, description: '1 bó nhỏ' },
    ],
  },
  {
    id: "cai-xanh",
    name: "Cải xanh",
    nameEn: "Chinese cabbage",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 16,
    protein: 1.5,
    carbs: 3.2,
    fat: 0.2,
    fiber: 1.2,
    sodium: 65,
    calcium: 105,
    iron: 0.8,
    vitaminC: 36,
    vitaminA: 4468,
    commonServing: "100g",
    diabetes: {
      glycemicIndex: 15,
      glycemicLoad: 0.5,
      carbPerPortion: 3.2,
    },
    gout: {
      purine: 15,
      purineLevel: 'low',
    },
    kidney: {
      potassium: 170,
      phosphorus: 30,
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0,
    },
  },
  {
    id: "ca-chua",
    name: "Cà chua",
    nameEn: "Tomato",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    sodium: 5,
    calcium: 10,
    iron: 0.3,
    vitaminC: 14,
    vitaminA: 833,
    commonServing: "100g (1-2 quả vừa)",
    diabetes: {
      glycemicIndex: 15,
      glycemicLoad: 0.6,
      carbPerPortion: 3.9,
    },
    gout: {
      purine: 10,
      purineLevel: 'low',
    },
    kidney: {
      potassium: 237,
      phosphorus: 24,
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0,
    },
    vietnameseUnits: [
      { unit: 'qua', weight: 100, description: '1-2 quả vừa' },
    ],
  },
  {
    id: "khoai-tay",
    name: "Khoai tây",
    nameEn: "Potato",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    fiber: 2.2,
    sodium: 6,
    calcium: 12,
    iron: 0.8,
    vitaminC: 19.7,
    commonServing: "100g (1 củ vừa)",
    diabetes: {
      glycemicIndex: 78,
      glycemicLoad: 13,
      carbPerPortion: 17,
    },
    gout: {
      purine: 10,
      purineLevel: 'low',
    },
    kidney: {
      potassium: 421, // Rất cao!
      phosphorus: 57,
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0,
    },
    notes: "Kali rất cao - hạn chế cho người bệnh thận",
    vietnameseUnits: [
      { unit: 'cai', weight: 100, description: '1 củ vừa' },
    ],
  },
  {
    id: "khoai-lang",
    name: "Khoai lang",
    nameEn: "Sweet potato",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fiber: 3,
    sodium: 54,
    calcium: 30,
    iron: 0.6,
    vitaminC: 2.4,
    vitaminA: 14187,
    commonServing: "100g (1 củ vừa)",
    diabetes: {
      glycemicIndex: 54,
      glycemicLoad: 11,
      carbPerPortion: 20,
    },
    gout: {
      purine: 10,
      purineLevel: 'low',
    },
    kidney: {
      potassium: 337, // Cao
      phosphorus: 47,
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0,
    },
    vietnameseUnits: [
      { unit: 'cai', weight: 100, description: '1 củ vừa' },
    ],
  },

  // Fruits
  {
    id: "chuoi",
    name: "Chuối",
    nameEn: "Banana",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    sodium: 1,
    calcium: 5,
    iron: 0.3,
    vitaminC: 8.7,
    commonServing: "100g (1 quả vừa)",
    diabetes: {
      glycemicIndex: 51, // chín vừa
      glycemicLoad: 12,
      carbPerPortion: 23,
    },
    gout: {
      purine: 10,
      purineLevel: 'low',
    },
    kidney: {
      potassium: 358, // Rất cao!
      phosphorus: 22,
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0,
    },
    notes: "Kali rất cao - hạn chế cho người bệnh thận",
    vietnameseUnits: [
      { unit: 'qua', weight: 100, description: '1 quả vừa' },
    ],
  },
  {
    id: "cam",
    name: "Cam",
    nameEn: "Orange",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    fiber: 2.4,
    sodium: 0,
    calcium: 40,
    iron: 0.1,
    vitaminC: 53.2,
    vitaminA: 225,
    commonServing: "100g (1 quả vừa)",
    diabetes: {
      glycemicIndex: 42,
      glycemicLoad: 5,
      carbPerPortion: 12,
    },
    gout: {
      purine: 10,
      purineLevel: 'low',
    },
    kidney: {
      potassium: 181,
      phosphorus: 14,
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0,
    },
    vietnameseUnits: [
      { unit: 'qua', weight: 100, description: '1 quả vừa' },
    ],
  },
  {
    id: "tao",
    name: "Táo",
    nameEn: "Apple",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    sodium: 1,
    calcium: 6,
    iron: 0.1,
    vitaminC: 4.6,
    commonServing: "100g (1 quả vừa)",
    diabetes: {
      glycemicIndex: 36,
      glycemicLoad: 5,
      carbPerPortion: 14,
    },
    gout: {
      purine: 10,
      purineLevel: 'low',
    },
    kidney: {
      potassium: 107,
      phosphorus: 12,
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0,
    },
    vietnameseUnits: [
      { unit: 'qua', weight: 100, description: '1 quả vừa' },
    ],
  },

  // Legumes
  {
    id: "dau-phu",
    name: "Đậu phụ",
    nameEn: "Tofu",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 76,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
    fiber: 0.3,
    sodium: 7,
    calcium: 350,
    iron: 5.4,
    commonServing: "100g (1 miếng vừa)",
    diabetes: {
      glycemicIndex: 15,
      glycemicLoad: 0.3,
      carbPerPortion: 1.9,
    },
    gout: {
      purine: 50,
      purineLevel: 'medium',
    },
    kidney: {
      potassium: 150,
      phosphorus: 120,
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0.7,
    },
    notes: "Đạm thực vật, tốt cho tim mạch và người gút",
    vietnameseUnits: [
      { unit: 'mieng', weight: 100, description: '1 miếng vừa' },
    ],
  },
  {
    id: "dau-xanh",
    name: "Đậu xanh",
    nameEn: "Mung beans",
    category: "legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 347,
    protein: 24,
    carbs: 63,
    fat: 1.2,
    fiber: 16.3,
    sodium: 15,
    calcium: 132,
    iron: 6.7,
    commonServing: "100g (nấu chín)",
    diabetes: {
      glycemicIndex: 25,
      glycemicLoad: 16,
      carbPerPortion: 63,
    },
    gout: {
      purine: 50,
      purineLevel: 'medium',
    },
    kidney: {
      potassium: 400, // Rất cao!
      phosphorus: 400, // Rất cao!
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0.3,
    },
    notes: "Kali và phốt pho rất cao - hạn chế cho người bệnh thận",
  },

  // Condiments
  {
    id: "nuoc-mam",
    name: "Nước mắm",
    nameEn: "Fish sauce",
    category: "condiments",
    servingSize: 15,
    servingUnit: "ml",
    calories: 8,
    protein: 1.3,
    carbs: 0.8,
    fat: 0,
    sodium: 1500,
    commonServing: "1 muỗng canh (15ml)",
    notes: "Rất nhiều natri - dùng ít cho người tăng huyết áp",
    kidney: {
      potassium: 50,
      phosphorus: 10,
    },
    cardiovascular: {
      cholesterol: 0,
      saturatedFat: 0,
    },
    vietnameseUnits: [
      { unit: 'thia-canh', weight: 15, description: '1 muỗng canh (15ml)' },
      { unit: 'thia-ca-phe', weight: 5, description: '1 muỗng cà phê (5ml)' },
    ],
  },
  // ========================================================================
  // Bổ sung thêm rau lá & trái cây (phần 36–37: 186–200)
  // ========================================================================
  {
    id: "rau-den-veg16",
    name: "Rau dền",
    nameEn: "Amaranth leaves",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 23,
    protein: 2.5,
    carbs: 4.0,
    fat: 0.3,
    fiber: 2.2,
    water: 92.0,
    sodium: 12,
    potassium: 611,
    calcium: 215,
    iron: 2.3,
    phosphorus: 43,
    magnesium: 55,
    zinc: 0.9,
    vitaminA: 291,
    vitaminC: 43.0,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.06,
    vitaminB2: 0.12,
    vitaminB6: 0.10,
    folate: 85,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 bát (~100g)",
    notes: "Rất giàu kali; CKD cần hạn chế.",
    kidney: { potassium: 611, phosphorus: 43 },
  },
  {
    id: "rau-day",
    name: "Rau đay",
    nameEn: "Jute leaves",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 34,
    protein: 4.0,
    carbs: 5.8,
    fat: 0.6,
    fiber: 2.0,
    water: 87.0,
    sodium: 15,
    potassium: 510,
    calcium: 182,
    iron: 3.3,
    phosphorus: 55,
    magnesium: 65,
    zinc: 0.7,
    vitaminA: 3800,
    vitaminC: 53.0,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.09,
    vitaminB2: 0.16,
    vitaminB6: 0.15,
    folate: 140,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 bát (~100g)",
    notes: "Nhiều chất nhầy, tốt tiêu hóa.",
    kidney: { potassium: 510, phosphorus: 55 },
  },
  {
    id: "tan-o",
    name: "Rau tần ô",
    nameEn: "Crown daisy",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 23,
    protein: 2.9,
    carbs: 3.9,
    fat: 0.4,
    fiber: 1.6,
    water: 92.0,
    sodium: 18,
    potassium: 340,
    calcium: 120,
    iron: 1.5,
    phosphorus: 50,
    magnesium: 45,
    zinc: 0.6,
    vitaminA: 4200,
    vitaminC: 11.0,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.06,
    vitaminB2: 0.10,
    vitaminB6: 0.12,
    folate: 105,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 bát (~100g)",
    notes: "Rau lẩu phổ biến.",
    kidney: { potassium: 340, phosphorus: 50 },
  },
  {
    id: "hanh-la",
    name: "Hành lá",
    nameEn: "Spring onion",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 32,
    protein: 1.8,
    carbs: 7.3,
    fat: 0.2,
    sugars: 2.3,
    fiber: 2.6,
    water: 89.0,
    sodium: 16,
    potassium: 276,
    calcium: 72,
    iron: 1.5,
    phosphorus: 37,
    magnesium: 20,
    zinc: 0.4,
    vitaminA: 997,
    vitaminC: 18.8,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.08,
    vitaminB2: 0.13,
    vitaminB6: 0.10,
    folate: 64,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "Dùng gia vị",
    notes: "Ăn lượng nhỏ.",
    kidney: { potassium: 276, phosphorus: 37 },
  },
  {
    id: "hung-que",
    name: "Húng quế",
    nameEn: "Sweet basil",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 23,
    protein: 3.2,
    carbs: 2.7,
    fat: 0.6,
    fiber: 1.6,
    water: 92.0,
    sodium: 4,
    potassium: 295,
    calcium: 177,
    iron: 3.2,
    phosphorus: 56,
    magnesium: 64,
    zinc: 0.8,
    vitaminA: 5275,
    vitaminC: 18.0,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.03,
    vitaminB2: 0.08,
    vitaminB6: 0.15,
    folate: 68,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "Ăn kèm",
    notes: "Rau gia vị, giàu vi chất.",
    kidney: { potassium: 295, phosphorus: 56 },
  },
  {
    id: "ca-tim",
    name: "Cà tím",
    nameEn: "Eggplant",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 25,
    protein: 1.0,
    carbs: 5.9,
    fat: 0.2,
    sugars: 3.5,
    fiber: 3.0,
    water: 93.0,
    sodium: 2,
    potassium: 229,
    calcium: 9,
    iron: 0.2,
    phosphorus: 24,
    magnesium: 14,
    zinc: 0.2,
    vitaminA: 23,
    vitaminC: 2.2,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.04,
    vitaminB2: 0.04,
    vitaminB6: 0.08,
    folate: 22,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 quả nhỏ (~100g)",
    notes: "Ít năng lượng.",
    diabetes: { glycemicIndex: 20, glycemicLoad: 1, carbPerPortion: 6 },
    kidney: { potassium: 229, phosphorus: 24 },
  },
  {
    id: "dau-bap",
    name: "Đậu bắp",
    nameEn: "Okra",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 33,
    protein: 1.9,
    carbs: 7.5,
    fat: 0.2,
    sugars: 1.5,
    fiber: 3.2,
    water: 90.0,
    sodium: 7,
    potassium: 299,
    calcium: 82,
    iron: 0.6,
    phosphorus: 61,
    magnesium: 57,
    zinc: 0.6,
    vitaminA: 716,
    vitaminC: 23.0,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.20,
    vitaminB2: 0.06,
    vitaminB6: 0.22,
    folate: 60,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 bát (~100g)",
    notes: "Chất nhầy tốt tiêu hóa.",
    diabetes: { glycemicIndex: 20, glycemicLoad: 2, carbPerPortion: 7 },
    kidney: { potassium: 299, phosphorus: 61 },
  },
  {
    id: "kho-qua",
    name: "Khổ qua",
    nameEn: "Bitter melon",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 17,
    protein: 1.0,
    carbs: 3.7,
    fat: 0.2,
    sugars: 1.0,
    fiber: 2.8,
    water: 94.0,
    sodium: 6,
    potassium: 296,
    calcium: 19,
    iron: 0.4,
    phosphorus: 31,
    magnesium: 17,
    zinc: 0.2,
    vitaminA: 471,
    vitaminC: 84.0,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.04,
    vitaminB2: 0.04,
    vitaminB6: 0.05,
    folate: 72,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 quả (~100g)",
    notes: "Hay dùng cho ĐTĐ.",
    diabetes: { glycemicIndex: 15, glycemicLoad: 1, carbPerPortion: 4 },
    kidney: { potassium: 296, phosphorus: 31 },
  },
  {
    id: "muop-huong",
    name: "Mướp hương",
    nameEn: "Angled luffa",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 20,
    protein: 0.8,
    carbs: 4.4,
    fat: 0.2,
    sugars: 1.5,
    fiber: 1.1,
    water: 93.0,
    sodium: 3,
    potassium: 150,
    calcium: 18,
    iron: 0.5,
    phosphorus: 30,
    magnesium: 14,
    zinc: 0.3,
    vitaminA: 0,
    vitaminC: 9.0,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.03,
    vitaminB2: 0.04,
    vitaminB6: 0.06,
    folate: 25,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 khúc (~100g)",
    notes: "Thanh mát.",
    diabetes: { glycemicIndex: 20, glycemicLoad: 1, carbPerPortion: 4 },
    kidney: { potassium: 150, phosphorus: 30 },
  },
  {
    id: "chuoi-tieu",
    name: "Chuối tiêu",
    nameEn: "Banana",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    sugars: 12.2,
    fiber: 2.6,
    water: 74.0,
    sodium: 1,
    potassium: 358,
    calcium: 5,
    iron: 0.3,
    phosphorus: 22,
    magnesium: 27,
    zinc: 0.2,
    vitaminA: 64,
    vitaminC: 8.7,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.03,
    vitaminB2: 0.07,
    vitaminB6: 0.40,
    folate: 20,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 quả (~100g)",
    notes: "Kali cao; CKD lưu ý.",
    diabetes: { glycemicIndex: 51, glycemicLoad: 13, carbPerPortion: 26 },
    kidney: { potassium: 358, phosphorus: 22 },
  },
  {
    id: "cam-sanh",
    name: "Cam sành",
    nameEn: "Orange",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 47,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
    sugars: 9.4,
    fiber: 2.4,
    water: 86.0,
    sodium: 0,
    potassium: 181,
    calcium: 40,
    iron: 0.1,
    phosphorus: 14,
    magnesium: 10,
    zinc: 0.1,
    vitaminA: 225,
    vitaminC: 53.2,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.09,
    vitaminB2: 0.04,
    vitaminB6: 0.06,
    folate: 30,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 quả (~130g)",
    notes: "Vitamin C cao.",
    diabetes: { glycemicIndex: 43, glycemicLoad: 5, carbPerPortion: 15 },
    kidney: { potassium: 181, phosphorus: 14 },
  },
  {
    id: "quyt",
    name: "Quýt",
    nameEn: "Mandarin",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 53,
    protein: 0.8,
    carbs: 13.3,
    fat: 0.3,
    sugars: 10.6,
    fiber: 1.8,
    water: 85.0,
    sodium: 2,
    potassium: 166,
    calcium: 37,
    iron: 0.2,
    phosphorus: 20,
    magnesium: 12,
    zinc: 0.1,
    vitaminA: 681,
    vitaminC: 26.7,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.06,
    vitaminB2: 0.04,
    vitaminB6: 0.08,
    folate: 16,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 quả (~100g)",
    notes: "Ngọt vừa.",
    diabetes: { glycemicIndex: 42, glycemicLoad: 6, carbPerPortion: 13 },
    kidney: { potassium: 166, phosphorus: 20 },
  },
  {
    id: "vu-sua",
    name: "Vú sữa",
    nameEn: "Star apple",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 67,
    protein: 0.9,
    carbs: 16.2,
    fat: 0.4,
    sugars: 14.7,
    fiber: 3.3,
    water: 80.0,
    sodium: 10,
    potassium: 212,
    calcium: 14,
    iron: 0.5,
    phosphorus: 26,
    magnesium: 20,
    zinc: 0.3,
    vitaminA: 0,
    vitaminC: 14.0,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.05,
    vitaminB2: 0.05,
    vitaminB6: 0.08,
    folate: 12,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1/2 quả (~100g)",
    notes: "Nhiều xơ hòa tan.",
    diabetes: { glycemicIndex: 48, glycemicLoad: 8, carbPerPortion: 16 },
    kidney: { potassium: 212, phosphorus: 26 },
  },
  {
    id: "chom-chom",
    name: "Chôm chôm",
    nameEn: "Rambutan",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 68,
    protein: 0.9,
    carbs: 16.5,
    fat: 0.2,
    sugars: 13.0,
    fiber: 0.9,
    water: 82.0,
    sodium: 11,
    potassium: 42,
    calcium: 22,
    iron: 0.4,
    phosphorus: 16,
    magnesium: 10,
    zinc: 0.1,
    vitaminA: 0,
    vitaminC: 4.9,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.02,
    vitaminB2: 0.04,
    vitaminB6: 0.06,
    folate: 8,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "5–6 quả (~100g)",
    notes: "Ngọt; ĐTĐ ăn vừa.",
    diabetes: { glycemicIndex: 55, glycemicLoad: 9, carbPerPortion: 17 },
    kidney: { potassium: 42, phosphorus: 16 },
  },
  {
    id: "nhan",
    name: "Nhãn",
    nameEn: "Longan",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 60,
    protein: 1.3,
    carbs: 15.1,
    fat: 0.1,
    sugars: 13.0,
    fiber: 1.1,
    water: 83.0,
    sodium: 0,
    potassium: 266,
    calcium: 1,
    iron: 0.1,
    phosphorus: 21,
    magnesium: 10,
    zinc: 0.1,
    vitaminA: 0,
    vitaminC: 84.0,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.03,
    vitaminB2: 0.14,
    vitaminB6: 0.10,
    folate: 14,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "10–12 quả (~100g)",
    notes: "Đường cao.",
    diabetes: { glycemicIndex: 60, glycemicLoad: 9, carbPerPortion: 15 },
    kidney: { potassium: 266, phosphorus: 21 },
  },
  // ========================================================================
  // Bổ sung nhóm rau lá, củ, trái cây phổ biến (phần 38–40)
  // ========================================================================
  {
    id: "cai-thia-veg25",
    name: "Rau cải thìa",
    nameEn: "Bok choy",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 13,
    protein: 1.5,
    carbs: 2.2,
    fat: 0.2,
    fiber: 1.0,
    water: 95.0,
    sodium: 45,
    potassium: 252,
    calcium: 105,
    iron: 0.8,
    phosphorus: 37,
    magnesium: 19,
    zinc: 0.3,
    vitaminA: 2230,
    vitaminC: 45.0,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.04,
    vitaminB2: 0.07,
    vitaminB6: 0.09,
    folate: 66,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 bát (~100g)",
    notes: "Ít kcal; giàu canxi.",
    kidney: { potassium: 252, phosphorus: 37 },
  },
  {
    id: "cai-be-xanh",
    name: "Rau cải bẹ xanh",
    nameEn: "Mustard greens",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 27,
    protein: 2.9,
    carbs: 4.7,
    fat: 0.4,
    fiber: 2.0,
    water: 92.0,
    sodium: 20,
    potassium: 384,
    calcium: 115,
    iron: 1.6,
    phosphorus: 58,
    magnesium: 27,
    zinc: 0.5,
    vitaminA: 1510,
    vitaminC: 70.0,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.08,
    vitaminB2: 0.15,
    vitaminB6: 0.14,
    folate: 75,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 bát (~100g)",
    notes: "Giàu kali; CKD chú ý.",
    kidney: { potassium: 384, phosphorus: 58 },
  },
  {
    id: "xa-lach",
    name: "Rau xà lách",
    nameEn: "Lettuce",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    sugars: 0.8,
    fiber: 1.3,
    water: 95.0,
    sodium: 28,
    potassium: 194,
    calcium: 36,
    iron: 0.9,
    phosphorus: 29,
    magnesium: 13,
    zinc: 0.2,
    vitaminA: 740,
    vitaminC: 9.2,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.07,
    vitaminB2: 0.08,
    vitaminB6: 0.09,
    folate: 38,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "Ăn sống",
    notes: "Ít năng lượng.",
    diabetes: { glycemicIndex: 15, glycemicLoad: 1, carbPerPortion: 3 },
    kidney: { potassium: 194, phosphorus: 29 },
  },
  {
    id: "tia-to",
    name: "Tía tô",
    nameEn: "Perilla leaves",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 34,
    protein: 3.9,
    carbs: 6.1,
    fat: 0.8,
    fiber: 2.8,
    water: 87.0,
    sodium: 4,
    potassium: 500,
    calcium: 224,
    iron: 3.1,
    phosphorus: 63,
    magnesium: 55,
    zinc: 0.9,
    vitaminA: 5200,
    vitaminC: 43.0,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.10,
    vitaminB2: 0.15,
    vitaminB6: 0.20,
    folate: 100,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "Ăn kèm",
    notes: "Rau gia vị, giàu vi chất.",
    kidney: { potassium: 500, phosphorus: 63 },
  },
  {
    id: "khoai-lang-veg29",
    name: "Khoai lang",
    nameEn: "Sweet potato",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    sugars: 4.2,
    fiber: 3.0,
    water: 77.0,
    sodium: 55,
    potassium: 337,
    calcium: 30,
    iron: 0.6,
    phosphorus: 47,
    magnesium: 25,
    zinc: 0.3,
    vitaminA: 14187,
    vitaminC: 2.4,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.08,
    vitaminB2: 0.06,
    vitaminB6: 0.21,
    folate: 11,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 củ (~100g)",
    notes: "Tinh bột; GI trung bình.",
    diabetes: { glycemicIndex: 44, glycemicLoad: 9, carbPerPortion: 20 },
    kidney: { potassium: 337, phosphorus: 47 },
  },
  {
    id: "khoai-mon",
    name: "Khoai môn",
    nameEn: "Taro root",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 112,
    protein: 1.5,
    carbs: 26.5,
    fat: 0.2,
    sugars: 0.4,
    fiber: 4.1,
    water: 70.0,
    sodium: 11,
    potassium: 591,
    calcium: 43,
    iron: 0.6,
    phosphorus: 84,
    magnesium: 33,
    zinc: 0.5,
    vitaminA: 76,
    vitaminC: 4.5,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.10,
    vitaminB2: 0.03,
    vitaminB6: 0.27,
    folate: 22,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 miếng (~100g)",
    notes: "Kali cao; CKD hạn chế.",
    diabetes: { glycemicIndex: 54, glycemicLoad: 14, carbPerPortion: 27 },
    kidney: { potassium: 591, phosphorus: 84 },
  },
  {
    id: "bap-ngo",
    name: "Bắp (ngô)",
    nameEn: "Corn",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 96,
    protein: 3.4,
    carbs: 21.0,
    fat: 1.5,
    sugars: 4.5,
    fiber: 2.4,
    water: 73.0,
    sodium: 15,
    potassium: 270,
    calcium: 2,
    iron: 0.5,
    phosphorus: 89,
    magnesium: 37,
    zinc: 0.5,
    vitaminA: 187,
    vitaminC: 6.8,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.20,
    vitaminB2: 0.10,
    vitaminB6: 0.16,
    folate: 42,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 trái nhỏ (~100g)",
    notes: "Tinh bột; ĐTĐ ăn vừa.",
    diabetes: { glycemicIndex: 52, glycemicLoad: 11, carbPerPortion: 21 },
    kidney: { potassium: 270, phosphorus: 89 },
  },
  {
    id: "xoai-chin-fr18",
    name: "Xoài chín",
    nameEn: "Ripe mango",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 60,
    protein: 0.8,
    carbs: 15.0,
    fat: 0.4,
    sugars: 13.7,
    fiber: 1.6,
    water: 83.0,
    sodium: 1,
    potassium: 168,
    calcium: 11,
    iron: 0.2,
    phosphorus: 14,
    magnesium: 10,
    zinc: 0.1,
    vitaminA: 1082,
    vitaminC: 36.4,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.03,
    vitaminB2: 0.04,
    vitaminB6: 0.12,
    folate: 43,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 miếng (~100g)",
    notes: "Ngọt; ĐTĐ ăn vừa.",
    diabetes: { glycemicIndex: 51, glycemicLoad: 8, carbPerPortion: 15 },
    kidney: { potassium: 168, phosphorus: 14 },
  },
  {
    id: "xoai-xanh",
    name: "Xoài xanh",
    nameEn: "Green mango",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 38,
    protein: 0.6,
    carbs: 9.0,
    fat: 0.2,
    sugars: 6.0,
    fiber: 1.8,
    water: 88.0,
    sodium: 2,
    potassium: 156,
    calcium: 14,
    iron: 0.2,
    phosphorus: 16,
    magnesium: 11,
    zinc: 0.1,
    vitaminA: 540,
    vitaminC: 27.7,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.04,
    vitaminB2: 0.05,
    vitaminB6: 0.10,
    folate: 38,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "Ăn sống",
    notes: "Chua; GI thấp.",
    diabetes: { glycemicIndex: 35, glycemicLoad: 3, carbPerPortion: 9 },
    kidney: { potassium: 156, phosphorus: 16 },
  },
  {
    id: "dua-hau-fr20",
    name: "Dưa hấu",
    nameEn: "Watermelon",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    sugars: 6.2,
    fiber: 0.4,
    water: 91.0,
    sodium: 2,
    potassium: 112,
    calcium: 7,
    iron: 0.2,
    phosphorus: 11,
    magnesium: 10,
    zinc: 0.1,
    vitaminA: 569,
    vitaminC: 8.1,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.03,
    vitaminB2: 0.02,
    vitaminB6: 0.05,
    folate: 3,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1 miếng (~100g)",
    notes: "Nhiều nước; GI cao.",
    diabetes: { glycemicIndex: 72, glycemicLoad: 5, carbPerPortion: 8 },
    kidney: { potassium: 112, phosphorus: 11 },
  },
  {
    id: "thanh-long-fr21",
    name: "Thanh long",
    nameEn: "Dragon fruit",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 50,
    protein: 1.1,
    carbs: 11.0,
    fat: 0.4,
    sugars: 8.0,
    fiber: 3.0,
    water: 85.0,
    sodium: 1,
    potassium: 277,
    calcium: 18,
    iron: 0.6,
    phosphorus: 36,
    magnesium: 40,
    zinc: 0.4,
    vitaminA: 5,
    vitaminC: 2.5,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 0 },
    vitaminB1: 0.04,
    vitaminB2: 0.05,
    vitaminB6: 0.08,
    folate: 7,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1/2 quả (~100g)",
    notes: "Nhiều xơ; tốt tiêu hóa.",
    diabetes: { glycemicIndex: 48, glycemicLoad: 5, carbPerPortion: 11 },
    kidney: { potassium: 277, phosphorus: 36 },
  },
  {
    id: "bo",
    name: "Bơ",
    nameEn: "Avocado",
    category: "fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    sugars: 0.7,
    fiber: 6.7,
    water: 73.0,
    sodium: 7,
    potassium: 485,
    calcium: 12,
    iron: 0.6,
    phosphorus: 52,
    magnesium: 29,
    zinc: 0.6,
    vitaminA: 146,
    vitaminC: 10.0,
    cholesterol: 0,
    cardiovascular: { cholesterol: 0, saturatedFat: 2.1 },
    vitaminB1: 0.07,
    vitaminB2: 0.13,
    vitaminB6: 0.26,
    folate: 81,
    vitaminB12: 0,
    vitaminD: 0,
    commonServing: "1/2 quả (~100g)",
    notes: "Giàu chất béo tốt; kali cao.",
    diabetes: { glycemicIndex: 15, glycemicLoad: 1, carbPerPortion: 9 },
    kidney: { potassium: 485, phosphorus: 52 },
  },
];

/**
 * Get food by ID with extended information
 */
export function getExtendedFoodById(id: string): ExtendedFoodItem | undefined {
  return extendedFoodDatabase.find((food) => food.id === id);
}

/**
 * Search foods with extended information
 */
export function searchExtendedFoods(query: string): ExtendedFoodItem[] {
  if (!query.trim()) return [];

  const lowerQuery = query.toLowerCase();
  return extendedFoodDatabase.filter(
    (food) =>
      food.name.toLowerCase().includes(lowerQuery) ||
      food.nameEn?.toLowerCase().includes(lowerQuery)
  );
}

/**
 * Get foods by disease compatibility
 */
export function getFoodsByDisease(
  disease: 'diabetes' | 'gout' | 'kidney' | 'hypertension' | 'cardiovascular',
  level: 'good' | 'moderate' | 'avoid' = 'good'
): ExtendedFoodItem[] {
  return extendedFoodDatabase.filter((food) => {
    switch (disease) {
      case 'diabetes':
        if (!food.diabetes) return false;
        if (level === 'good') return (food.diabetes.glycemicIndex || 100) < 55;
        if (level === 'moderate') {
          const gi = food.diabetes.glycemicIndex || 100;
          return gi >= 55 && gi < 70;
        }
        return (food.diabetes.glycemicIndex || 0) >= 70;
        
      case 'gout':
        if (!food.gout) return false;
        if (level === 'good') return food.gout.purineLevel === 'low';
        if (level === 'moderate') return food.gout.purineLevel === 'medium';
        return food.gout.purineLevel === 'high' || food.gout.purineLevel === 'very-high';
        
      case 'kidney':
        if (!food.kidney) return false;
        if (level === 'good') return food.kidney.potassium < 200 && food.kidney.phosphorus < 200;
        if (level === 'moderate') {
          return (food.kidney.potassium >= 200 && food.kidney.potassium < 300) ||
                 (food.kidney.phosphorus >= 200 && food.kidney.phosphorus < 300);
        }
        return food.kidney.potassium >= 300 || food.kidney.phosphorus >= 300;
        
      case 'hypertension':
        if (!food.sodium) return level === 'good';
        if (level === 'good') return food.sodium < 100;
        if (level === 'moderate') return food.sodium >= 100 && food.sodium < 500;
        return food.sodium >= 500;
        
      case 'cardiovascular':
        if (!food.cardiovascular) return level === 'good';
        if (level === 'good') {
          return food.cardiovascular.cholesterol < 100 && food.cardiovascular.saturatedFat < 5;
        }
        if (level === 'moderate') {
          return (food.cardiovascular.cholesterol >= 100 && food.cardiovascular.cholesterol < 200) ||
                 (food.cardiovascular.saturatedFat >= 5 && food.cardiovascular.saturatedFat < 10);
        }
        return food.cardiovascular.cholesterol >= 200 || food.cardiovascular.saturatedFat >= 10;
        
      default:
        return false;
    }
  });
}
