/**
 * Article Metadata System
 * 
 * Centralized system for managing article metadata, including:
 * - Article information (title, description, category, tags)
 * - Related articles
 * - Tool links
 * - Search and navigation support
 */

export type ArticleLevel = 'foundation' | 'intermediate' | 'advanced';
export type TargetAudience = 'professional' | 'general' | 'both';
export type ArticleCategory = 
  | 'clinical-foundations'
  | 'chronic-diseases'
  | 'vitamins-minerals'
  | 'daily-practices'
  | 'life-stages'
  | 'special-topics'
  | 'general-nutrition';

export interface ArticleMetadata {
  slug: string;
  title: string;
  description: string;
  category: ArticleCategory;
  tags: string[];
  relatedArticles: string[]; // slugs of related articles
  toolLinks?: string[]; // tool slugs
  level: ArticleLevel;
  targetAudience: TargetAudience;
  href: string; // full path to article
  icon?: string; // lucide-react icon name
}

/**
 * All article metadata
 * This should be kept in sync with actual articles
 */
export const articles: ArticleMetadata[] = [
  // Clinical Foundations
  {
    slug: 'myths-in-clinical-nutrition',
    title: 'Hiểu lầm & Quan niệm Sai trong Dinh dưỡng lâm sàng',
    description: 'Điều chỉnh dựa trên bằng chứng cho các hiểu lầm phổ biến',
    category: 'clinical-foundations',
    tags: ['myths', 'misconceptions', 'clinical', 'evidence-based'],
    relatedArticles: ['assessment-process', 'needs-estimation', 'why-intake-falls-short'],
    level: 'foundation',
    targetAudience: 'professional',
    href: '/knowledge/myths-in-clinical-nutrition',
  },
  {
    slug: 'assessment-process',
    title: 'Quy trình Đánh giá Dinh dưỡng lâm sàng',
    description: 'Hướng dẫn đầy đủ về đánh giá dinh dưỡng lâm sàng',
    category: 'clinical-foundations',
    tags: ['assessment', 'screening', 'evaluation', 'clinical'],
    relatedArticles: ['nutrition-assessment-overview', 'needs-estimation', 'intake-assessment'],
    toolLinks: ['malnutrition-screening', 'energy-protein-calculator', 'intake-assessment'],
    level: 'foundation',
    targetAudience: 'professional',
    href: '/knowledge/assessment-process',
  },
  {
    slug: 'needs-estimation',
    title: 'Ước tính Nhu cầu Dinh dưỡng',
    description: 'Vì sao khoảng quan trọng hơn số chính xác',
    category: 'clinical-foundations',
    tags: ['needs', 'estimation', 'calculation', 'requirements'],
    relatedArticles: ['assessment-process', 'why-intake-falls-short', 'intake-assessment'],
    toolLinks: ['energy-protein-calculator'],
    level: 'foundation',
    targetAudience: 'professional',
    href: '/knowledge/needs-estimation',
  },
  {
    slug: 'intake-assessment',
    title: 'Đánh giá Lượng Ăn',
    description: 'Hiểu người bệnh thực sự nhận được gì',
    category: 'clinical-foundations',
    tags: ['intake', 'assessment', 'consumption', 'evaluation'],
    relatedArticles: ['assessment-process', 'why-intake-falls-short', 'needs-estimation'],
    toolLinks: ['intake-assessment'],
    level: 'foundation',
    targetAudience: 'professional',
    href: '/knowledge/intake-assessment',
  },
  {
    slug: 'why-intake-falls-short',
    title: 'Vì sao Lượng Ăn Thường Thiếu',
    description: 'Các yếu tố thực tế tạo ra khoảng cách',
    category: 'clinical-foundations',
    tags: ['intake', 'gaps', 'barriers', 'clinical'],
    relatedArticles: ['intake-assessment', 'needs-estimation', 'assessment-process'],
    level: 'foundation',
    targetAudience: 'professional',
    href: '/knowledge/why-intake-falls-short',
  },

  // General Nutrition
  {
    slug: 'calories-energy',
    title: 'Hiểu về Calo và năng lượng',
    description: 'Giải thích calo, TDEE, BMR với ví dụ thực tế. Hiểu về năng lượng trong thực phẩm',
    category: 'general-nutrition',
    tags: ['calories', 'energy', 'TDEE', 'BMR', 'metabolism', 'weight-management'],
    relatedArticles: ['macronutrients-overview', 'healthy-weight-management', 'meal-planning'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/calories-energy',
  },
  {
    slug: 'healthy-plate',
    title: 'Cân bằng Bữa ăn: Đĩa ăn lành mạnh',
    description: 'Hướng dẫn cách cân bằng bữa ăn với đĩa ăn lành mạnh. Visual guide với color coding',
    category: 'general-nutrition',
    tags: ['healthy-plate', 'meal-balance', 'nutrition', 'meal-planning'],
    relatedArticles: ['macronutrients-overview', 'meal-planning', 'portion-sizes'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/healthy-plate',
  },
  {
    slug: 'protein-sources-needs',
    title: 'Protein: Nguồn và Nhu cầu',
    description: 'Hiểu về protein - nguồn protein tốt, nhu cầu, và ví dụ thực tế',
    category: 'general-nutrition',
    tags: ['protein', 'sources', 'needs', 'meat', 'fish', 'beans'],
    relatedArticles: ['macronutrients-overview', 'healthy-plate', 'portion-sizes', 'dinh-duong-cho-nguoi-cao-tuoi'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/protein-sources-needs',
  },
  {
    slug: 'macronutrients-overview',
    title: 'Tổng quan về các Chất Dinh dưỡng Đa lượng',
    description: 'Tổng quan về carbohydrate, protein, và chất béo',
    category: 'general-nutrition',
    tags: ['macronutrients', 'carbohydrates', 'protein', 'fats', 'basics'],
    relatedArticles: ['carbohydrates', 'dietary-fats', 'hydration', 'calories-energy'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/macronutrients-overview',
  },
  {
    slug: 'carbohydrates',
    title: 'Carbohydrate (Tinh bột và Đường)',
    description: 'Hiểu về carbohydrate - nguồn năng lượng chính',
    category: 'general-nutrition',
    tags: ['carbohydrates', 'sugar', 'energy', 'diabetes', 'glycemic-index'],
    relatedArticles: ['macronutrients-overview', 'glycemic-index-load', 'diabetes-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/carbohydrates',
  },
  {
    slug: 'dietary-fats',
    title: 'Chất béo trong Chế độ ăn',
    description: 'Hiểu các loại chất béo và ảnh hưởng sức khỏe',
    category: 'general-nutrition',
    tags: ['fats', 'cholesterol', 'heart-health', 'omega-3'],
    relatedArticles: ['macronutrients-overview', 'hypertension-nutrition', 'heart-failure-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/dietary-fats',
  },
  {
    slug: 'dietary-fiber',
    title: 'Chất xơ trong Dinh dưỡng lâm sàng',
    description: 'Hiểu về chất xơ hòa tan và không hòa tan, lợi ích sức khỏe',
    category: 'general-nutrition',
    tags: ['fiber', 'digestion', 'gut-health', 'diabetes'],
    relatedArticles: ['carbohydrates', 'diabetes-nutrition', 'dinh-duong-trong-tao-bon-man-tinh', 'gut-health-probiotics'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/dietary-fiber',
  },
  {
    slug: 'sodium-health',
    title: 'Natri (Muối) và Sức khỏe',
    description: 'Hiểu về natri trong chế độ ăn và cách giảm natri',
    category: 'general-nutrition',
    tags: ['sodium', 'salt', 'hypertension', 'heart-health'],
    relatedArticles: ['hypertension-nutrition', 'heart-failure-nutrition', 'ckd-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/sodium-health',
  },
  {
    slug: 'glycemic-index-load',
    title: 'Chỉ số Đường huyết (GI) và Tải lượng Đường huyết (GL)',
    description: 'Hiểu cách thực phẩm ảnh hưởng đến đường huyết',
    category: 'general-nutrition',
    tags: ['glycemic-index', 'diabetes', 'blood-sugar', 'carbohydrates'],
    relatedArticles: ['carbohydrates', 'diabetes-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/glycemic-index-load',
  },
  {
    slug: 'hydration',
    title: 'Hydration: Nước và Dịch',
    description: 'Hiểu về nhu cầu nước và hydration',
    category: 'general-nutrition',
    tags: ['hydration', 'water', 'fluids', 'health'],
    relatedArticles: ['ckd-nutrition', 'heart-failure-nutrition', 'dinh-duong-cho-nguoi-cao-tuoi'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/hydration',
  },

  // Chronic Diseases
  {
    slug: 'cardiovascular-disease-nutrition',
    title: 'Dinh dưỡng trong Bệnh Tim mạch',
    description: 'Hướng dẫn dinh dưỡng tổng quan cho bệnh tim mạch. Nguyên tắc dinh dưỡng lành mạnh cho tim',
    category: 'chronic-diseases',
    tags: ['cardiovascular', 'heart-health', 'cholesterol', 'blood-pressure'],
    relatedArticles: ['dinh-duong-sau-nhoi-mau-co-tim', 'hypertension-nutrition', 'heart-failure-nutrition', 'dietary-fats', 'sodium-health'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/cardiovascular-disease-nutrition',
  },
  {
    slug: 'dinh-duong-sau-nhoi-mau-co-tim',
    title: 'Dinh dưỡng sau Nhồi máu cơ tim',
    description: 'Hướng dẫn dinh dưỡng sau nhồi máu cơ tim - chất béo, muối, và phòng ngừa thứ phát. Dinh dưỡng + thuốc + vận động = bộ ba bắt buộc',
    category: 'chronic-diseases',
    tags: ['myocardial-infarction', 'nhồi-máu-cơ-tim', 'heart-attack', 'cardiovascular', 'cholesterol', 'secondary-prevention'],
    relatedArticles: ['cardiovascular-disease-nutrition', 'hypertension-nutrition', 'diabetes-nutrition', 'dyslipidemia-nutrition', 'healthy-weight-management'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/dinh-duong-sau-nhoi-mau-co-tim',
  },
  {
    slug: 'diabetes-nutrition',
    title: 'Dinh dưỡng Đái tháo đường',
    description: 'Hướng dẫn về carbohydrate counting, quản lý đường huyết',
    category: 'chronic-diseases',
    tags: ['diabetes', 'blood-sugar', 'carbohydrates', 'insulin'],
    relatedArticles: ['carbohydrates', 'glycemic-index-load', 'hypertension-nutrition', 'dinh-duong-sau-nhoi-mau-co-tim'],
    toolLinks: ['energy-protein-calculator'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/diabetes-nutrition',
  },
  {
    slug: 'hypertension-nutrition',
    title: 'Dinh dưỡng Tăng huyết áp',
    description: 'Hướng dẫn về DASH diet, quản lý natri và kali',
    category: 'chronic-diseases',
    tags: ['hypertension', 'blood-pressure', 'sodium', 'dash-diet'],
    relatedArticles: ['sodium-health', 'heart-failure-nutrition', 'dietary-fats', 'dinh-duong-sau-nhoi-mau-co-tim'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/hypertension-nutrition',
  },
  {
    slug: 'heart-failure-nutrition',
    title: 'Dinh dưỡng Suy tim',
    description: 'Hướng dẫn về quản lý natri, dịch, và cân nặng trong suy tim',
    category: 'chronic-diseases',
    tags: ['heart-failure', 'sodium', 'fluids', 'cardiac'],
    relatedArticles: ['hypertension-nutrition', 'sodium-health', 'hydration'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/heart-failure-nutrition',
  },
  {
    slug: 'ckd-nutrition',
    title: 'Dinh dưỡng Bệnh thận mạn (CKD)',
    description: 'Hướng dẫn dinh dưỡng trong bệnh thận mạn theo giai đoạn',
    category: 'chronic-diseases',
    tags: ['ckd', 'kidney', 'protein', 'phosphorus', 'potassium'],
    relatedArticles: ['dialysis-nutrition', 'sodium-health', 'hydration'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/ckd-nutrition',
  },
  {
    slug: 'dialysis-nutrition',
    title: 'Dinh dưỡng Lọc máu',
    description: 'Hướng dẫn dinh dưỡng cho bệnh nhân lọc máu',
    category: 'chronic-diseases',
    tags: ['dialysis', 'kidney', 'protein', 'phosphorus'],
    relatedArticles: ['ckd-nutrition'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/dialysis-nutrition',
  },
  {
    slug: 'liver-disease-nutrition',
    title: 'Dinh dưỡng Bệnh gan mạn',
    description: 'Hướng dẫn dinh dưỡng trong bệnh gan mạn',
    category: 'chronic-diseases',
    tags: ['liver', 'protein', 'sodium', 'ascites'],
    relatedArticles: ['dinh-duong-trong-gan-nhiem-mo', 'ckd-nutrition', 'sodium-health'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/liver-disease-nutrition',
  },
  {
    slug: 'dinh-duong-trong-gan-nhiem-mo',
    title: 'Dinh dưỡng trong Gan nhiễm mỡ',
    description: 'Hướng dẫn dinh dưỡng cho gan nhiễm mỡ - giảm mỡ gan, kiểm soát đường và mỡ máu. Gan nhiễm mỡ có thể đảo ngược nếu điều chỉnh dinh dưỡng và lối sống đúng',
    category: 'chronic-diseases',
    tags: ['fatty-liver', 'gan-nhiễm-mỡ', 'nafld', 'liver', 'metabolism', 'weight-management'],
    relatedArticles: ['liver-disease-nutrition', 'diabetes-nutrition', 'dyslipidemia-nutrition', 'healthy-weight-management'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/dinh-duong-trong-gan-nhiem-mo',
  },
  {
    slug: 'copd-nutrition',
    title: 'Dinh dưỡng COPD',
    description: 'Hướng dẫn dinh dưỡng trong bệnh phổi tắc nghẽn mạn tính',
    category: 'chronic-diseases',
    tags: ['copd', 'lungs', 'energy', 'breathing'],
    relatedArticles: ['cancer-nutrition'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/copd-nutrition',
  },
  {
    slug: 'cancer-nutrition',
    title: 'Dinh dưỡng Ung thư',
    description: 'Hướng dẫn tổng quan về dinh dưỡng trong ung thư',
    category: 'chronic-diseases',
    tags: ['cancer', 'oncology', 'protein', 'energy', 'side-effects'],
    relatedArticles: ['copd-nutrition'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/cancer-nutrition',
  },
  {
    slug: 'ibd-nutrition',
    title: 'Dinh dưỡng Bệnh viêm ruột (IBD)',
    description: 'Hướng dẫn dinh dưỡng trong Crohn và Ulcerative Colitis',
    category: 'chronic-diseases',
    tags: ['ibd', 'crohn', 'colitis', 'digestion', 'fiber'],
    relatedArticles: ['dinh-duong-trong-hoi-chung-ruot-kich-thich-ibs', 'dietary-fiber', 'gut-health-probiotics'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/ibd-nutrition',
  },
  {
    slug: 'dinh-duong-trong-hoi-chung-ruot-kich-thich-ibs',
    title: 'Dinh dưỡng trong Hội chứng Ruột kích thích (IBS)',
    description: 'Hướng dẫn dinh dưỡng cho Hội chứng Ruột kích thích (IBS) - FODMAP, chất xơ, và cách quản lý triệu chứng',
    category: 'chronic-diseases',
    tags: ['ibs', 'irritable-bowel-syndrome', 'fodmap', 'digestion', 'fiber', 'gut-health'],
    relatedArticles: ['ibd-nutrition', 'dinh-duong-trong-viem-loet-da-day-ta-trang', 'dinh-duong-trong-trao-nguoc-da-day-thuc-quan-gerd', 'dietary-fiber', 'gut-health-probiotics'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/dinh-duong-trong-hoi-chung-ruot-kich-thich-ibs',
  },
  {
    slug: 'dinh-duong-trong-viem-loet-da-day-ta-trang',
    title: 'Dinh dưỡng trong Viêm loét Dạ dày – Tá tràng',
    description: 'Hướng dẫn dinh dưỡng cho viêm loét dạ dày – tá tràng - cách ăn, thực phẩm nên ăn và tránh, hỗ trợ lành loét',
    category: 'chronic-diseases',
    tags: ['peptic-ulcer', 'gastric-ulcer', 'duodenal-ulcer', 'hp', 'helicobacter-pylori', 'digestion', 'stomach'],
    relatedArticles: ['dinh-duong-trong-hoi-chung-ruot-kich-thich-ibs', 'dinh-duong-trong-trao-nguoc-da-day-thuc-quan-gerd', 'nutrition-during-illness', 'nutrition-recovery'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/dinh-duong-trong-viem-loet-da-day-ta-trang',
  },
  {
    slug: 'dinh-duong-trong-trao-nguoc-da-day-thuc-quan-gerd',
    title: 'Dinh dưỡng trong Trào ngược dạ dày – Thực quản (GERD)',
    description: 'Hướng dẫn dinh dưỡng cho trào ngược dạ dày – thực quản (GERD) - thời điểm ăn, cách ăn, và thực phẩm nên ăn/tránh',
    category: 'chronic-diseases',
    tags: ['gerd', 'gastroesophageal-reflux', 'acid-reflux', 'heartburn', 'digestion', 'stomach', 'esophagus'],
    relatedArticles: ['dinh-duong-trong-viem-loet-da-day-ta-trang', 'dinh-duong-trong-hoi-chung-ruot-kich-thich-ibs', 'nutrition-during-illness'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/dinh-duong-trong-trao-nguoc-da-day-thuc-quan-gerd',
  },
  {
    slug: 'dinh-duong-trong-tao-bon-man-tinh',
    title: 'Dinh dưỡng trong Táo bón mạn tính',
    description: 'Hướng dẫn dinh dưỡng cho táo bón mạn tính - chất xơ, nước, vận động, và thói quen đi tiêu. Táo bón = xơ + nước + vận động + thói quen',
    category: 'chronic-diseases',
    tags: ['constipation', 'táo-bón', 'fiber', 'digestion', 'bowel-health', 'hydration'],
    relatedArticles: ['dietary-fiber', 'dinh-duong-trong-hoi-chung-ruot-kich-thich-ibs', 'dinh-duong-trong-tieu-chay-man-tinh', 'hydration', 'dinh-duong-cho-nguoi-cao-tuoi'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/dinh-duong-trong-tao-bon-man-tinh',
  },
  {
    slug: 'dinh-duong-trong-tieu-chay-man-tinh',
    title: 'Dinh dưỡng trong Tiêu chảy mạn tính / Tiêu chảy chức năng',
    description: 'Hướng dẫn dinh dưỡng cho tiêu chảy mạn tính - ăn đúng loại, đúng lượng, đúng thời điểm. Tiêu chảy mạn cần ăn đúng - không nhịn',
    category: 'chronic-diseases',
    tags: ['diarrhea', 'tiêu-chảy', 'chronic-diarrhea', 'ibs-d', 'digestion', 'bowel-health', 'lactose-intolerance'],
    relatedArticles: ['dinh-duong-trong-hoi-chung-ruot-kich-thich-ibs', 'dinh-duong-trong-tao-bon-man-tinh', 'dietary-fiber', 'hydration', 'nutrition-during-illness'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/dinh-duong-trong-tieu-chay-man-tinh',
  },
  {
    slug: 'dyslipidemia-nutrition',
    title: 'Dinh dưỡng Rối loạn Lipid máu',
    description: 'Hướng dẫn về quản lý chất béo, cholesterol, và triglycerides',
    category: 'chronic-diseases',
    tags: ['cholesterol', 'lipids', 'fats', 'heart-health'],
    relatedArticles: ['dietary-fats', 'heart-failure-nutrition', 'dinh-duong-sau-nhoi-mau-co-tim'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/dyslipidemia-nutrition',
  },
  {
    slug: 'dinh-duong-trong-benh-gut-va-tang-acid-uric',
    title: 'Dinh dưỡng trong Bệnh Gout',
    description: 'Hướng dẫn dinh dưỡng cho bệnh gout - purin, rượu bia, và cách kiểm soát. Gout là bệnh mạn, cần điều trị suốt đời. Dinh dưỡng giúp giảm cơn nhưng không thay thế thuốc hạ uric',
    category: 'chronic-diseases',
    tags: ['gout', 'gút', 'acid-uric', 'purin', 'arthritis', 'metabolism'],
    relatedArticles: ['ckd-nutrition', 'dyslipidemia-nutrition', 'diabetes-nutrition', 'healthy-weight-management'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/dinh-duong-trong-benh-gut-va-tang-acid-uric',
  },
  {
    slug: 'dinh-duong-trong-loang-xuong',
    title: 'Dinh dưỡng trong Loãng xương',
    description: 'Hướng dẫn dinh dưỡng cho loãng xương - canxi, vitamin D, protein, và cách phòng ngừa. Loãng xương cần dinh dưỡng + thuốc + vận động + phòng té ngã',
    category: 'chronic-diseases',
    tags: ['osteoporosis', 'loãng-xương', 'bone-health', 'calcium', 'vitamin-d', 'protein'],
    relatedArticles: ['calcium-bone-health', 'vitamin-d', 'protein-sources-needs', 'magnesium-health', 'dinh-duong-cho-nguoi-cao-tuoi'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/dinh-duong-trong-loang-xuong',
  },
  {
    slug: 'dinh-duong-cho-nguoi-sau-dot-quy',
    title: 'Dinh dưỡng cho Người sau Đột quỵ',
    description: 'Hướng dẫn dinh dưỡng cho người sau đột quỵ - nuốt khó, năng lượng, protein, và phòng tái phát. Dinh dưỡng ảnh hưởng trực tiếp đến khả năng phục hồi',
    category: 'chronic-diseases',
    tags: ['stroke', 'đột-quỵ', 'tai-biến', 'dysphagia', 'nuốt-khó', 'recovery', 'rehabilitation'],
    relatedArticles: ['hypertension-nutrition', 'diabetes-nutrition', 'dyslipidemia-nutrition', 'nutrition-recovery', 'dinh-duong-cho-nguoi-cao-tuoi'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/dinh-duong-cho-nguoi-sau-dot-quy',
  },

  // Vitamins & Minerals
  {
    slug: 'vitamin-c-immunity',
    title: 'Vitamin C và Miễn dịch',
    description: 'Hiểu về vitamin C - vitamin quan trọng cho hệ miễn dịch, chữa lành vết thương',
    category: 'vitamins-minerals',
    tags: ['vitamin-c', 'immunity', 'ascorbic-acid', 'antioxidants'],
    relatedArticles: ['antioxidants-foods', 'iron-anemia'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/vitamin-c-immunity',
  },
  {
    slug: 'vitamin-a-eye-health',
    title: 'Vitamin A và Sức khỏe Mắt',
    description: 'Hiểu về vitamin A - vitamin quan trọng cho sức khỏe mắt, hệ miễn dịch, và da',
    category: 'vitamins-minerals',
    tags: ['vitamin-a', 'eye-health', 'beta-carotene', 'retinol'],
    relatedArticles: ['antioxidants-foods', 'pregnancy-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/vitamin-a-eye-health',
  },
  {
    slug: 'magnesium-health',
    title: 'Magnesium và Sức khỏe',
    description: 'Hiểu về magnesium - khoáng chất quan trọng cho cơ bắp, thần kinh, tim mạch, và xương',
    category: 'vitamins-minerals',
    tags: ['magnesium', 'muscles', 'nerves', 'heart-health', 'bones', 'sleep'],
    relatedArticles: ['calcium-bone-health', 'nutrition-sleep'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/magnesium-health',
  },
  {
    slug: 'folate-pregnancy',
    title: 'Folate và Phụ nữ Mang thai',
    description: 'Hiểu về folate (axit folic) - vitamin quan trọng cho phụ nữ mang thai. Ngăn ngừa dị tật ống thần kinh',
    category: 'vitamins-minerals',
    tags: ['folate', 'folic-acid', 'pregnancy', 'neural-tube-defects', 'B9'],
    relatedArticles: ['pregnancy-nutrition', 'iron-anemia'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/folate-pregnancy',
  },
  {
    slug: 'vitamin-k-blood-clotting',
    title: 'Vitamin K và Đông máu',
    description: 'Hiểu về vitamin K - vitamin quan trọng cho đông máu và sức khỏe xương',
    category: 'vitamins-minerals',
    tags: ['vitamin-k', 'blood-clotting', 'warfarin', 'bones'],
    relatedArticles: ['calcium-bone-health'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/vitamin-k-blood-clotting',
  },
  {
    slug: 'vitamin-d',
    title: 'Vitamin D và Sức khỏe Xương',
    description: 'Hiểu về vitamin D - vai trò quan trọng trong sức khỏe xương',
    category: 'vitamins-minerals',
    tags: ['vitamin-d', 'bone-health', 'calcium', 'sunlight'],
    relatedArticles: ['calcium-bone-health', 'dinh-duong-cho-nguoi-cao-tuoi'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/vitamin-d',
  },
  {
    slug: 'iron-anemia',
    title: 'Sắt và Thiếu máu',
    description: 'Hiểu về sắt - khoáng chất quan trọng để tạo máu',
    category: 'vitamins-minerals',
    tags: ['iron', 'anemia', 'blood', 'pregnancy'],
    relatedArticles: ['dinh-duong-trong-thieu-mau', 'pregnancy-nutrition', 'vitamin-b12-energy'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/iron-anemia',
  },
  {
    slug: 'dinh-duong-trong-thieu-mau',
    title: 'Dinh dưỡng trong Thiếu máu',
    description: 'Hướng dẫn dinh dưỡng cho thiếu máu - sắt, B12, folate, và cách tăng hấp thu. Thiếu máu = dinh dưỡng + tìm nguyên nhân + điều trị đúng',
    category: 'chronic-diseases',
    tags: ['anemia', 'thiếu-máu', 'iron', 'vitamin-b12', 'folate', 'hemoglobin'],
    relatedArticles: ['iron-anemia', 'vitamin-b12-energy', 'folate-pregnancy', 'protein-sources-needs', 'dinh-duong-cho-nguoi-cao-tuoi'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/dinh-duong-trong-thieu-mau',
  },
  {
    slug: 'calcium-bone-health',
    title: 'Canxi và Sức khỏe Xương',
    description: 'Hiểu về canxi - khoáng chất quan trọng nhất cho xương',
    category: 'vitamins-minerals',
    tags: ['calcium', 'bone-health', 'osteoporosis'],
    relatedArticles: ['vitamin-d', 'dinh-duong-cho-nguoi-cao-tuoi'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/calcium-bone-health',
  },
  {
    slug: 'vitamin-b12-energy',
    title: 'Vitamin B12 và năng lượng',
    description: 'Hiểu về vitamin B12 - vitamin quan trọng cho năng lượng',
    category: 'vitamins-minerals',
    tags: ['vitamin-b12', 'energy', 'anemia', 'vegan'],
    relatedArticles: ['iron-anemia'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/vitamin-b12-energy',
  },
  {
    slug: 'potassium-blood-pressure',
    title: 'Kali và Huyết áp',
    description: 'Hiểu về kali - khoáng chất quan trọng giúp kiểm soát huyết áp',
    category: 'vitamins-minerals',
    tags: ['potassium', 'blood-pressure', 'hypertension', 'ckd'],
    relatedArticles: ['hypertension-nutrition', 'ckd-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/potassium-blood-pressure',
  },
  {
    slug: 'zinc-immunity',
    title: 'Kẽm và Miễn dịch',
    description: 'Hiểu về kẽm - khoáng chất quan trọng cho hệ miễn dịch',
    category: 'vitamins-minerals',
    tags: ['zinc', 'immunity', 'wound-healing'],
    relatedArticles: [],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/zinc-immunity',
  },

  // Daily Practices
  {
    slug: 'reading-food-labels',
    title: 'Đọc Nhãn Thực phẩm',
    description: 'Hướng dẫn cách đọc và hiểu nhãn thực phẩm',
    category: 'daily-practices',
    tags: ['food-labels', 'nutrition-facts', 'shopping'],
    relatedArticles: ['sodium-health', 'carbohydrates', 'dietary-fats'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/daily-practices/reading-food-labels',
  },
  {
    slug: 'weekly-meal-planning',
    title: 'Lập Kế hoạch Bữa ăn Tuần',
    description: 'Hướng dẫn step-by-step cách lập kế hoạch bữa ăn cho cả tuần với templates',
    category: 'daily-practices',
    tags: ['weekly-meal-planning', 'meal-planning', 'organization', 'templates'],
    relatedArticles: ['meal-planning', 'meal-prep', 'nutrition-on-budget', 'healthy-plate'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/weekly-meal-planning',
  },
  {
    slug: 'meal-prep',
    title: 'Chuẩn bị Bữa ăn (Meal Prep)',
    description: 'Hướng dẫn cách chuẩn bị bữa ăn trước để tiết kiệm thời gian và ăn uống lành mạnh',
    category: 'daily-practices',
    tags: ['meal-prep', 'meal-preparation', 'time-saving', 'preparation'],
    relatedArticles: ['weekly-meal-planning', 'meal-planning', 'healthy-cooking-methods'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/meal-prep',
  },
  {
    slug: 'portion-sizes',
    title: 'Hiểu về Portion Sizes (Khẩu phần)',
    description: 'Hướng dẫn cách ước lượng khẩu phần đúng với visual guide và comparisons',
    category: 'daily-practices',
    tags: ['portion-sizes', 'serving-size', 'measurement', 'hand-guide'],
    relatedArticles: ['healthy-plate', 'reading-food-labels', 'calories-energy', 'healthy-weight-management'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/portion-sizes',
  },
  {
    slug: 'meal-planning',
    title: 'Lập Kế hoạch Bữa ăn',
    description: 'Hướng dẫn cách lập kế hoạch bữa ăn đơn giản, thực tế',
    category: 'daily-practices',
    tags: ['meal-planning', 'meal-prep', 'organization'],
    relatedArticles: ['healthy-cooking-methods', 'nutrition-on-budget', 'weekly-meal-planning'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/daily-practices/meal-planning',
  },
  {
    slug: 'healthy-cooking-methods',
    title: 'Phương pháp Nấu ăn lành mạnh',
    description: 'Hướng dẫn các phương pháp nấu ăn lành mạnh',
    category: 'daily-practices',
    tags: ['cooking', 'preparation', 'healthy'],
    relatedArticles: ['meal-planning', 'dietary-fats'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/daily-practices/healthy-cooking-methods',
  },
  {
    slug: 'eating-out-healthy',
    title: 'Ăn uống lành mạnh khi Đi ăn Ngoài',
    description: 'Hướng dẫn cách chọn lựa thực phẩm lành mạnh khi đi ăn ngoài',
    category: 'daily-practices',
    tags: ['eating-out', 'restaurants', 'healthy-choices'],
    relatedArticles: ['meal-planning', 'reading-food-labels'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/daily-practices/eating-out-healthy',
  },
  {
    slug: 'smart-snacking',
    title: 'Snacking Thông minh',
    description: 'Hướng dẫn cách snack thông minh',
    category: 'daily-practices',
    tags: ['snacking', 'snacks', 'healthy'],
    relatedArticles: ['meal-planning', 'nutrition-on-budget'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/daily-practices/smart-snacking',
  },
  {
    slug: 'nutrition-on-budget',
    title: 'Dinh dưỡng với Ngân sách Hạn hẹp',
    description: 'Hướng dẫn cách ăn uống lành mạnh với ngân sách hạn hẹp',
    category: 'daily-practices',
    tags: ['budget', 'affordable', 'shopping'],
    relatedArticles: ['meal-planning', 'smart-snacking', 'weekly-meal-planning'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/daily-practices/nutrition-on-budget',
  },
  {
    slug: 'nutrition-busy-lifestyle',
    title: 'Dinh dưỡng cho Người Bận rộn',
    description: 'Quick tips và hướng dẫn dinh dưỡng cho người có lối sống bận rộn',
    category: 'daily-practices',
    tags: ['busy-lifestyle', 'time-saving', 'quick-meals', 'convenience'],
    relatedArticles: ['weekly-meal-planning', 'meal-prep', 'smart-snacking'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/nutrition-busy-lifestyle',
  },
  {
    slug: 'nutrition-travel',
    title: 'Dinh dưỡng khi Đi Du lịch',
    description: 'Practical tips về dinh dưỡng khi đi du lịch. Cách ăn uống lành mạnh khi đi máy bay, ở khách sạn',
    category: 'daily-practices',
    tags: ['travel', 'nutrition-travel', 'eating-out', 'healthy-travel'],
    relatedArticles: ['eating-out-healthy', 'nutrition-busy-lifestyle'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/nutrition-travel',
  },

  // Life Stages
  {
    slug: 'infant-nutrition',
    title: 'Dinh dưỡng cho Trẻ sơ sinh (0-12 tháng)',
    description: 'Hướng dẫn dinh dưỡng cho trẻ sơ sinh từ 0-12 tháng. Sữa mẹ, sữa công thức, và bắt đầu ăn dặm',
    category: 'life-stages',
    tags: ['infant', 'baby', 'breastfeeding', 'formula', 'weaning'],
    relatedArticles: ['pregnancy-nutrition', 'breastfeeding-nutrition', 'children-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/infant-nutrition',
  },
  {
    slug: 'breastfeeding-nutrition',
    title: 'Dinh dưỡng cho Phụ nữ Cho con bú',
    description: 'Hướng dẫn dinh dưỡng cho phụ nữ cho con bú. Nhu cầu dinh dưỡng tăng, thực phẩm quan trọng',
    category: 'life-stages',
    tags: ['breastfeeding', 'lactation', 'postpartum', 'nutrition'],
    relatedArticles: ['pregnancy-nutrition', 'infant-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/breastfeeding-nutrition',
  },
  {
    slug: 'pregnancy-nutrition',
    title: 'Dinh dưỡng cho Phụ nữ Mang thai',
    description: 'Hướng dẫn dinh dưỡng cho phụ nữ mang thai',
    category: 'life-stages',
    tags: ['pregnancy', 'prenatal', 'folate', 'iron'],
    relatedArticles: ['iron-anemia', 'calcium-bone-health', 'folate-pregnancy', 'breastfeeding-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/life-stages/pregnancy-nutrition',
  },
  {
    slug: 'children-nutrition',
    title: 'Dinh dưỡng cho Trẻ em và Thanh thiếu niên',
    description: 'Hướng dẫn dinh dưỡng cho trẻ em và thanh thiếu niên',
    category: 'life-stages',
    tags: ['children', 'teens', 'growth', 'development'],
    relatedArticles: ['pregnancy-nutrition', 'dinh-duong-cho-nguoi-cao-tuoi', 'infant-nutrition', 'teen-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/life-stages/children-nutrition',
  },
  {
    slug: 'teen-nutrition',
    title: 'Dinh dưỡng cho Thanh thiếu niên',
    description: 'Hướng dẫn dinh dưỡng cho thanh thiếu niên (13-18 tuổi). Nhu cầu tăng trưởng, năng lượng, protein',
    category: 'life-stages',
    tags: ['teen', 'adolescent', 'growth', 'puberty', 'development'],
    relatedArticles: ['children-nutrition', 'exercise-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/teen-nutrition',
  },
  {
    slug: 'dinh-duong-cho-nguoi-cao-tuoi',
    title: 'Dinh dưỡng cho Người cao tuổi',
    description: 'Hướng dẫn dinh dưỡng cho người cao tuổi - protein, canxi, vitamin D, và cách phòng suy dinh dưỡng. Ăn đủ – ăn đúng – ăn đều – ăn an toàn',
    category: 'life-stages',
    tags: ['elderly', 'aging', 'protein', 'vitamin-d', 'sarcopenia', 'suy-dinh-duong', 'người-cao-tuổi'],
    relatedArticles: ['vitamin-d', 'calcium-bone-health', 'hydration', 'protein-sources-needs', 'dinh-duong-trong-tao-bon-man-tinh'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/dinh-duong-cho-nguoi-cao-tuoi',
  },

  // Special Topics
  {
    slug: 'exercise-nutrition',
    title: 'Dinh dưỡng cho Người Tập thể dục',
    description: 'Hướng dẫn dinh dưỡng cho người tập thể dục. Pre/post workout nutrition, nhu cầu protein, carbohydrate',
    category: 'special-topics',
    tags: ['exercise', 'workout', 'sports-nutrition', 'pre-workout', 'post-workout'],
    relatedArticles: ['protein-sources-needs', 'carbohydrates', 'hydration'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/exercise-nutrition',
  },
  {
    slug: 'intermittent-fasting',
    title: 'Intermittent Fasting: Hiểu đúng',
    description: 'Hướng dẫn về intermittent fasting (nhịn ăn gián đoạn) - các phương pháp, lợi ích, rủi ro',
    category: 'special-topics',
    tags: ['intermittent-fasting', 'IF', 'fasting', 'weight-loss'],
    relatedArticles: ['healthy-weight-management', 'calories-energy'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/intermittent-fasting',
  },
  {
    slug: 'plant-based-diet',
    title: 'Plant-based Diet: Hướng dẫn',
    description: 'Hướng dẫn về chế độ ăn dựa trên thực vật (plant-based diet). Lợi ích, thách thức, và cách đảm bảo đủ dinh dưỡng',
    category: 'special-topics',
    tags: ['plant-based', 'vegetarian', 'vegan', 'protein-thực-vật'],
    relatedArticles: ['protein-sources-needs', 'vitamin-b12-energy', 'iron-anemia'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/plant-based-diet',
  },
  {
    slug: 'nutrition-sleep',
    title: 'Dinh dưỡng và Giấc ngủ',
    description: 'Mối liên hệ giữa dinh dưỡng và giấc ngủ. Thực phẩm giúp ngủ tốt, thực phẩm nên tránh trước khi ngủ',
    category: 'special-topics',
    tags: ['nutrition-sleep', 'sleep', 'insomnia', 'melatonin', 'tryptophan'],
    relatedArticles: ['magnesium-health'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/nutrition-sleep',
  },
  {
    slug: 'nutrition-stress',
    title: 'Dinh dưỡng và Stress',
    description: 'Mối liên hệ giữa dinh dưỡng và stress. Thực phẩm giúp giảm stress, thực phẩm nên tránh',
    category: 'special-topics',
    tags: ['nutrition-stress', 'stress', 'anxiety', 'food-mood'],
    relatedArticles: ['nutrition-sleep', 'magnesium-health'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/nutrition-stress',
  },
  {
    slug: 'gut-health-probiotics',
    title: 'Sức khỏe Đường ruột và Probiotics',
    description: 'Hiểu về sức khỏe đường ruột, probiotics, và prebiotics',
    category: 'special-topics',
    tags: ['gut-health', 'probiotics', 'prebiotics', 'digestion'],
    relatedArticles: ['dietary-fiber', 'ibd-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/special-topics/gut-health-probiotics',
  },
  {
    slug: 'omega-3-heart-health',
    title: 'Omega-3 và Sức khỏe Tim mạch',
    description: 'Hiểu về omega-3 - chất béo tốt quan trọng cho tim mạch',
    category: 'special-topics',
    tags: ['omega-3', 'heart-health', 'fish', 'fats'],
    relatedArticles: ['dietary-fats', 'heart-failure-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/special-topics/omega-3-heart-health',
  },
  {
    slug: 'healthy-weight-management',
    title: 'Quản lý Cân nặng lành mạnh',
    description: 'Hướng dẫn cách quản lý cân nặng lành mạnh',
    category: 'special-topics',
    tags: ['weight-management', 'weight-loss', 'calories'],
    relatedArticles: ['macronutrients-overview', 'meal-planning'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/special-topics/healthy-weight-management',
  },
  {
    slug: 'nutrition-myths-public',
    title: 'Hiểu lầm Dinh dưỡng Phổ biến',
    description: 'Điều chỉnh các hiểu lầm dinh dưỡng phổ biến trong công chúng',
    category: 'special-topics',
    tags: ['myths', 'misconceptions', 'public'],
    relatedArticles: ['myths-in-clinical-nutrition'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/special-topics/nutrition-myths-public',
  },
  {
    slug: 'antioxidants-foods',
    title: 'Chất chống Oxy hóa trong Thực phẩm',
    description: 'Hiểu về chất chống oxy hóa - hợp chất tự nhiên trong thực phẩm',
    category: 'special-topics',
    tags: ['antioxidants', 'vitamins', 'health'],
    relatedArticles: ['vitamin-c-immunity', 'vitamin-a-eye-health'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/special-topics/antioxidants-foods',
  },

  // Vietnamese Foods & Practices
  {
    slug: 'vietnamese-foods-nutrition',
    title: 'Thực phẩm Việt Nam: Nguồn Dinh dưỡng Tốt',
    description: 'Giới thiệu các thực phẩm Việt Nam giàu dinh dưỡng - rau củ, protein, carbohydrate, trái cây với ví dụ thực tế',
    category: 'general-nutrition',
    tags: ['vietnamese-food', 'local-foods', 'nutrition', 'rau-củ', 'thực-phẩm-việt-nam'],
    relatedArticles: ['protein-sources-needs', 'carbohydrates', 'macronutrients-overview', 'dietary-fiber'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vietnamese-foods-nutrition',
  },
  {
    slug: 'vietnamese-cooking-methods',
    title: 'Cách Nấu Ăn lành mạnh Kiểu Việt Nam',
    description: 'Hướng dẫn phương pháp nấu ăn truyền thống Việt Nam (luộc, hấp, kho, nướng, xào) và cách tối ưu dinh dưỡng',
    category: 'daily-practices',
    tags: ['cooking', 'vietnamese-cooking', 'phương-pháp-nấu', 'luộc', 'hấp', 'kho'],
    relatedArticles: ['healthy-cooking-methods', 'sodium-health', 'dietary-fats'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/vietnamese-cooking-methods',
  },
  {
    slug: 'smart-shopping-vietnam',
    title: 'Đi Chợ Thông minh ở Việt Nam',
    description: 'Hướng dẫn chọn thực phẩm tươi, đọc nhãn, so sánh giá, mua theo mùa ở chợ Việt Nam',
    category: 'daily-practices',
    tags: ['shopping', 'chợ', 'mua-sắm', 'thực-phẩm-tươi', 'đi-chợ'],
    relatedArticles: ['reading-food-labels', 'nutrition-on-budget', 'seasonal-foods-vietnam'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/smart-shopping-vietnam',
  },
  {
    slug: 'vietnamese-family-meals',
    title: 'Bữa ăn Gia đình Việt Nam: Cân bằng Dinh dưỡng',
    description: 'Cách tổ chức bữa ăn gia đình kiểu Việt Nam (cơm + canh + món mặn + rau) để đảm bảo cân bằng dinh dưỡng',
    category: 'daily-practices',
    tags: ['family-meals', 'bữa-ăn-gia-đình', 'cơm-canh', 'cân-bằng-dinh-dưỡng'],
    relatedArticles: ['healthy-plate', 'meal-planning', 'macronutrients-overview'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/vietnamese-family-meals',
  },
  {
    slug: 'street-food-vietnam',
    title: 'Thực phẩm Đường phố Việt Nam: Ăn Uống lành mạnh',
    description: 'Cách chọn lựa đồ ăn đường phố lành mạnh, tránh rủi ro. Hướng dẫn với phở, bánh mì, bún, chè',
    category: 'daily-practices',
    tags: ['street-food', 'đồ-ăn-đường-phố', 'phở', 'bánh-mì', 'ăn-ngoài'],
    relatedArticles: ['eating-out-healthy', 'sodium-health', 'nutrition-busy-lifestyle'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/street-food-vietnam',
  },
  {
    slug: 'festival-nutrition-vietnam',
    title: 'Dinh dưỡng trong Lễ hội Việt Nam',
    description: 'Cách ăn uống lành mạnh trong Tết, Trung thu, và các lễ hội khác. Hướng dẫn với bánh chưng, bánh tét, mứt, bánh trung thu',
    category: 'special-topics',
    tags: ['festival', 'lễ-hội', 'tết', 'trung-thu', 'bánh-chưng', 'mứt'],
    relatedArticles: ['healthy-weight-management', 'sodium-health', 'carbohydrates'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/festival-nutrition-vietnam',
  },
  {
    slug: 'vietnamese-fermented-foods',
    title: 'Thực phẩm Chức năng Việt Nam: Nước mắm, Tương, Chao',
    description: 'Giá trị dinh dưỡng và cách sử dụng các loại gia vị/thực phẩm lên men Việt Nam (nước mắm, tương, chao, mắm tôm)',
    category: 'general-nutrition',
    tags: ['fermented-foods', 'nước-mắm', 'tương', 'chao', 'gia-vị', 'thực-phẩm-lên-men'],
    relatedArticles: ['sodium-health', 'protein-sources-needs'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vietnamese-fermented-foods',
  },
  {
    slug: 'nutrition-manual-labor',
    title: 'Dinh dưỡng cho Người Lao động Chân tay',
    description: 'Nhu cầu năng lượng và protein cao cho người lao động chân tay. Cách bổ sung, bữa ăn thực tế cho công nhân, nông dân',
    category: 'special-topics',
    tags: ['manual-labor', 'lao-động-chân-tay', 'công-nhân', 'nông-dân', 'năng-lượng-cao'],
    relatedArticles: ['calories-energy', 'protein-sources-needs', 'hydration'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/nutrition-manual-labor',
  },
  {
    slug: 'nutrition-night-shift',
    title: 'Dinh dưỡng cho Người Làm Ca Đêm',
    description: 'Cách ăn uống khi làm ca đêm, quản lý giấc ngủ và dinh dưỡng. Timeline bữa ăn cho ca đêm',
    category: 'special-topics',
    tags: ['night-shift', 'ca-đêm', 'giấc-ngủ', 'timeline-bữa-ăn'],
    relatedArticles: ['nutrition-sleep', 'nutrition-busy-lifestyle'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/nutrition-night-shift',
  },
  {
    slug: 'nutrition-rural-vietnam',
    title: 'Dinh dưỡng cho Người Sống ở Nông thôn',
    description: 'Tận dụng thực phẩm địa phương, tự trồng, cách bảo quản. Tips tận dụng vườn nhà',
    category: 'special-topics',
    tags: ['rural', 'nông-thôn', 'thực-phẩm-địa-phương', 'tự-trồng', 'vườn-nhà'],
    relatedArticles: ['nutrition-on-budget', 'seasonal-foods-vietnam'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/nutrition-rural-vietnam',
  },
  {
    slug: 'seasonal-foods-vietnam',
    title: 'Thực phẩm Theo Mùa ở Việt Nam',
    description: 'Thực phẩm theo mùa ở Việt Nam, lợi ích, cách chọn và bảo quản. Calendar thực phẩm theo mùa',
    category: 'general-nutrition',
    tags: ['seasonal', 'theo-mùa', 'thực-phẩm-mùa', 'calendar'],
    relatedArticles: ['nutrition-on-budget', 'smart-shopping-vietnam'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/seasonal-foods-vietnam',
  },
  {
    slug: 'regional-nutrition-vietnam',
    title: 'Dinh dưỡng Theo Vùng miền Việt Nam',
    description: 'Đặc điểm dinh dưỡng theo vùng (Bắc, Trung, Nam), ưu và nhược điểm. Món ăn đặc trưng từng vùng',
    category: 'special-topics',
    tags: ['regional', 'vùng-miền', 'miền-bắc', 'miền-trung', 'miền-nam', 'đặc-trưng'],
    relatedArticles: ['vietnamese-foods-nutrition', 'sodium-health'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/regional-nutrition-vietnam',
  },

  // New Vitamins & Minerals Articles
  {
    slug: 'vitamin-e-antioxidant',
    title: 'Vitamin E và Chất chống Oxy hóa',
    description: 'Hiểu về vitamin E - vitamin quan trọng cho chất chống oxy hóa, sức khỏe da, và bảo vệ tế bào',
    category: 'vitamins-minerals',
    tags: ['vitamin-e', 'antioxidants', 'skin-health', 'dầu-thực-vật', 'quả-hạch'],
    relatedArticles: ['vitamin-c-immunity', 'antioxidants-foods', 'dietary-fats'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/vitamin-e-antioxidant',
  },
  {
    slug: 'selenium-immunity',
    title: 'Selenium và Miễn dịch',
    description: 'Hiểu về selenium - khoáng chất quan trọng cho hệ miễn dịch, chức năng tuyến giáp, và chất chống oxy hóa',
    category: 'vitamins-minerals',
    tags: ['selenium', 'immunity', 'thyroid', 'antioxidants', 'hải-sản'],
    relatedArticles: ['zinc-immunity', 'vitamin-c-immunity', 'nutrition-immune-system'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/selenium-immunity',
  },

  // New Daily Practices Articles
  {
    slug: 'breakfast-importance',
    title: 'Tầm quan trọng của Bữa sáng',
    description: 'Tại sao bữa sáng quan trọng? Lợi ích của bữa sáng, ví dụ bữa sáng lành mạnh, và cách bắt đầu ngày mới với dinh dưỡng tốt',
    category: 'daily-practices',
    tags: ['breakfast', 'bữa-sáng', 'năng-lượng', 'tập-trung', 'sức-khỏe'],
    relatedArticles: ['nutrition-busy-lifestyle', 'meal-planning', 'calories-energy', 'vietnamese-breakfast-options'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/daily-practices/breakfast-importance',
  },

  // New Vietnamese Context Articles
  {
    slug: 'vietnamese-breakfast-options',
    title: 'Lựa chọn Bữa sáng Việt Nam',
    description: 'Các lựa chọn bữa sáng phổ biến ở Việt Nam - cháo, phở, bánh mì, xôi. Cách chọn bữa sáng lành mạnh với món ăn Việt Nam',
    category: 'daily-practices',
    tags: ['bữa-sáng-việt-nam', 'cháo', 'phở', 'bánh-mì', 'xôi', 'vietnamese-breakfast'],
    relatedArticles: ['breakfast-importance', 'street-food-vietnam', 'vietnamese-foods-nutrition'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/vietnamese-breakfast-options',
  },
  {
    slug: 'vietnamese-soups-nutrition',
    title: 'Canh Việt Nam và Dinh dưỡng',
    description: 'Canh (soup) là món ăn phổ biến trong bữa ăn Việt Nam. Hiểu về giá trị dinh dưỡng của các loại canh, cách nấu canh lành mạnh',
    category: 'general-nutrition',
    tags: ['canh-việt-nam', 'vietnamese-soup', 'canh-chua', 'canh-rau', 'hydration'],
    relatedArticles: ['vietnamese-family-meals', 'vietnamese-cooking-methods', 'sodium-health', 'hydration'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/vietnamese-soups-nutrition',
  },
  {
    slug: 'vietnamese-herbs-spices',
    title: 'Gia vị và Thảo mộc Việt Nam',
    description: 'Gia vị và thảo mộc Việt Nam không chỉ tăng hương vị mà còn có giá trị dinh dưỡng và lợi ích sức khỏe',
    category: 'general-nutrition',
    tags: ['gia-vị-việt-nam', 'thảo-mộc', 'hành', 'tỏi', 'gừng', 'rau-thơm', 'antioxidants'],
    relatedArticles: ['vietnamese-cooking-methods', 'antioxidants-foods', 'sodium-health'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vietnamese-herbs-spices',
  },
  {
    slug: 'nutrition-immune-system',
    title: 'Dinh dưỡng và Hệ miễn dịch',
    description: 'Tổng quan về dinh dưỡng cho hệ miễn dịch. Các chất dinh dưỡng quan trọng, nguồn thực phẩm, và cách tăng cường hệ miễn dịch',
    category: 'special-topics',
    tags: ['immune-system', 'miễn-dịch', 'vitamin-c', 'zinc', 'selenium', 'protein'],
    relatedArticles: ['vitamin-c-immunity', 'zinc-immunity', 'selenium-immunity', 'protein-sources-needs'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/special-topics/nutrition-immune-system',
  },
  {
    slug: 'iodine-thyroid',
    title: 'Iodine và Sức khỏe Tuyến giáp',
    description: 'Hiểu về iodine - khoáng chất quan trọng cho chức năng tuyến giáp, sự trao đổi chất, và phát triển',
    category: 'vitamins-minerals',
    tags: ['iodine', 'iod', 'thyroid', 'tuyến-giáp', 'muối-iod', 'hải-sản'],
    relatedArticles: ['sodium-health', 'pregnancy-nutrition', 'vietnamese-foods-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/iodine-thyroid',
  },
  {
    slug: 'mindful-eating',
    title: 'Ăn uống Chánh niệm',
    description: 'Ăn uống chánh niệm (mindful eating) là cách ăn uống có ý thức, chú ý đến cảm giác, hương vị, và tín hiệu của cơ thể',
    category: 'daily-practices',
    tags: ['mindful-eating', 'ăn-uống-chánh-niệm', 'ý-thức-ăn-uống', 'quan-hệ-thức-ăn', 'sức-khỏe-tâm-thần'],
    relatedArticles: ['portion-sizes', 'healthy-weight-management', 'nutrition-stress'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/daily-practices/mindful-eating',
  },
  {
    slug: 'nutrition-during-illness',
    title: 'Dinh dưỡng khi Bị bệnh',
    description: 'Hướng dẫn dinh dưỡng khi bị bệnh - cách ăn uống để hỗ trợ phục hồi, giữ nước, và cung cấp năng lượng',
    category: 'daily-practices',
    tags: ['nutrition-during-illness', 'ăn-uống-khi-ốm', 'phục-hồi', 'hydration', 'cảm-cúm'],
    relatedArticles: ['hydration', 'nutrition-recovery', 'vitamin-c-immunity'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/daily-practices/nutrition-during-illness',
  },
  {
    slug: 'vietnamese-snacks-healthy',
    title: 'Snack lành mạnh Kiểu Việt Nam',
    description: 'Các lựa chọn snack lành mạnh phù hợp với văn hóa Việt Nam. Từ trái cây địa phương đến các món ăn vặt truyền thống',
    category: 'general-nutrition',
    tags: ['snack-việt-nam', 'vietnamese-snacks', 'ăn-vặt-lành-mạnh', 'healthy-snacks', 'trái-cây'],
    relatedArticles: ['smart-snacking', 'portion-sizes', 'vietnamese-foods-nutrition', 'nutrition-busy-lifestyle'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/vietnamese-snacks-healthy',
  },
  {
    slug: 'nutrition-recovery',
    title: 'Dinh dưỡng Phục hồi',
    description: 'Dinh dưỡng sau khi khỏi bệnh, sau phẫu thuật, hoặc sau chấn thương. Cách ăn uống để hỗ trợ phục hồi nhanh và hiệu quả',
    category: 'daily-practices',
    tags: ['nutrition-recovery', 'phục-hồi', 'phục-hồi-sau-bệnh', 'phục-hồi-sau-phẫu-thuật', 'protein-phục-hồi'],
    relatedArticles: ['nutrition-during-illness', 'protein-sources-needs', 'vitamin-c-immunity', 'zinc-immunity'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/daily-practices/nutrition-recovery',
  },
  {
    slug: 'food-combining',
    title: 'Kết hợp Thực phẩm Đúng cách',
    description: 'Hiểu về cách kết hợp thực phẩm để tăng hấp thu dinh dưỡng, cải thiện tiêu hóa, và tạo bữa ăn cân bằng',
    category: 'daily-practices',
    tags: ['food-combining', 'kết-hợp-thực-phẩm', 'hấp-thu-dinh-dưỡng', 'tiêu-hóa', 'bữa-ăn-cân-bằng'],
    relatedArticles: ['healthy-plate', 'vietnamese-family-meals', 'iron-deficiency-anemia', 'vegetarian-vegan-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/daily-practices/food-combining',
  },
  {
    slug: 'nutrition-mental-health',
    title: 'Dinh dưỡng và Sức khỏe Tâm thần',
    description: 'Mối liên hệ giữa dinh dưỡng và sức khỏe tâm thần. Cách ăn uống ảnh hưởng đến tâm trạng, stress, và sức khỏe não bộ',
    category: 'special-topics',
    tags: ['nutrition-mental-health', 'ăn-uống-tâm-trạng', 'stress', 'sức-khỏe-não-bộ', 'depression', 'anxiety'],
    relatedArticles: ['dietary-fats', 'carbohydrates', 'vitamin-b-complex', 'mindful-eating'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/special-topics/nutrition-mental-health',
  },
  {
    slug: 'nutrition-skin-health',
    title: 'Dinh dưỡng và Sức khỏe Da',
    description: 'Mối liên hệ giữa dinh dưỡng và sức khỏe da. Các chất dinh dưỡng quan trọng cho da, thực phẩm tốt cho da',
    category: 'special-topics',
    tags: ['nutrition-skin-health', 'sức-khỏe-da', 'vitamin-c-da', 'vitamin-e-da', 'collagen', 'antioxidants'],
    relatedArticles: ['vitamin-c-immunity', 'vitamin-e-antioxidant', 'dietary-fats', 'hydration'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/special-topics/nutrition-skin-health',
  },
  {
    slug: 'nutrition-aging-well',
    title: 'Dinh dưỡng Lão hóa Khỏe mạnh',
    description: 'Dinh dưỡng cho người cao tuổi - cách ăn uống để lão hóa khỏe mạnh, duy trì sức khỏe, và phòng ngừa bệnh tật',
    category: 'special-topics',
    tags: ['nutrition-aging', 'lão-hóa-khỏe-mạnh', 'dinh-duong-cho-nguoi-cao-tuoi', 'healthy-aging', 'người-cao-tuổi'],
    relatedArticles: ['dinh-duong-cho-nguoi-cao-tuoi', 'protein-sources-needs', 'calcium-bone-health', 'vietnamese-soups-nutrition'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/special-topics/nutrition-aging-well',
  },
  {
    slug: 'vietnamese-drinks-nutrition',
    title: 'Đồ uống Việt Nam và Dinh dưỡng',
    description: 'Các loại đồ uống phổ biến ở Việt Nam - trà, cà phê, nước dừa, nước mía. Giá trị dinh dưỡng và cách chọn đồ uống lành mạnh',
    category: 'general-nutrition',
    tags: ['đồ-uống-việt-nam', 'vietnamese-drinks', 'trà', 'cà-phê', 'nước-dừa', 'hydration'],
    relatedArticles: ['hydration', 'sugar-health', 'antioxidants-foods'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/vietnamese-drinks-nutrition',
  },
  {
    slug: 'nutrition-bone-health',
    title: 'Dinh dưỡng và Sức khỏe Xương',
    description: 'Tổng quan về dinh dưỡng cho sức khỏe xương. Calcium, vitamin D, protein, và các chất dinh dưỡng quan trọng cho xương khỏe mạnh. Phòng ngừa loãng xương.',
    category: 'special-topics',
    tags: ['sức-khỏe-xương', 'bone-health', 'calcium', 'vitamin-d', 'loãng-xương', 'osteoporosis'],
    relatedArticles: ['calcium-bone-health', 'vitamin-d', 'protein-sources-needs', 'dinh-duong-cho-nguoi-cao-tuoi'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/special-topics/nutrition-bone-health',
  },
  {
    slug: 'vitamin-b-complex',
    title: 'Vitamin B Complex và năng lượng',
    description: 'Hiểu về vitamin B complex - nhóm vitamin quan trọng cho năng lượng, chức năng não, và sức khỏe tổng thể. Các loại vitamin B, nguồn thực phẩm, và nhu cầu.',
    category: 'vitamins-minerals',
    tags: ['vitamin-b', 'vitamin-b-complex', 'năng-lượng', 'energy', 'chức-năng-não', 'thiamine', 'riboflavin'],
    relatedArticles: ['calories-energy', 'carbohydrates', 'pregnancy-nutrition', 'vegetarian-vegan-nutrition'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/vitamin-b-complex',
  },
  {
    slug: 'copper-health',
    title: 'Đồng và Sức khỏe',
    description: 'Tìm hiểu về đồng - khoáng chất vi lượng quan trọng cho sức khỏe, chức năng miễn dịch, sản xuất tế bào máu, và bảo vệ tế bào khỏi tổn thương oxy hóa.',
    category: 'vitamins-minerals',
    tags: ['đồng', 'copper', 'khoáng-chất', 'miễn-dịch', 'tế-bào-máu', 'chống-oxy-hóa'],
    relatedArticles: ['iron-anemia', 'zinc-immunity', 'selenium-immunity', 'antioxidants'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/vitamins-minerals/copper-health',
  },
  {
    slug: 'vietnamese-foods-nutrition',
    title: 'Thực phẩm Việt Nam: Nguồn Dinh dưỡng Tốt',
    description: 'Khám phá giá trị dinh dưỡng của thực phẩm truyền thống Việt Nam - rau củ, protein, carbohydrate, và trái cây. Hướng dẫn cách chọn và sử dụng thực phẩm Việt Nam để có chế độ ăn lành mạnh.',
    category: 'general-nutrition',
    tags: ['thực-phẩm-việt-nam', 'dinh-dưỡng-việt-nam', 'ẩm-thực-việt', 'rau-củ', 'protein-việt-nam'],
    relatedArticles: ['protein-sources-needs', 'carbohydrates', 'macronutrients-overview'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/vietnamese-foods-nutrition',
  },
  {
    slug: 'vietnamese-cooking-methods',
    title: 'Cách Nấu Ăn lành mạnh Kiểu Việt Nam',
    description: 'Hướng dẫn các phương pháp nấu ăn truyền thống Việt Nam lành mạnh - luộc, hấp, kho, nướng, xào. Cách giữ dinh dưỡng và giảm dầu mỡ, muối.',
    category: 'daily-practices',
    tags: ['nấu-ăn-việt-nam', 'phương-pháp-nấu-ăn', 'luộc', 'hấp', 'kho', 'lành-mạnh'],
    relatedArticles: ['sodium-health', 'dietary-fats', 'vietnamese-foods-nutrition'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/daily-practices/vietnamese-cooking-methods',
  },
  {
    slug: 'smart-shopping-vietnam',
    title: 'Đi Chợ Thông minh ở Việt Nam',
    description: 'Hướng dẫn cách đi chợ thông minh ở Việt Nam - chọn thực phẩm tươi, đọc nhãn, so sánh giá, mua theo mùa. Checklist đi chợ.',
    category: 'daily-practices',
    tags: ['đi-chợ', 'mua-sắm-thực-phẩm', 'chợ-việt-nam', 'thực-phẩm-tươi', 'mua-theo-mùa'],
    relatedArticles: ['seasonal-foods-vietnam', 'nutrition-on-budget', 'vietnamese-foods-nutrition'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/daily-practices/smart-shopping-vietnam',
  },
  {
    slug: 'vietnamese-family-meals',
    title: 'Bữa ăn Gia đình Việt Nam: Cân bằng Dinh dưỡng',
    description: 'Hiểu về cấu trúc bữa ăn gia đình Việt Nam truyền thống - cơm + canh + món mặn + rau. Cách cân bằng dinh dưỡng và ví dụ bữa ăn lành mạnh.',
    category: 'daily-practices',
    tags: ['bữa-ăn-gia-đình', 'cấu-trúc-bữa-ăn', 'bữa-ăn-việt-nam', 'cân-bằng-dinh-dưỡng'],
    relatedArticles: ['meal-planning', 'macronutrients-overview', 'vietnamese-foods-nutrition'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/daily-practices/vietnamese-family-meals',
  },
  {
    slug: 'street-food-vietnam',
    title: 'Thực phẩm Đường phố Việt Nam: Ăn Uống lành mạnh',
    description: 'Hướng dẫn cách ăn uống lành mạnh với đồ ăn đường phố Việt Nam. Lựa chọn tốt (phở, bánh mì, bún) và lựa chọn nên hạn chế. Tips an toàn và cách điều chỉnh.',
    category: 'daily-practices',
    tags: ['đồ-ăn-đường-phố', 'street-food', 'phở', 'bánh-mì', 'ăn-uống-lành-mạnh'],
    relatedArticles: ['eating-out-healthy', 'sodium-health', 'nutrition-busy-lifestyle'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/daily-practices/street-food-vietnam',
  },
  {
    slug: 'festival-nutrition-vietnam',
    title: 'Dinh dưỡng trong Lễ hội Việt Nam',
    description: 'Hướng dẫn cách ăn uống lành mạnh trong các lễ hội Việt Nam - Tết, Trung thu, và các lễ hội khác. Cách cân bằng và tips thực hành.',
    category: 'special-topics',
    tags: ['lễ-hội-việt-nam', 'Tết', 'Trung-thu', 'bánh-chưng', 'bánh-tét', 'mứt'],
    relatedArticles: ['healthy-weight-management', 'sodium-health', 'carbohydrates'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/special-topics/festival-nutrition-vietnam',
  },
  {
    slug: 'vietnamese-fermented-foods',
    title: 'Thực phẩm Chức năng Việt Nam: Nước mắm, Tương, Chao',
    description: 'Tìm hiểu về các loại gia vị và thực phẩm lên men Việt Nam - nước mắm, tương, chao, mắm tôm. Giá trị dinh dưỡng, cách sử dụng, và lưu ý về natri.',
    category: 'general-nutrition',
    tags: ['nước-mắm', 'tương', 'chao', 'mắm-tôm', 'gia-vị-việt-nam', 'thực-phẩm-lên-men'],
    relatedArticles: ['sodium-health', 'protein-sources-needs', 'probiotics-gut-health'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/general-nutrition/vietnamese-fermented-foods',
  },
  {
    slug: 'nutrition-manual-labor',
    title: 'Dinh dưỡng cho Người Lao động Chân tay',
    description: 'Hướng dẫn dinh dưỡng cho người lao động chân tay - nhu cầu năng lượng cao (2,500-3,500 calo/ngày), nhu cầu protein cao, và hydration. Ví dụ bữa ăn cho công nhân, nông dân.',
    category: 'special-topics',
    tags: ['dinh-dưỡng-lao-động', 'công-nhân', 'nông-dân', 'năng-lượng-cao', 'protein-cao'],
    relatedArticles: ['calories-energy', 'protein-sources-needs', 'hydration'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/special-topics/nutrition-manual-labor',
  },
  {
    slug: 'nutrition-night-shift',
    title: 'Dinh dưỡng cho Người Làm Ca Đêm',
    description: 'Hướng dẫn cách ăn uống khi làm ca đêm - timeline bữa ăn (trước, trong, sau ca đêm), quản lý giấc ngủ, thực phẩm nên tránh. Tips thực hành.',
    category: 'special-topics',
    tags: ['ca-đêm', 'night-shift', 'dinh-dưỡng-ca-đêm', 'giấc-ngủ', 'caffeine'],
    relatedArticles: ['nutrition-sleep', 'nutrition-busy-lifestyle'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/special-topics/nutrition-night-shift',
  },
  {
    slug: 'nutrition-rural-vietnam',
    title: 'Dinh dưỡng cho Người Sống ở Nông thôn',
    description: 'Hướng dẫn tận dụng thực phẩm địa phương ở nông thôn Việt Nam - rau vườn, trái cây, cá sông, thịt gà vườn. Cách bảo quản và tips tận dụng vườn nhà.',
    category: 'special-topics',
    tags: ['nông-thôn', 'thực-phẩm-địa-phương', 'rau-vườn', 'trái-cây-địa-phương', 'cá-sông'],
    relatedArticles: ['nutrition-on-budget', 'seasonal-foods-vietnam'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/special-topics/nutrition-rural-vietnam',
  },
  {
    slug: 'seasonal-foods-vietnam',
    title: 'Thực phẩm Theo Mùa ở Việt Nam',
    description: 'Khám phá thực phẩm theo mùa ở Việt Nam - mùa xuân, hè, thu, đông. Lợi ích của thực phẩm theo mùa (rẻ hơn, tươi hơn, dinh dưỡng hơn) và cách bảo quản.',
    category: 'general-nutrition',
    tags: ['thực-phẩm-theo-mùa', 'seasonal-foods', 'mùa-xuân', 'mùa-hè', 'mùa-thu', 'mùa-đông'],
    relatedArticles: ['nutrition-on-budget', 'smart-shopping-vietnam'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/general-nutrition/seasonal-foods-vietnam',
  },
  {
    slug: 'regional-nutrition-vietnam',
    title: 'Dinh dưỡng Theo Vùng miền Việt Nam',
    description: 'Khám phá đặc điểm dinh dưỡng theo vùng miền Việt Nam - Miền Bắc, Miền Trung, Miền Nam. Món ăn đặc trưng, ưu và nhược điểm, cách cân bằng.',
    category: 'special-topics',
    tags: ['vùng-miền-việt-nam', 'miền-bắc', 'miền-trung', 'miền-nam', 'món-ăn-đặc-trưng'],
    relatedArticles: ['vietnamese-foods-nutrition', 'sodium-health'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/special-topics/regional-nutrition-vietnam',
  },
  {
    slug: 'nutrition-night-shift',
    title: 'Dinh dưỡng cho Người Làm Ca Đêm',
    description: 'Hướng dẫn cách ăn uống khi làm ca đêm - timeline bữa ăn (trước, trong, sau ca đêm), quản lý giấc ngủ, thực phẩm nên tránh. Tips thực hành.',
    category: 'special-topics',
    tags: ['ca-đêm', 'night-shift', 'dinh-dưỡng-ca-đêm', 'giấc-ngủ', 'caffeine'],
    relatedArticles: ['nutrition-sleep', 'nutrition-busy-lifestyle'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/special-topics/nutrition-night-shift',
  },
  {
    slug: 'nutrition-rural-vietnam',
    title: 'Dinh dưỡng cho Người Sống ở Nông thôn',
    description: 'Hướng dẫn tận dụng thực phẩm địa phương ở nông thôn Việt Nam - rau vườn, trái cây, cá sông, thịt gà vườn. Cách bảo quản và tips tận dụng vườn nhà.',
    category: 'special-topics',
    tags: ['nông-thôn', 'thực-phẩm-địa-phương', 'rau-vườn', 'trái-cây-địa-phương', 'cá-sông'],
    relatedArticles: ['nutrition-on-budget', 'seasonal-foods-vietnam'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/special-topics/nutrition-rural-vietnam',
  },
  {
    slug: 'seasonal-foods-vietnam',
    title: 'Thực phẩm Theo Mùa ở Việt Nam',
    description: 'Khám phá thực phẩm theo mùa ở Việt Nam - mùa xuân, hè, thu, đông. Lợi ích của thực phẩm theo mùa (rẻ hơn, tươi hơn, dinh dưỡng hơn) và cách bảo quản.',
    category: 'general-nutrition',
    tags: ['thực-phẩm-theo-mùa', 'seasonal-foods', 'mùa-xuân', 'mùa-hè', 'mùa-thu', 'mùa-đông'],
    relatedArticles: ['nutrition-on-budget', 'smart-shopping-vietnam'],
    level: 'foundation',
    targetAudience: 'both',
    href: '/knowledge/general-nutrition/seasonal-foods-vietnam',
  },
  {
    slug: 'festival-nutrition-vietnam',
    title: 'Dinh dưỡng trong Lễ hội Việt Nam',
    description: 'Hướng dẫn cách ăn uống lành mạnh trong các lễ hội Việt Nam - Tết, Trung thu, và các lễ hội khác. Cách cân bằng và tips thực hành.',
    category: 'special-topics',
    tags: ['lễ-hội-việt-nam', 'Tết', 'Trung-thu', 'bánh-chưng', 'bánh-tét', 'mứt'],
    relatedArticles: ['healthy-weight-management', 'sodium-health', 'carbohydrates'],
    level: 'foundation',
    targetAudience: 'general',
    href: '/knowledge/special-topics/festival-nutrition-vietnam',
  },
  {
    slug: 'emergency-nutrition',
    title: 'Dinh dưỡng trong Cấp cứu',
    description: 'Hướng dẫn về dinh dưỡng trong các tình huống cấp cứu, chấn thương, và phẫu thuật. Hiểu về stress metabolism và nhu cầu dinh dưỡng đặc biệt.',
    category: 'clinical-foundations',
    tags: ['cấp cứu', 'chấn thương', 'phẫu thuật', 'stress metabolism', 'nhiễm trùng'],
    relatedArticles: ['assessment-process', 'needs-estimation', 'dinh-duong-sau-phau-thuat'],
    level: 'intermediate',
    targetAudience: 'professional',
    href: '/knowledge/emergency-nutrition',
  },
  {
    slug: 'sports-nutrition',
    title: 'Dinh dưỡng Thể thao',
    description: 'Hướng dẫn về dinh dưỡng cho vận động viên và người tập thể dục. Nhu cầu năng lượng, protein, carbohydrate, và hydration trong thể thao.',
    category: 'special-topics',
    tags: ['thể thao', 'vận động viên', 'protein', 'carbohydrate', 'hydration', 'exercise'],
    relatedArticles: ['exercise-nutrition', 'protein-sources-needs', 'hydration'],
    level: 'intermediate',
    targetAudience: 'both',
    href: '/knowledge/sports-nutrition',
  },
];

/**
 * Get article metadata by slug
 */
export function getArticle(slug: string): ArticleMetadata | undefined {
  return articles.find(article => article.slug === slug);
}

/**
 * Get all articles in a category
 */
export function getArticlesByCategory(category: ArticleCategory): ArticleMetadata[] {
  return articles.filter(article => article.category === category);
}

/**
 * Get related articles for a given article slug
 */
export function getRelatedArticles(slug: string, limit: number = 5): ArticleMetadata[] {
  const article = getArticle(slug);
  if (!article) return [];

  const related = article.relatedArticles
    .map(relatedSlug => getArticle(relatedSlug))
    .filter((article): article is ArticleMetadata => article !== undefined)
    .slice(0, limit);

  return related;
}

/**
 * Search articles by query (searches title, description, and tags)
 */
export function searchArticles(query: string): ArticleMetadata[] {
  const lowerQuery = query.toLowerCase();
  return articles.filter(article => 
    article.title.toLowerCase().includes(lowerQuery) ||
    article.description.toLowerCase().includes(lowerQuery) ||
    article.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
}

/**
 * Get articles by tag
 */
export function getArticlesByTag(tag: string): ArticleMetadata[] {
  return articles.filter(article => 
    article.tags.some(t => t.toLowerCase() === tag.toLowerCase())
  );
}

/**
 * Get all unique categories
 */
export function getCategories(): ArticleCategory[] {
  return Array.from(new Set(articles.map(article => article.category)));
}

/**
 * Get all unique tags
 */
export function getTags(): string[] {
  const allTags = articles.flatMap(article => article.tags);
  return Array.from(new Set(allTags)).sort();
}
