"""
Sync canonical DisplayName from CSV into vietnamese-food-extended.ts
to fix mojibake / inconsistent Vietnamese names in the TS database.

Inputs:
  - DANH-MUC-THUC-PHAM-CANONICAL.csv (generated by normalize_food_catalog.py)
  - clinical-nutrition/lib/vietnamese-food-extended.ts

Behavior:
  - For mỗi hàng canonical:
      Id, DisplayName
    tìm block chứa `id: "Id"` trong extended file
    và thay giá trị của `name: "..."` thành DisplayName (đã chuẩn UTF-8).

  - Không đụng tới nameEn, nutrients, disease info.

Usage:
  cd d:\\1 app\\nutrition
  python scripts/sync_canonical_names_to_extended.py
"""

from __future__ import annotations

import csv
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CANONICAL_CSV = ROOT / "DANH-MUC-THUC-PHAM-CANONICAL.csv"
EXTENDED_TS = ROOT / "clinical-nutrition" / "lib" / "vietnamese-food-extended.ts"


def ts_escape(s: str) -> str:
    """Escape a string for inclusion in TS double-quoted literal."""
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    )


def load_canonical_names(path: Path) -> dict[str, str]:
    mapping: dict[str, str] = {}
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            fid = (row.get("Id") or "").strip()
            dn = (row.get("DisplayName") or "").strip()
            if not fid or not dn:
                continue

            mapping[fid] = dn
    return mapping


def main() -> int:
    id_to_name = load_canonical_names(CANONICAL_CSV)
    content = EXTENDED_TS.read_text(encoding="utf-8")

    total_replacements = 0
    for fid, display_name in id_to_name.items():
        escaped = ts_escape(display_name)
        # Match from id: "fid" up tới dòng name: "..."
        pattern = re.compile(
            r'(id:\s*"' + re.escape(fid) + r'"\s*,[^{}]*?\n\s*name:\s*")([^"]*)(")',
            re.MULTILINE | re.DOTALL,
        )
        new_content, n = pattern.subn(r'\1' + escaped + r'\3', content)
        if n > 0:
            total_replacements += n
            content = new_content

    if total_replacements:
        EXTENDED_TS.write_text(content, encoding="utf-8")
        print(f"Updated name for {total_replacements} items in vietnamese-food-extended.ts")
    else:
        print("No matching ids found to update.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

